import React, { useState } from 'react';
import type { Order } from '../../types/servos';
import { useServOS } from '../../context/ServOSContext';
import { isNative } from '../../runtime/RuntimeProvider';

interface Props {
  isOpen: boolean; onClose: () => void; order: Order | null; isProForma?: boolean;
  paymentDetails?: { tenderType: string; receiptRef?: string; cashTendered?: number; changeDue?: number; guestName?: string; roomNumber?: string };
}
export const ThermalReceiptModal = ({ isOpen, onClose, order, paymentDetails, isProForma = false }: Props) => {
  const { currentProperty, currentOutlet } = useServOS();
  const [message, setMessage] = useState('');
  if (!isOpen || !order) return null;
  const title = isProForma ? 'Pro-forma bill' : 'Internal receipt';
  const money = (amount?: number) => `KES ${(amount || 0).toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const content = [currentProperty.name, currentOutlet.name, title, !isNative ? 'SAMPLE — UI PREVIEW' : '', `Order: ${order.orderNumber}`, `Time: ${new Date(order.completedAt || order.createdAt).toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })}`, ...order.items.map(i => `${i.quantity} × ${i.productName}: ${money(i.totalPrice)}`), `Total: ${money(order.grandTotal)}`, paymentDetails ? `Recorded tender: ${paymentDetails.tenderType}; reference: ${paymentDetails.receiptRef || '—'}` : `Recorded paid: ${money(order.amountPaid)}`, 'This document is not evidence of eTIMS submission.', 'Thank you.'].filter(Boolean).join('\n');
  const download = () => { const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `receipt-${order.orderNumber.replace(/[^a-z0-9_-]/gi, '')}.txt`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <div className="fixed inset-0 z-50 bg-black/80 grid place-items-center p-4"><section role="dialog" aria-modal="true" aria-labelledby="receipt-heading" className="max-w-lg w-full max-h-[90vh] overflow-auto rounded-xl bg-slate-900 border border-slate-700 p-5 space-y-4"><header className="flex justify-between"><h2 id="receipt-heading" className="font-bold text-xl">{title}</h2><button onClick={onClose} aria-label="Close receipt">Close</button></header><div className="servos-receipt bg-white text-black p-5 font-mono text-xs space-y-3"><h3 className="font-bold text-center">{currentProperty.name}</h3><p className="text-center">{currentOutlet.name}</p>{!isNative && <p className="font-bold">SAMPLE — UI PREVIEW</p>}<p>{title} · {order.orderNumber}</p><p>{new Date(order.completedAt || order.createdAt).toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })}</p><table className="w-full"><thead><tr><th className="text-left">Item</th><th>Qty</th><th className="text-right">Amount</th></tr></thead><tbody>{order.items.map(i => <tr key={i.id}><td className="py-1">{i.productName}</td><td className="text-center">{i.quantity}</td><td className="text-right">{money(i.totalPrice)}</td></tr>)}</tbody></table><p className="border-t pt-2 font-bold">Total: {money(order.grandTotal)}</p>{paymentDetails && <><p>Recorded tender: {paymentDetails.tenderType}</p><p>Reference: {paymentDetails.receiptRef || '—'}</p>{paymentDetails.tenderType === 'MPESA' && <p>Manually confirmed; reconciliation is recorded separately.</p>}</>}<p>This document is not evidence of eTIMS submission.</p><p className="text-center">Thank you.</p></div><div className="flex gap-3 flex-wrap"><button className="bg-amber-400 text-slate-950 rounded p-2" onClick={() => { window.print(); setMessage('Print dialog requested. Confirm output on your printer.'); }}>Print / save PDF</button><button className="border border-slate-600 rounded p-2" onClick={download}>Download text</button><button className="border border-slate-600 rounded p-2" onClick={() => void navigator.clipboard.writeText(content).then(() => setMessage('Receipt text copied.')).catch(() => setMessage('Clipboard unavailable; use Download text.'))}>Copy text</button></div>{message && <p role="status" className="text-xs">{message}</p>}</section><style>{`@media print { body * { visibility: hidden !important; } .servos-receipt, .servos-receipt * { visibility: visible !important; } .servos-receipt { position: absolute; left: 0; top: 0; width: 80mm; } }`}</style></div>;
};
