import React, { useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { useRuntime } from './RuntimeProvider';

export const BusinessAdminView = () => {
  const runtime = useRuntime()!;
  const [name, setName] = useState(''); const [pin, setPin] = useState(''); const [role, setRole] = useState('Server');
  const [float, setFloat] = useState('0'); const [counted, setCounted] = useState('0'); const [reason, setReason] = useState('');
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const tills = runtime.snapshot!.records.filter(r => r.collection === 'tillSessions');
  const till = tills.find(r => r.data.status === 'OPEN');
  const execute = async (action: () => Promise<unknown>) => { setBusy(true); setMessage(''); try { await action(); setMessage('Saved locally.'); } catch(e) { setMessage(String(e)); } finally { setBusy(false); } };
  const field = 'bg-slate-950 border border-slate-700 rounded p-2 text-white';
  return <div className="p-5 overflow-auto space-y-6"><h1 className="text-2xl font-bold">Business administration</h1><p className="text-slate-400">{runtime.session!.name} · {runtime.session!.role} · Last sync: {runtime.snapshot!.lastSync || 'Never'}</p><div className="flex gap-3 flex-wrap"><button disabled={runtime.syncing} onClick={() => void runtime.sync()} className={field}>Sync {runtime.snapshot!.pendingCount} pending operations</button><button onClick={() => void runtime.lock()} className={field}>Lock terminal / change staff</button><button className={field} onClick={() => void invoke<string>('runtime_backup', { token: runtime.session!.token }).then(path => setMessage(`Local backup created: ${path}`)).catch(e => setMessage(String(e)))}>Create local backup</button></div>
  <section className="space-y-3 border border-slate-700 rounded-xl p-4"><h2 className="font-bold">Till session</h2>{till ? <><p>Expected cash: KES {till.data.expectedCashInDrawer}</p><label className="block">Counted cash <input className={field} type="number" min="0" step="0.01" value={counted} onChange={e => setCounted(e.target.value)} /></label><label className="block">Variance reason <input className={field} value={reason} onChange={e => setReason(e.target.value)} /></label><button disabled={busy} className={field} onClick={() => void execute(() => runtime.command('till.close', { tillId: till.id, countedCash: Number(counted), reason }))}>Close till</button></> : <><label>Opening float <input className={field} type="number" min="0" step="0.01" value={float} onChange={e => setFloat(e.target.value)} /></label><button disabled={busy} className={field} onClick={() => void execute(() => runtime.command('till.open', { floatAmount: Number(float) }))}>Open till</button></>}</section>
  {runtime.session!.role === 'Admin' && <form className="space-y-3 border border-slate-700 rounded-xl p-4" onSubmit={e => { e.preventDefault(); void execute(async () => { await runtime.command('staff.create', { name, pin, role }); setName(''); setPin(''); }); }}><h2 className="font-bold">Enroll staff</h2><label className="block">Name <input required className={field} value={name} onChange={e => setName(e.target.value)} /></label><label className="block">PIN <input required type="password" inputMode="numeric" minLength={6} maxLength={12} className={field} value={pin} onChange={e => setPin(e.target.value)} /></label><label className="block">Role <select className={field} value={role} onChange={e => setRole(e.target.value)}><option>Server</option><option>Manager</option><option>Admin</option></select></label><button disabled={busy} className={field}>Create staff account</button></form>}
  {message && <p role="status">{message}</p>}</div>;
};
