import React, { useState } from 'react';
import { useRuntime } from './RuntimeProvider';

export const ManualReconciliationView = () => {
  const runtime = useRuntime()!;
  const [selected, setSelected] = useState(''); const [amount, setAmount] = useState(''); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const receipts = runtime.snapshot!.records.filter(r => r.collection === 'mpesaReceipts');
  const field = 'bg-slate-950 border border-slate-700 rounded p-2';
  return <div className="p-5 overflow-auto space-y-5"><h1 className="text-2xl font-bold">Manual M-Pesa reconciliation</h1><p className="text-slate-400">Compare recorded receipts with the business account statement. Cashier confirmation does not verify a receipt with Safaricom.</p>{receipts.length === 0 && <p>No M-Pesa receipts recorded.</p>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Code', 'Account', 'Received', 'Allocated', 'Status', 'Review'].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{receipts.map(r => <tr key={r.id} className="border-t border-slate-800"><td className="p-3">{r.data.code}</td><td>{r.data.account}</td><td>{r.data.receivedAmount}</td><td>{r.data.allocatedAmount}</td><td>{r.data.reconciliationStatus}</td><td><button disabled={r.data.reconciliationStatus === 'RECONCILED'} className={field} onClick={() => { setSelected(r.id); setAmount(''); setReference(''); setNotes(''); }}>Review</button></td></tr>)}</tbody></table></div>{selected && <form className="space-y-3" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await runtime.command('mpesa.reconcile', { receiptId: selected, statementAmount: Number(amount), statementReference: reference, notes }); setSelected(''); } catch(e) {setError(String(e));} finally {setBusy(false);} }}><label className="block">Statement amount <input required type="number" step="0.01" min="0" className={field} value={amount} onChange={e => setAmount(e.target.value)} /></label><label className="block">Statement reference <input required className={field} value={reference} onChange={e => setReference(e.target.value)} /></label><label className="block">Review notes <input required className={field} value={notes} onChange={e => setNotes(e.target.value)} /></label><button disabled={busy} className={field}>Confirm reconciliation</button><button type="button" className={field} onClick={() => setSelected('')}>Cancel</button></form>}{error && <p role="alert" className="text-rose-300">{error}</p>}</div>;
};
