import React,{useEffect,useRef,useState} from 'react';
import {BusinessStore,type QueuedCommand} from './BusinessStore';
import {startAutomaticSync,synchronizeStore} from './sync';
import {allowed,loadAuthorizedSnapshot,openWebDevice,type BusinessRecord,type Rpc,type WebSession} from './session';

type Values=Record<string,string>;
type Field={key:string;label:string;type?:'text'|'number'|'money'|'datetime-local'|'select';options?:Array<{value:string;label:string}>;value?:string;optional?:boolean};
type Editor={title:string;operation:string;collection:string;id:string;fields:Field[];payload:(values:Values)=>Record<string,unknown>};
const input='w-full rounded-lg border border-slate-600 bg-slate-950 p-2 text-white';
const button='rounded-lg border border-slate-600 px-3 py-2 disabled:opacity-40';
const label=(r:BusinessRecord)=>String(r.data.name||r.data.number||r.data.tag||r.id);
const money=(value:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(value||0)/100);
const minor=(value:string)=>Math.round(Number(value)*100);

export function WebBusinessApp({initialSession,rpc,onSignOut}:{initialSession:WebSession;rpc:Rpc;onSignOut:()=>void}){
 const [session,setSession]=useState(initialSession);const [records,setRecords]=useState<BusinessRecord[]>([]);const [queue,setQueue]=useState<QueuedCommand[]>([]);
 const [drafts,setDrafts]=useState<Array<{id:string;operation:string;payload:Record<string,unknown>;updatedAt:string}>>([]);
 const [tab,setTab]=useState<'Rooms'|'Assets'|'Settings'|'Activity'>('Rooms');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);
 const [editor,setEditor]=useState<Editor|null>(null);const [values,setValues]=useState<Values>({});
 const store=useRef<BusinessStore|null>(null);const rpcRef=useRef(rpc);rpcRef.current=rpc;const sessionRef=useRef(session);sessionRef.current=session;
 const syncRef=useRef<()=>Promise<void>>(async()=>{});
 const refresh=async()=>{if(!store.current)return;const [r,q,d]=await Promise.all([store.current.records(),store.current.queue(),store.current.drafts()]);setRecords(r);setQueue(q);setDrafts(d)};
 useEffect(()=>{
  let stopped=false;let needsSnapshot=true;let automatic:ReturnType<typeof startAutomaticSync>|undefined;let opened:BusinessStore|undefined;
  const run=async()=>{
   if(!opened||stopped)return;
   let latest:WebSession;try{latest=await rpcRef.current('rpc/servos_v2_session',{})}catch(error){if([401,403].includes((error as {status?:number}).status||0)){setReady(false);setRecords([])}throw error}
   if(!latest.enabled||latest.businessId!==initialSession.businessId||latest.actorId!==initialSession.actorId){setReady(false);setRecords([]);throw new Error('This workspace is no longer enabled for this session. Sign in again.')}
   if(needsSnapshot||latest.policyVersion!==await opened.policyVersion()){
    setReady(false);setRecords([]);await navigator.locks.request(`servos-v2-sync:${opened.scope}:${opened.deviceId}:${opened.actorId}`,()=>loadAuthorizedSnapshot(opened!,rpcRef.current,latest));needsSnapshot=false;
   }
   sessionRef.current=latest;if(!stopped)setSession(latest);
   await synchronizeStore(opened,{execute:command=>rpcRef.current('rpc/servos_v2_execute',{command}),pull:cursor=>rpcRef.current('rpc/servos_v2_pull',{after_sequence:cursor,page_size:100})});
   if(!stopped){await refresh();setReady(true);setError('')}
  };
  syncRef.current=run;
  void(async()=>{try{
   opened=await openWebDevice(initialSession,rpcRef.current);if(stopped){opened.close();return}store.current=opened;
   automatic=startAutomaticSync(run,e=>{if(!stopped){setError(String(e));if((e as {status?:number}).status===403){setReady(false);setRecords([])}}});
  }catch(e){if(!stopped)setError(String(e))}})();
  return()=>{stopped=true;automatic?.stop();opened?.close();store.current=null};
 },[initialSession.businessId,initialSession.actorId]);
 const active=(collection:string)=>records.filter(r=>r.collection===collection&&!r.archived);
 const find=(collection:string,id:string)=>records.find(r=>r.collection===collection&&r.id===id);
 const choices=(collection:string)=>active(collection).map(r=>({value:r.id,label:label(r)}));
 const select=(key:string,title:string,collection:string):Field=>({key,label:title,type:'select',options:choices(collection)});
 const open=(next:Editor)=>{setEditor(next);setValues(Object.fromEntries(next.fields.map(f=>[f.key,f.value??''])));setError('')};
 const submit=async(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>{
  if(!store.current||!ready)return;setBusy(true);setError('');setNotice('');
  try{
   if(!navigator.onLine){await store.current.saveDraft(crypto.randomUUID(),operation,payload);setNotice('Draft saved on this browser. It has not been finalized.');await refresh();setEditor(null);return}
   const baselines=records.map(({collection,id,version})=>({collection,id,version}));
   for(const target of [collection,...(operation.startsWith('stay.')?['folios','stays']:[])])if(!baselines.some(r=>r.collection===target&&r.id===id))baselines.push({collection:target,id,version:0});
   const command=await store.current.enqueue(operation,payload,baselines);setEditor(null);setNotice('Saved on this browser; awaiting server validation.');await refresh();
   try{await syncRef.current()}catch(e){setError(`${String(e)}. The queued command is retained for retry.`);return}
   const result=(await store.current.queue()).find(q=>q.id===command.id)?.result;
   if(result?.status==='SYNCHRONIZED')setNotice('Saved and synchronized.');
   else{setNotice('');setError(result?.error?.message||'Waiting for server confirmation. See Activity.')}
  }catch(e){setError(String(e))}finally{setBusy(false)}
 };
 const action=(title:string,operation:string,collection:string,id:string,fields:Field[]=[],extra:Record<string,unknown>={})=>open({title,operation,collection,id,fields,payload:v=>({id,...extra,...v})});
 const master=(collection:string,title:string,fields:Field[])=>{const id=crypto.randomUUID();open({title,operation:'record.save',collection,id,fields,payload:v=>({id,collection,data:{...v,...(collection==='roomTypes'?{maxGuests:Number(v.maxGuests)}:{}),...(collection==='suppliers'?{paymentTermsDays:Number(v.paymentTermsDays)}:{})}})})};
 const editRoom=(room?:BusinessRecord)=>{const id=room?.id||crypto.randomUUID();const fields:Field[]=[{key:'number',label:'Room number'},select('roomTypeId','Room type','roomTypes'),{key:'capacity',label:'Guest capacity',type:'number'},{key:'turnaroundMinutes',label:'Turnaround minutes',type:'number'}];open({title:room?'Edit room':'Add room',operation:'room.save',collection:'rooms',id,fields:fields.map(f=>({...f,value:String(room?.data[f.key]??(f.key==='turnaroundMinutes'?30:''))})),payload:v=>({id,data:{...v,capacity:Number(v.capacity),turnaroundMinutes:Number(v.turnaroundMinutes)}})})};
 const addRate=()=>{const id=crypto.randomUUID();open({title:'Add room rate',operation:'ratePlan.save',collection:'ratePlans',id,fields:[{key:'name',label:'Rate name'},select('roomTypeId','Room type','roomTypes'),{key:'mode',label:'Stay type',type:'select',options:[{value:'NIGHTLY',label:'Nightly'},{value:'DAY_USE',label:'Day use'}]},{key:'price',label:'Price (KES, tax included)',type:'money'},{key:'taxBasisPoints',label:'Tax basis points (1600 = 16%)',type:'number',value:'0'},{key:'durationMinutes',label:'Day-use duration in minutes',type:'number',optional:true}],payload:v=>({id,data:{name:v.name,roomTypeId:v.roomTypeId,mode:v.mode,priceMinor:minor(v.price),taxBasisPoints:Number(v.taxBasisPoints),currency:'KES',...(v.mode==='DAY_USE'?{durationMinutes:Number(v.durationMinutes)}:{})}})})};
 const reserve=(room:BusinessRecord)=>{const id=crypto.randomUUID();open({title:`Reserve room ${label(room)}`,operation:'roomReservation.create',collection:'roomReservations',id,fields:[select('customerId','Guest','customers'),select('ratePlanId','Rate plan','ratePlans'),{key:'guests',label:'Guests',type:'number',value:'1'},{key:'startsAt',label:'Arrival (this device’s local time)',type:'datetime-local'},{key:'endsAt',label:'Departure (this device’s local time)',type:'datetime-local'}],payload:v=>({id,roomId:room.id,customerId:v.customerId,ratePlanId:v.ratePlanId,guests:Number(v.guests),startsAt:new Date(v.startsAt).toISOString(),endsAt:new Date(v.endsAt).toISOString()})})};
 const editAsset=(asset?:BusinessRecord)=>{const id=asset?.id||crypto.randomUUID();const fields:Field[]=[{key:'name',label:'Asset name'},{key:'tag',label:'Unique asset tag'},select('assetCategoryId','Category','assetCategories'),{...select('roomId','Room','rooms'),optional:true},{...select('locationId','Stock location','stockLocations'),optional:true},{key:'serialNumber',label:'Serial number',optional:true},{key:'purchaseCostMinor',label:'Acquisition cost (KES)',type:'money'}];open({title:asset?'Edit asset':'Add asset',operation:'asset.save',collection:'assets',id,fields:fields.map(f=>({...f,value:f.key==='purchaseCostMinor'?String(Number(asset?.data.purchaseCostMinor||0)/100):String(asset?.data[f.key]??'')})),payload:v=>({id,data:{...v,purchaseCostMinor:minor(v.purchaseCostMinor)}})})};
 const payment=(booking:BusinessRecord,deposit:boolean)=>open({title:deposit?'Record deposit':'Settle folio',operation:deposit?'folio.deposit':'folio.pay',collection:'folios',id:booking.id,fields:[select('accountId','Payment account','paymentAccounts'),{key:'amount',label:'Amount received (KES)',type:'money'},{key:'cashTendered',label:'Cash tendered (cash only)',type:'money',optional:true},{key:'reference',label:'External reference (non-cash)',optional:true},{key:'confirmation',label:'External payment confirmation',type:'select',optional:true,options:[{value:'confirmed',label:'I have manually verified receipt of funds'}]}],payload:v=>({id:booking.id,accountId:v.accountId,amountMinor:minor(v.amount),...(v.cashTendered?{cashTenderedMinor:minor(v.cashTendered)}:{}),reference:v.reference,manuallyConfirmed:v.confirmation==='confirmed'})});
 const pending=queue.some(q=>q.state==='PENDING_SYNC');const disabled=busy||!ready||pending;
 return <div className="min-h-screen bg-slate-950 p-4 text-slate-100 sm:p-6"><header className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">ServOS business workspace</h1><p className="text-sm text-slate-400">{pending?'Commands awaiting synchronization':ready?'Authorized business records':'Connecting to business records'}</p></div><div className="flex gap-2"><button className={button} onClick={()=>void syncRef.current().catch(e=>setError(String(e)))}>Synchronize</button><button className={button} onClick={onSignOut}>Sign out</button></div></header>
  <nav className="mb-5 flex flex-wrap gap-2" aria-label="Business workspace">{(['Rooms','Assets','Settings','Activity'] as const).map(t=><button key={t} className={`${button} ${tab===t?'bg-amber-400 text-slate-950':''}`} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {error&&<p role="alert" className="mb-4 rounded-lg border border-rose-800 bg-rose-950 p-3">{error}</p>}{notice&&<p role="status" className="mb-4 rounded-lg border border-emerald-800 p-3">{notice}</p>}
  {!ready&&<p>Online sign-in, device registration and an authorized snapshot are required before opening this workspace.</p>}
  {ready&&tab==='Rooms'&&<section className="space-y-5"><div className="flex flex-wrap gap-2">{allowed(session,'rooms.manage')&&<><button disabled={disabled} className={button} onClick={()=>editRoom()}>Add room</button><button disabled={disabled} className={button} onClick={addRate}>Add rate</button></>}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{active('rooms').map(room=><article key={room.id} className="rounded-xl border border-slate-700 p-4"><h2 className="text-lg font-bold">Room {label(room)}</h2><p>{String(room.data.housekeepingState)} · {String(room.data.maintenanceState)}</p><p>Capacity {String(room.data.capacity)} · {String(room.data.turnaroundMinutes)} minutes turnaround</p><div className="mt-3 flex flex-wrap gap-2">{allowed(session,'rooms.manage')&&<button className={button} disabled={disabled} onClick={()=>editRoom(room)}>Edit</button>}{allowed(session,'rooms.operate')&&<button className={button} disabled={disabled} onClick={()=>reserve(room)}>Reserve / walk-in</button>}{allowed(session,'rooms.manage')&&<button className={button} disabled={disabled} onClick={()=>action('Update housekeeping','room.housekeeping','rooms',room.id,[{key:'state',label:'Next housekeeping state',type:'select',options:['DIRTY','CLEANING','INSPECTION','CLEAN'].map(value=>({value,label:value}))}])}>Housekeeping</button>}</div></article>)}</div>{active('rooms').length===0&&<p>No rooms yet. Add a room type in Settings, then a room and rate.</p>}
   <h2 className="text-xl font-bold">Reservations and stays</h2>{active('roomReservations').map(booking=>{const folio=find('folios',booking.id);return <article key={booking.id} className="rounded-xl border border-slate-700 p-4"><h3 className="font-bold">{label(find('customers',String(booking.data.customerId))||booking)} · Room {String(find('rooms',String(booking.data.roomId))?.data.number||booking.data.roomId)}</h3><p>{String(booking.data.status)} · {new Date(String(booking.data.startsAt)).toLocaleString()} – {new Date(String(booking.data.endsAt)).toLocaleString()}</p>{folio&&<p>Balance {money(folio.data.balanceMinor)} · Unapplied deposit {money(folio.data.depositMinor)}</p>}<div className="mt-3 flex flex-wrap gap-2">
    {booking.data.status==='RESERVED'&&allowed(session,'rooms.operate')&&<><button disabled={disabled} className={button} onClick={()=>action('Check in','stay.checkIn','stays',booking.id)}>Check in</button><button disabled={disabled} className={button} onClick={()=>action('Cancel reservation','roomReservation.cancel','roomReservations',booking.id,[{key:'reason',label:'Cancellation reason'}])}>Cancel</button></>}
    {!folio&&allowed(session,'folio.manage')&&booking.data.status==='RESERVED'&&<button disabled={disabled} className={button} onClick={()=>action('Open folio for deposits','folio.open','folios',booking.id)}>Open folio</button>}
    {folio?.data.status==='OPEN'&&allowed(session,'folio.manage')&&<><button disabled={disabled} className={button} onClick={()=>payment(booking,true)}>Deposit</button><button disabled={disabled} className={button} onClick={()=>payment(booking,false)}>Payment</button><button disabled={disabled} className={button} onClick={()=>open({title:'Apply deposit',operation:'folio.applyDeposit',collection:'folios',id:booking.id,fields:[{key:'amount',label:'Amount to apply (KES)',type:'money'}],payload:v=>({id:booking.id,amountMinor:minor(v.amount)})})}>Apply deposit</button>{booking.data.status==='CHECKED_IN'&&<button disabled={disabled} className={button} onClick={()=>action('Post all booked accommodation for settlement','folio.postAccommodation','folios',booking.id,[],{settleBookedStay:true})}>Post accommodation</button>}</>}
    {booking.data.status==='CHECKED_IN'&&allowed(session,'rooms.operate')&&<><button disabled={disabled} className={button} onClick={()=>action('Move guest','stay.move','stays',booking.id,[select('roomId','Destination room','rooms'),{key:'reason',label:'Move reason'}])}>Move room</button><button disabled={disabled} className={button} onClick={()=>action('Check out after settlement','stay.checkOut','stays',booking.id)}>Check out</button></>}
   </div></article>})}
  </section>}
  {ready&&tab==='Assets'&&<section className="space-y-4">{allowed(session,'assets.manage')&&<button disabled={disabled} className={button} onClick={()=>editAsset()}>Add asset</button>}{active('assets').map(asset=><article key={asset.id} className="rounded-xl border border-slate-700 p-4"><h2 className="font-bold">{label(asset)} · {String(asset.data.tag)}</h2><p>{String(asset.data.status)} · {String(asset.data.condition)} · Custodian: {String(find('employees',String(asset.data.custodianId))?.data.name||'Unassigned')}</p><div className="mt-3 flex flex-wrap gap-2">{allowed(session,'assets.manage')&&<button disabled={disabled} className={button} onClick={()=>editAsset(asset)}>Edit</button>}{allowed(session,'assets.operate')&&<><button disabled={disabled} className={button} onClick={()=>action('Assign asset','asset.assign','assets',asset.id,[select('custodianId','Custodian','employees'),{key:'reason',label:'Assignment reason'}])}>Assign</button><button disabled={disabled} className={button} onClick={()=>action('Return asset','asset.return','assets',asset.id,[{key:'reason',label:'Return reason'}])}>Return</button><button disabled={disabled} className={button} onClick={()=>action('Transfer asset','asset.transfer','assets',asset.id,[{...select('roomId','Destination room','rooms'),optional:true},{...select('locationId','Destination location','stockLocations'),optional:true},{key:'reason',label:'Transfer reason'}])}>Transfer</button><button disabled={disabled} className={button} onClick={()=>action('Inspect asset','asset.inspect','assets',asset.id,[{key:'condition',label:'Condition',type:'select',options:['GOOD','FAIR','POOR','BROKEN'].map(value=>({value,label:value}))},{key:'reason',label:'Inspection notes'}])}>Inspect</button></>}</div></article>)}{active('assets').length===0&&<p>No assets yet. Add a category in Settings and assign each asset to a room or stock location.</p>}</section>}
  {ready&&tab==='Settings'&&<section className="space-y-4"><h2 className="text-xl font-bold">Business master records</h2><div className="flex flex-wrap gap-2">{allowed(session,'customers.manage')&&<button disabled={disabled} className={button} onClick={()=>master('customers','Add guest',[{key:'name',label:'Guest name'},{key:'phone',label:'Phone',optional:true},{key:'email',label:'Email',optional:true}])}>Add guest</button>}{allowed(session,'roomTypes.manage')&&<button disabled={disabled} className={button} onClick={()=>master('roomTypes','Add room type',[{key:'name',label:'Room type'},{key:'maxGuests',label:'Maximum guests',type:'number'}])}>Add room type</button>}{allowed(session,'assetCategories.manage')&&<button disabled={disabled} className={button} onClick={()=>master('assetCategories','Add asset category',[{key:'name',label:'Category name'}])}>Add asset category</button>}</div>{['customers','roomTypes','ratePlans','assetCategories','paymentAccounts','hotelServices'].map(collection=><div key={collection}><h3 className="font-semibold">{collection}</h3><ul className="space-y-1">{active(collection).map(r=><li key={r.id}>{label(r)}{r.data.priceMinor!==undefined?` · ${money(r.data.priceMinor)}`:''}</li>)}</ul></div>)}</section>}
  {ready&&tab==='Activity'&&<section className="space-y-3"><h2 className="text-xl font-bold">Command history</h2><p>Disconnected actions are drafts. No offline financial finalization is enabled yet.</p>{queue.slice().reverse().map(q=><article key={q.id} className="rounded-lg border border-slate-700 p-3"><strong>{q.command.operation}</strong> · {q.state}<p className="break-all text-xs text-slate-400">{q.id}</p>{q.result?.error&&<p>{q.result.error.message}</p>}</article>)}<h3 className="font-semibold">Drafts retained on this browser</h3>{drafts.map(d=><p key={d.id}>{d.operation} · {new Date(d.updatedAt).toLocaleString()}</p>)}</section>}
  {editor&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-4"><form role="dialog" aria-modal="true" aria-label={editor.title} className="mx-auto my-5 max-w-xl space-y-4 rounded-xl border border-slate-600 bg-slate-900 p-5" onSubmit={e=>{e.preventDefault();try{void submit(editor.operation,editor.collection,editor.id,editor.payload(values))}catch(error){setError(String(error))}}}><h2 className="text-xl font-bold">{editor.title}</h2>{editor.fields.length===0&&<p>Confirm this operation. The server will validate the current state before committing it.</p>}{editor.fields.map(f=><label key={f.key} className="block">{f.label}{f.type==='select'?<select required={!f.optional} className={input} value={values[f.key]||''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}><option value="">Select…</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input required={!f.optional} className={input} type={f.type==='money'?'number':f.type||'text'} min={f.type==='number'||f.type==='money'?0:undefined} step={f.type==='money'?'0.01':f.type==='number'?'1':undefined} value={values[f.key]||''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/>}</label>)}<div className="flex gap-2"><button disabled={busy} className={`${button} bg-amber-400 text-slate-950`}>Confirm</button><button type="button" className={button} onClick={()=>setEditor(null)}>Cancel</button></div></form></div>}
 </div>;
}
