import React,{useMemo,useState} from 'react';
import {AlertTriangle,ArrowRightLeft,Boxes,PackageCheck,Search} from 'lucide-react';
import {useBarcodeScanner,barcodeEquals} from '../../hooks/useBarcodeScanner';
import {allowed,type BusinessRecord,type WebSession} from './session';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<void>;
const field='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-amber-400';
const button='rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold hover:bg-slate-800 disabled:opacity-40';
const primary='rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold text-slate-950 hover:bg-amber-300 disabled:opacity-40';
const money=(minor:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(minor||0)/100);
const data=(record?:BusinessRecord)=>record?.data as Record<string,any>|undefined;
const active=(records:BusinessRecord[],collection:string)=>records.filter(r=>r.collection===collection&&!r.archived);
const archived=(records:BusinessRecord[],collection:string)=>records.filter(r=>r.collection===collection&&r.archived);
const total=(stock:BusinessRecord)=>Object.values(data(stock)?.currentStock||{}).reduce((sum:number,value)=>sum+Number(value||0),0);
const status=(stock:BusinessRecord)=>{const q=total(stock),r=Number(data(stock)?.reorderLevel||0);return q<=0?'OUT':r>0&&q<=r?'LOW':'HEALTHY'};
const tone=(s:string)=>s==='OUT'?'border-rose-500/30 bg-rose-500/10 text-rose-200':s==='LOW'?'border-amber-500/30 bg-amber-500/10 text-amber-200':'border-emerald-500/30 bg-emerald-500/10 text-emerald-200';

export function WebCatalogView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn}){
 const products=active(records,'products');const stocks=active(records,'stockItems');const locations=active(records,'stockLocations');
 const [kind,setKind]=useState<'PRODUCT'|'STOCK'|'LOCATION'|null>(null);const [editing,setEditing]=useState<BusinessRecord|null>(null);
 const [form,setForm]=useState<Record<string,any>>({});
 const canCatalog=allowed(session,'catalog.manage');const canInventory=allowed(session,'inventory.adjust');
 const open=(next:'PRODUCT'|'STOCK'|'LOCATION',record?:BusinessRecord)=>{
  setKind(next);setEditing(record||null);const d=data(record)||{};
  if(next==='PRODUCT')setForm({name:d.name||'',code:d.code||'',price:Number(d.priceMinor||0)/100,category:d.category||'GENERAL',routeTo:d.routeTo||'BAR',stockItemId:d.stockItemId||'',barcode:d.barcode||'',favorite:!!d.favorite});
  if(next==='STOCK')setForm({name:d.name||'',code:d.code||'',baseUnit:d.baseUnit||'unit',barcode:d.barcode||'',scanUnitQuantity:Number(d.scanUnitQuantity||1),reorderLevel:Number(d.reorderLevel||0),averageUnitCost:Number(d.averageUnitCostMinor||0)/100});
  if(next==='LOCATION')setForm({name:d.name||'',code:d.code||'',type:d.type||'STORE'});
 };
 const save=async()=>{
  const id=editing?.id||crypto.randomUUID();
  if(kind==='PRODUCT')await command('product.save','products',id,{id,data:{name:String(form.name||'').trim(),code:String(form.code||'').trim(),priceMinor:Math.round(Number(form.price||0)*100),category:String(form.category||'GENERAL').trim(),routeTo:String(form.routeTo||'BAR'),stockItemId:String(form.stockItemId||'').trim()||undefined,barcode:String(form.barcode||'').trim()||undefined,favorite:!!form.favorite,taxClassId:'A_STANDARD'}});
  if(kind==='STOCK')await command('stockItem.save','stockItems',id,{id,data:{name:String(form.name||'').trim(),code:String(form.code||'').trim(),baseUnit:String(form.baseUnit||'unit').trim(),barcode:String(form.barcode||'').trim()||undefined,scanUnitQuantity:Number(form.scanUnitQuantity||1),reorderLevel:Number(form.reorderLevel||0),averageUnitCostMinor:Math.round(Number(form.averageUnitCost||0)*100)}});
  if(kind==='LOCATION')await command('stockLocation.save','stockLocations',id,{id,data:{name:String(form.name||'').trim(),code:String(form.code||'').trim(),type:String(form.type||'STORE')}});
  setKind(null);setEditing(null);
 };
 const masterAction=async(record:BusinessRecord,op:string)=>{await command(op,record.collection,record.id,{id:record.id})};
 return <section className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Catalog & stock masters</h2><p className="mt-1 text-sm text-slate-400">Transactional web masters. Quantities are never edited here; Inventory commands own stock balances.</p></div><div className="flex flex-wrap gap-2">{canCatalog&&<><button disabled={disabled} className={primary} onClick={()=>open('PRODUCT')}>New product</button><button disabled={disabled} className={button} onClick={()=>open('STOCK')}>New stock item</button></>}{canInventory&&<button disabled={disabled} className={button} onClick={()=>open('LOCATION')}>New stock location</button>}</div></div>
  <div className="grid gap-4 xl:grid-cols-2">
   <Panel title={`Products · ${products.length}`}>{products.map(r=>{const d=data(r)!;return <article key={r.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-start justify-between gap-3"><div><b>{String(d.name)}</b><div className="font-mono text-[11px] text-slate-500">{String(d.code)}</div></div><span className="font-semibold text-amber-300">{money(d.priceMinor)}</span></div><div className="mt-1 text-xs text-slate-500">{String(d.category||'GENERAL')} · {String(d.routeTo||'BAR')}{d.stockItemId?' · stock linked':''}</div>{canCatalog&&<div className="mt-3 flex gap-2"><button disabled={disabled} className={button} onClick={()=>open('PRODUCT',r)}>Edit</button><button disabled={disabled} className={button} onClick={()=>void masterAction(r,'product.archive')}>Archive</button></div>}</article>})}</Panel>
   <Panel title={`Stock masters · ${stocks.length}`}>{stocks.map(r=>{const d=data(r)!;return <article key={r.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-start justify-between gap-3"><div><b>{String(d.name)}</b><div className="font-mono text-[11px] text-slate-500">{String(d.code)}</div></div><span>{total(r).toLocaleString()} {String(d.baseUnit||'units')}</span></div><div className="mt-1 text-xs text-slate-500">Reorder at {Number(d.reorderLevel||0).toLocaleString()} · Avg cost {money(d.averageUnitCostMinor)}</div>{canCatalog&&<div className="mt-3 flex gap-2"><button disabled={disabled} className={button} onClick={()=>open('STOCK',r)}>Edit</button><button disabled={disabled} className={button} onClick={()=>void masterAction(r,'stockItem.archive')}>Archive</button></div>}</article>})}</Panel>
  </div>
  <Panel title={`Stock locations · ${locations.length}`}><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{locations.map(r=>{const d=data(r)!;return <article key={r.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><b>{String(d.name)}</b><div className="text-xs text-slate-500">{String(d.code||r.id)} · {String(d.type||'STORE')}</div>{canInventory&&<div className="mt-3 flex gap-2"><button disabled={disabled} className={button} onClick={()=>open('LOCATION',r)}>Edit</button><button disabled={disabled} className={button} onClick={()=>void masterAction(r,'stockLocation.archive')}>Archive</button></div>}</article>})}</div></Panel>
  {(archived(records,'products').length+archived(records,'stockItems').length+archived(records,'stockLocations').length)>0&&<details className="rounded-xl border border-slate-800 bg-slate-900 p-3"><summary className="cursor-pointer font-semibold">Archived masters</summary><div className="mt-3 space-y-2">{archived(records,'products').map(r=><Restore key={r.id} record={r} label={String(data(r)?.name||r.id)} disabled={disabled} onRestore={()=>masterAction(r,'product.reactivate')}/>)}{archived(records,'stockItems').map(r=><Restore key={r.id} record={r} label={String(data(r)?.name||r.id)} disabled={disabled} onRestore={()=>masterAction(r,'stockItem.reactivate')}/>)}{archived(records,'stockLocations').map(r=><Restore key={r.id} record={r} label={String(data(r)?.name||r.id)} disabled={disabled} onRestore={()=>masterAction(r,'stockLocation.reactivate')}/>)}</div></details>}
  {kind&&<Modal title={editing?`Edit ${kind.toLowerCase()}`:`New ${kind.toLowerCase()}`} onClose={()=>setKind(null)}><div className="space-y-3">
   <label className="block text-sm">Name<input className={field} value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label>
   <label className="block text-sm">Code / SKU<input className={field} value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})}/></label>
   {kind==='PRODUCT'&&<><label className="block text-sm">Price (KES)<input type="number" min="0" step="0.01" className={field} value={form.price??0} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label className="block text-sm">Category<input className={field} value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="block text-sm">Route<select className={field} value={form.routeTo||'BAR'} onChange={e=>setForm({...form,routeTo:e.target.value})}><option>BAR</option><option>KITCHEN</option><option>SERVICE</option></select></label><label className="block text-sm">Linked stock item<select className={field} value={form.stockItemId||''} onChange={e=>setForm({...form,stockItemId:e.target.value})}><option value="">Untracked / later recipe</option>{stocks.map(s=><option key={s.id} value={s.id}>{String(data(s)?.name)}</option>)}</select></label><label className="block text-sm">Barcode<input className={field} value={form.barcode||''} onChange={e=>setForm({...form,barcode:e.target.value})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.favorite} onChange={e=>setForm({...form,favorite:e.target.checked})}/>Favorite</label></>}
   {kind==='STOCK'&&<><label className="block text-sm">Base unit<input className={field} value={form.baseUnit||''} onChange={e=>setForm({...form,baseUnit:e.target.value})}/></label><label className="block text-sm">Barcode<input className={field} value={form.barcode||''} onChange={e=>setForm({...form,barcode:e.target.value})}/></label><label className="block text-sm">Quantity represented by one scan<input type="number" min="0.000001" step="0.001" className={field} value={form.scanUnitQuantity??1} onChange={e=>setForm({...form,scanUnitQuantity:Number(e.target.value)})}/></label><label className="block text-sm">Reorder level<input type="number" min="0" step="0.001" className={field} value={form.reorderLevel??0} onChange={e=>setForm({...form,reorderLevel:Number(e.target.value)})}/></label><label className="block text-sm">Average unit cost (KES)<input type="number" min="0" step="0.01" className={field} value={form.averageUnitCost??0} onChange={e=>setForm({...form,averageUnitCost:Number(e.target.value)})}/><span className="text-xs text-slate-500">Once stock exists, average cost changes must come through Procurement.</span></label></>}
   {kind==='LOCATION'&&<label className="block text-sm">Type<select className={field} value={form.type||'STORE'} onChange={e=>setForm({...form,type:e.target.value})}><option>STORE</option><option>FRIDGE</option><option>BAR</option><option>KITCHEN</option><option>OTHER</option></select></label>}
   <div className="flex gap-2"><button disabled={disabled||!String(form.name||'').trim()||!String(form.code||'').trim()} className={primary} onClick={()=>void save()}>Save</button><button className={button} onClick={()=>setKind(null)}>Cancel</button></div>
  </div></Modal>}
 </section>;
}

export function WebInventoryView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn}){
 const stocks=active(records,'stockItems');const locations=active(records,'stockLocations');const movements=active(records,'stockMovements').slice().sort((a,b)=>String(data(b)?.occurredAt||'').localeCompare(String(data(a)?.occurredAt||'')));
 const [search,setSearch]=useState('');const [state,setState]=useState('ALL');const [location,setLocation]=useState('ALL');const [selectedId,setSelectedId]=useState(stocks[0]?.id||'');
 const [modal,setModal]=useState<'COUNT'|'TRANSFER'|'WASTE'|null>(null);const [form,setForm]=useState({stockItemId:stocks[0]?.id||'',locationId:locations[0]?.id||'',toLocationId:locations[1]?.id||'',countedQty:0,quantity:1,reason:'',scan:''});
 const selected=stocks.find(s=>s.id===selectedId)||stocks[0];
 const rows=useMemo(()=>stocks.map(stock=>({stock,total:total(stock),status:status(stock)})).filter(row=>{const d=data(row.stock)!;const q=search.trim().toLowerCase();return (!q||[d.name,d.code,d.barcode].some(v=>String(v||'').toLowerCase().includes(q)))&&(state==='ALL'||row.status===state)}),[stocks,search,state]);
 const stockValue=stocks.reduce((sum,s)=>sum+total(s)*Number(data(s)?.averageUnitCostMinor||0),0);
 const canCount=allowed(session,'inventory.count')||allowed(session,'inventory.adjust');const canTransfer=allowed(session,'inventory.transfer');const canWaste=allowed(session,'inventory.waste');
 const open=(kind:'COUNT'|'TRANSFER'|'WASTE',stock?:BusinessRecord,loc?:string)=>{const s=stock||selected||stocks[0];const locationId=loc||locations[0]?.id||'';setForm({stockItemId:s?.id||'',locationId,toLocationId:locations.find(x=>x.id!==locationId)?.id||'',countedQty:0,quantity:1,reason:'',scan:''});setSelectedId(s?.id||'');setModal(kind)};
 const scan=(raw:string)=>{if(modal!=='COUNT')return;const code=raw.trim();const matches=stocks.filter(s=>barcodeEquals(String(data(s)?.barcode||''),code)||barcodeEquals(String(data(s)?.code||''),code));if(matches.length!==1)return;const s=matches[0];const increment=Number(data(s)?.scanUnitQuantity||1);setSelectedId(s.id);setForm(prev=>({...prev,stockItemId:s.id,countedQty:(prev.stockItemId===s.id?prev.countedQty:0)+increment,scan:''}))};
 useBarcodeScanner({enabled:modal==='COUNT',onScan:scan});
 const commit=async()=>{const id=form.stockItemId;if(modal==='COUNT')await command('inventory.count','stockItems',id,{id,stockItemId:id,locationId:form.locationId,countedQty:Number(form.countedQty),reason:form.reason||'Physical stock count'});if(modal==='TRANSFER')await command('inventory.transfer','stockItems',id,{id,stockItemId:id,locationId:form.locationId,toLocationId:form.toLocationId,quantity:Number(form.quantity),reason:form.reason||'Internal transfer'});if(modal==='WASTE')await command('inventory.waste','stockItems',id,{id,stockItemId:id,locationId:form.locationId,quantity:Number(form.quantity),reason:form.reason||'Declared waste'});setModal(null)};
 const selectedData=data(selected);
 const recent=selected?movements.filter(m=>data(m)?.stockItemId===selected.id).slice(0,12):[];
 return <section className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Inventory</h2><p className="mt-1 text-sm text-slate-400">Shared v2 stock ledger with exact physical counts, transfers, waste and immutable movement history.</p></div><div className="flex flex-wrap gap-2">{canCount&&<button disabled={disabled} className={primary} onClick={()=>open('COUNT')}>Count stock</button>}{canTransfer&&<button disabled={disabled} className={button} onClick={()=>open('TRANSFER')}>Transfer</button>}{canWaste&&<button disabled={disabled} className={button} onClick={()=>open('WASTE')}>Waste</button>}</div></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Boxes className="h-4 w-4"/>} label="Stock masters" value={String(stocks.length)}/><Metric icon={<PackageCheck className="h-4 w-4"/>} label="Stock value" value={money(stockValue)}/><Metric icon={<AlertTriangle className="h-4 w-4"/>} label="Low stock" value={String(stocks.filter(s=>status(s)==='LOW').length)}/><Metric icon={<AlertTriangle className="h-4 w-4"/>} label="Out of stock" value={String(stocks.filter(s=>status(s)==='OUT').length)}/></div>
  <div className="grid gap-2 md:grid-cols-[1fr_180px_220px]"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500"/><input className={field+' pl-9'} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search stock name, SKU or barcode"/></label><select className={field} value={state} onChange={e=>setState(e.target.value)}><option value="ALL">All stock states</option><option>HEALTHY</option><option>LOW</option><option>OUT</option></select><select className={field} value={location} onChange={e=>setLocation(e.target.value)}><option value="ALL">All locations / total</option>{locations.map(l=><option key={l.id} value={l.id}>{String(data(l)?.name)}</option>)}</select></div>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-slate-500"><tr><th className="p-3">Stock item</th><th className="p-3">State</th><th className="p-3 text-right">On hand</th><th className="p-3 text-right">Reorder</th><th className="p-3 text-right">Value</th></tr></thead><tbody>{rows.map(({stock,total:qty,status:st})=>{const d=data(stock)!;const shown=location==='ALL'?qty:Number(d.currentStock?.[location]||0);return <tr key={stock.id} onClick={()=>setSelectedId(stock.id)} className="cursor-pointer border-t border-slate-800 hover:bg-slate-900"><td className="p-3"><b>{String(d.name)}</b><div className="font-mono text-[11px] text-slate-500">{String(d.code)}</div></td><td className="p-3"><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${tone(st)}`}>{st}</span></td><td className="p-3 text-right font-mono">{shown.toLocaleString()} {String(d.baseUnit||'')}</td><td className="p-3 text-right">{Number(d.reorderLevel||0).toLocaleString()}</td><td className="p-3 text-right">{money(qty*Number(d.averageUnitCostMinor||0))}</td></tr>})}</tbody></table></div>
   <aside className="rounded-xl border border-slate-800 bg-slate-900 p-4">{selected&&selectedData?<><div className="flex items-start justify-between"><div><div className="text-xs uppercase text-slate-500">Selected stock</div><h3 className="text-lg font-bold">{String(selectedData.name)}</h3></div><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${tone(status(selected))}`}>{status(selected)}</span></div><div className="mt-4 space-y-2">{locations.map(l=><button key={l.id} disabled={!canCount||disabled} onClick={()=>open('COUNT',selected,l.id)} className="flex w-full items-center justify-between rounded-lg border border-slate-800 bg-slate-950 p-3 text-left"><span>{String(data(l)?.name)}</span><span className="font-mono">{Number(selectedData.currentStock?.[l.id]||0).toLocaleString()} {String(selectedData.baseUnit||'')}</span></button>)}</div><div className="mt-5 text-xs font-bold uppercase text-slate-500">Recent movements</div><div className="mt-2 max-h-64 space-y-2 overflow-auto">{recent.map(m=>{const d=data(m)!;return <div key={m.id} className="rounded-lg bg-slate-950 p-3 text-xs"><div className="flex justify-between gap-2"><b>{String(d.movementType)}</b><span>{Number(d.quantityDelta)>0?'+':''}{Number(d.quantityDelta).toLocaleString()} {String(d.baseUnit||'')}</span></div><div className="mt-1 text-slate-500">{String(d.reason||'')}</div></div>})}</div></>:<p className="text-sm text-slate-500">No stock items.</p>}</aside>
  </div>
  {modal&&<Modal title={modal==='COUNT'?'Physical stock count':modal==='TRANSFER'?'Transfer stock':'Record waste'} onClose={()=>setModal(null)}><div className="space-y-3"><label className="block text-sm">Stock item<select className={field} value={form.stockItemId} onChange={e=>setForm({...form,stockItemId:e.target.value,countedQty:0})}>{stocks.map(s=><option key={s.id} value={s.id}>{String(data(s)?.name)}</option>)}</select></label><label className="block text-sm">Location<select className={field} value={form.locationId} onChange={e=>setForm({...form,locationId:e.target.value,toLocationId:locations.find(l=>l.id!==e.target.value)?.id||''})}>{locations.map(l=><option key={l.id} value={l.id}>{String(data(l)?.name)}</option>)}</select></label>{modal==='TRANSFER'&&<label className="block text-sm">Destination<select className={field} value={form.toLocationId} onChange={e=>setForm({...form,toLocationId:e.target.value})}>{locations.filter(l=>l.id!==form.locationId).map(l=><option key={l.id} value={l.id}>{String(data(l)?.name)}</option>)}</select></label>}{modal==='COUNT'?<><div className="grid grid-cols-2 gap-2"><Fact label="Expected" value={`${Number(data(stocks.find(s=>s.id===form.stockItemId))?.currentStock?.[form.locationId]||0).toLocaleString()}`}/><Fact label="Draft variance" value={`${(Number(form.countedQty)-Number(data(stocks.find(s=>s.id===form.stockItemId))?.currentStock?.[form.locationId]||0)).toLocaleString()}`}/></div><label className="block text-sm">Physical quantity<input type="number" min="0" step="0.001" className={field} value={form.countedQty} onChange={e=>setForm({...form,countedQty:Number(e.target.value)})}/></label><label className="block text-sm">Scan barcode / SKU<input data-barcode-capture="true" className={field} value={form.scan} onChange={e=>setForm({...form,scan:e.target.value})}/></label><button className={button} disabled={!form.scan.trim()} onClick={()=>scan(form.scan)}>Apply typed barcode</button></>:<label className="block text-sm">Quantity<input type="number" min="0.001" step="0.001" className={field} value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label>}<label className="block text-sm">Reason<input className={field} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button disabled={disabled||!form.stockItemId||!form.locationId||(modal==='TRANSFER'&&!form.toLocationId)} className={primary} onClick={()=>void commit()}>Commit {modal.toLowerCase()}</button></div></Modal>}
 </section>;
}

const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-xl border border-slate-800 bg-slate-900/40 p-4"><h3 className="mb-3 font-bold">{title}</h3><div className="space-y-2">{children}</div></section>;
const Metric=({icon,label,value}:{icon:React.ReactNode;label:string;value:string})=><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex items-center gap-2 text-xs uppercase text-slate-500">{icon}{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>;
const Fact=({label,value}:{label:string;value:string})=><div className="rounded-lg bg-slate-950 p-3"><div className="text-[10px] uppercase text-slate-600">{label}</div><div className="font-semibold">{value}</div></div>;
const Restore=({label,disabled,onRestore}:{record:BusinessRecord;label:string;disabled:boolean;onRestore:()=>Promise<void>})=><div className="flex items-center justify-between rounded-lg bg-slate-950 p-2 text-sm"><span>{label}</span><button disabled={disabled} className={button} onClick={()=>void onRestore()}>Reactivate</button></div>;
const Modal=({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-50 overflow-y-auto bg-black/70 p-4"><section role="dialog" aria-modal="true" aria-label={title} className="mx-auto my-8 max-w-xl rounded-xl border border-slate-700 bg-slate-900 p-5"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-bold">{title}</h3><button className={button} onClick={onClose}>Close</button></div>{children}</section></div>;
