import React,{useState} from 'react';
import type {BusinessRecord,WebSession} from './session';
import {allowed} from './session';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<void>;
const field='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white';
const button='rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold disabled:opacity-40';
const primary='rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold text-slate-950 disabled:opacity-40';
const data=(record?:BusinessRecord)=>record?.data as Record<string,any>|undefined;
const active=(records:BusinessRecord[],collection:string)=>records.filter(r=>r.collection===collection&&!r.archived);
const money=(minor:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(minor||0)/100);
const minor=(value:string)=>{const amount=Number(value);if(!Number.isFinite(amount)||amount<0)throw new Error('Enter a valid nonnegative amount.');return Math.round(amount*100)};

export function WebFinanceView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn}){
 const tills=active(records,'tillSessions').slice().sort((a,b)=>String(data(b)?.openedAt||'').localeCompare(String(data(a)?.openedAt||'')));
 const reports=active(records,'closeDayReports').slice().sort((a,b)=>String(data(b)?.generatedAt||'').localeCompare(String(data(a)?.generatedAt||'')));
 const openTill=tills.find(till=>data(till)?.status==='OPEN');
 const [direction,setDirection]=useState<'PAID_IN'|'PAID_OUT'>('PAID_IN');
 const [movementAmount,setMovementAmount]=useState('');const [movementReason,setMovementReason]=useState('');
 const [countedCash,setCountedCash]=useState('');const [varianceReason,setVarianceReason]=useState('');const [notice,setNotice]=useState('');
 const run=async(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>{setNotice('');try{await command(operation,collection,id,payload)}catch(error){setNotice(String(error))}};
 const cashMovement=async()=>{if(!openTill)return;await run('till.cashMovement','cashMovements',crypto.randomUUID(),{tillSessionId:openTill.id,direction,amountMinor:minor(movementAmount),reason:movementReason.trim()});setMovementAmount('');setMovementReason('')};
 const closeTill=async()=>{if(!openTill)return;const amount=countedCash||((Number(data(openTill)?.expectedCashMinor||0)/100).toFixed(2));await run('till.close','tillSessions',openTill.id,{id:openTill.id,countedCashMinor:minor(amount),varianceReason:varianceReason.trim()})};
 const generate=async(till:BusinessRecord)=>run('closeDay.generate','closeDayReports',`close-day-${till.id}`,{tillId:till.id});
 return <section className="space-y-5">
  <header><h2 className="text-xl font-bold">Finance and close day</h2><p className="mt-1 text-sm text-slate-400">Cash movements and close reports are committed through versioned commands. External payments remain manually confirmed.</p></header>
  {notice&&<p role="alert" className="rounded-lg border border-rose-800 bg-rose-950 p-3 text-sm">{notice}</p>}
  {openTill?<article className="space-y-4 rounded-xl border border-slate-700 bg-slate-900/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Open till session</h3><p className="text-xs text-slate-500">Opened {new Date(String(data(openTill)?.openedAt)).toLocaleString()} · expected cash {money(data(openTill)?.expectedCashMinor)}</p></div><span className="rounded-full border border-amber-700 px-2 py-1 text-xs">OPEN</span></div>
   {allowed(session,'till.cashMovement')&&<div className="grid gap-2 sm:grid-cols-2"><label className="text-sm">Movement<select className={field} value={direction} onChange={e=>setDirection(e.target.value as 'PAID_IN'|'PAID_OUT')}><option value="PAID_IN">Cash in</option><option value="PAID_OUT">Cash out</option></select></label><label className="text-sm">Amount (KES)<input className={field} type="number" min="0.01" step="0.01" value={movementAmount} onChange={e=>setMovementAmount(e.target.value)}/></label><label className="text-sm sm:col-span-2">Reason<input className={field} value={movementReason} onChange={e=>setMovementReason(e.target.value)}/></label><button disabled={disabled||!movementAmount||movementAmount==='0'||movementReason.trim().length<3} className={button} onClick={()=>void cashMovement()}>Record cash movement</button></div>}
   {allowed(session,'till.close')&&<div className="grid gap-2 border-t border-slate-800 pt-4 sm:grid-cols-2"><label className="text-sm">Counted cash (KES)<input className={field} type="number" min="0" step="0.01" value={countedCash||String((Number(data(openTill)?.expectedCashMinor||0)/100).toFixed(2))} onChange={e=>setCountedCash(e.target.value)}/></label><label className="text-sm">Variance reason<input className={field} value={varianceReason} onChange={e=>setVarianceReason(e.target.value)} placeholder="Required when count differs"/></label><button disabled={disabled} className={primary} onClick={()=>void closeTill()}>Close till</button><p className="self-center text-xs text-slate-500">Closing is rejected while any order remains open. Variance authorization is enforced by the server.</p></div>}
  </article>:<p className="rounded-lg border border-slate-800 p-4 text-sm text-slate-400">No open till. Open the next till from POS before accepting cash or starting a shift.</p>}
  <section className="space-y-3"><h3 className="font-bold">Close-day reports</h3>{tills.filter(till=>data(till)?.status==='CLOSED').map(till=>{const report=reports.find(row=>data(row)?.tillSessionId===till.id);return <article key={till.id} className="rounded-xl border border-slate-800 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>Till {till.id.slice(0,12)}</b><p className="text-xs text-slate-500">{new Date(String(data(till)?.closedAt)).toLocaleString()} · variance {money(data(till)?.cashVarianceMinor)}</p></div>{!report&&allowed(session,'reports.view')&&<button disabled={disabled} className={button} onClick={()=>void generate(till)}>Generate close-day snapshot</button>}</div>{report&&<dl className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><div>Gross {money(data(report)?.sales?.grossMinor)}</div><div>Net {money(data(report)?.sales?.netMinor)}</div><div>Refunds {money(data(report)?.sales?.refundsMinor)}</div><div>Cash {money(data(report)?.tenders?.cashMinor)}</div><div>M-Pesa {money(data(report)?.tenders?.mpesaMinor)}</div><div>Card {money(data(report)?.tenders?.cardMinor)}</div><div>Counted {money(data(report)?.cash?.countedMinor)}</div><div>Variance {money(data(report)?.cash?.varianceMinor)}</div><div>M-Pesa review {String(data(report)?.reconciliation?.mpesaStatus||'')}</div></dl>}</article>})}{!tills.some(till=>data(till)?.status==='CLOSED')&&<p className="text-sm text-slate-500">Closed till sessions and immutable snapshots will appear here.</p>}</section>
 </section>;
}
