import React,{useState} from 'react';
import {CheckCircle2,ClipboardCheck,Compass,LockKeyhole,RefreshCw,ShieldCheck} from 'lucide-react';
import type {Rpc,WebSession} from './session';

const field='w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-amber-400';
const button='inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold text-slate-200 hover:border-slate-600 hover:bg-slate-800 disabled:opacity-40';
const primary='inline-flex items-center justify-center gap-2 rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-amber-300 disabled:opacity-40';

export function WebLifecycleView({session,rpc,onUpdated}:{session:WebSession;rpc:Rpc;onUpdated:(next:WebSession)=>void}){
 const [profile,setProfile]=useState({tradingName:String(session.intakeProfile?.tradingName||''),legalName:String(session.intakeProfile?.legalName||''),phone:String(session.intakeProfile?.phone||''),email:String(session.intakeProfile?.email||'')});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const stage=session.lifecycleStage||'LIVE';
 const checks=session.readiness?.checks||[];
 const setup=async(step?:string)=>{setBusy(true);setError('');setNotice('');try{const next=await rpc('rpc/servos_v2_web_lifecycle',step?{action:'setup.complete',payload:{step}}:{action:'readiness.refresh',payload:{}});onUpdated(next);setNotice(step?'Setup check saved.':'Readiness checked.')}catch(cause){setError(String(cause))}finally{setBusy(false)}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const next=await rpc('rpc/servos_v2_web_lifecycle',{action:'intake.save',payload:{profile}});onUpdated(next);setNotice('Business details saved. Continue with setup when you are ready.')}catch(cause){setError(String(cause))}finally{setBusy(false)}};
 const goLive=async()=>{setBusy(true);setError('');try{const next=await rpc('rpc/servos_v2_web_lifecycle',{action:'go_live',payload:{}});onUpdated(next);setNotice('Go Live completed. Your operational workspace is ready.')}catch(cause){setError(String(cause))}finally{setBusy(false)}};
 const title=stage==='INTAKE'?'Commission your business':stage==='SETUP'?'Finish business setup':'Go Live readiness';
 return <section className="mx-auto max-w-4xl space-y-5 rounded-2xl border border-slate-800 bg-slate-900 p-5 text-white sm:p-7" data-guide-anchor="web.lifecycle">
  <div className="flex items-start gap-3"><Compass className="mt-1 h-6 w-6 text-amber-300"/><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">BUSINESS READINESS</p><h2 className="mt-1 text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-slate-400">ServOS keeps commissioning separate from staff training. Your business must be ready before operational commands are enabled.</p></div></div>
  {error&&<p role="alert" className="rounded-xl border border-rose-800 bg-rose-950/50 p-3 text-sm text-rose-200">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-emerald-800 bg-emerald-950/30 p-3 text-sm text-emerald-200">{notice}</p>}
  {stage==='INTAKE'&&<form className="grid gap-4 sm:grid-cols-2" onSubmit={save}><label className="text-sm sm:col-span-2">Trading name<input required className={`${field} mt-1`} value={profile.tradingName} onChange={e=>setProfile(v=>({...v,tradingName:e.target.value}))}/></label><label className="text-sm">Legal name<input className={`${field} mt-1`} value={profile.legalName} onChange={e=>setProfile(v=>({...v,legalName:e.target.value}))}/></label><label className="text-sm">Business phone<input className={`${field} mt-1`} value={profile.phone} onChange={e=>setProfile(v=>({...v,phone:e.target.value}))}/></label><label className="text-sm sm:col-span-2">Business email<input type="email" className={`${field} mt-1`} value={profile.email} onChange={e=>setProfile(v=>({...v,email:e.target.value}))}/></label><div className="sm:col-span-2"><button disabled={busy} className={primary}>{busy?'Saving…':'Save business details'}</button></div></form>}
  {stage!=='INTAKE'&&<><div className="grid gap-3 sm:grid-cols-2">{checks.map(check=><button key={check.id} disabled={busy||check.complete||!['business.configure','*'].some(p=>session.permissions.includes(p))} onClick={()=>void setup(check.id)} className={`flex items-center gap-3 rounded-xl border p-4 text-left ${check.complete?'border-emerald-700/50 bg-emerald-950/20':'border-slate-700 bg-slate-950 hover:border-amber-500/60'}`}><span className={`grid h-9 w-9 place-items-center rounded-full ${check.complete?'bg-emerald-500/20 text-emerald-300':'bg-slate-800 text-amber-300'}`}>{check.complete?<CheckCircle2 className="h-5 w-5"/>:<ClipboardCheck className="h-5 w-5"/>}</span><span><b>{check.label}</b><span className="mt-1 block text-xs text-slate-500">{check.complete?'Complete':'Mark complete after verifying this area.'}</span></span></button>)}</div><div className="flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>void setup()}><RefreshCw className="h-4 w-4"/>Refresh readiness</button>{stage==='READY_FOR_GO_LIVE'&&session.permissions.includes('business.configure')&&<button disabled={busy||!session.readiness?.ready} className={primary} onClick={()=>void goLive()}><ShieldCheck className="h-4 w-4"/>Go Live</button>}</div><p className="text-xs text-slate-500">Only an authorized business administrator can complete setup and Go Live. Native-only hardware acceptance remains terminal-specific.</p></>}
 </section>;
}

export function WebStaffWelcome({session,onDismiss,onStartTour}:{session:WebSession;onDismiss:()=>void;onStartTour:()=>void}){
 const [hidden,setHidden]=useState(()=>localStorage.getItem(`servos-welcome:${session.businessId}:${session.actorId}:v1`)==='dismissed');
 if(hidden)return null;
 const dismiss=()=>{localStorage.setItem(`servos-welcome:${session.businessId}:${session.actorId}:v1`,'dismissed');setHidden(true);onDismiss()};
 return <section className="mb-5 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-5" data-guide-anchor="web.welcome"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><LockKeyhole className="mt-1 h-5 w-5 text-amber-300"/><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">WELCOME TO SERVOS WEB</p><h2 className="mt-1 text-xl font-bold">Start with the work you need to finish.</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">Your access controls what appears here. Changes are checked by the business server and can be reviewed from Saved changes.</p></div></div><div className="flex gap-2"><button className={button} onClick={onStartTour}>Take the tour</button><button className={primary} onClick={dismiss}>Got it</button></div></div></section>;
}