import React,{useEffect,useState} from 'react';
import {allowed,type BusinessRecord,type Rpc,type WebSession} from './session';
type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<unknown>;
type Device={id:string;name:string;class:string;ownerId:string;active:boolean;lastSequence:number;lastSeenAt:string|null;protocolVersion:number;createdAt:string};
const input='w-full rounded-lg border border-slate-600 bg-slate-950 p-2 text-white';
const button='rounded-lg border border-slate-600 px-3 py-2 disabled:opacity-40';
const roles=['Admin','Manager','Cashier','Server','Chef','Housekeeper','Accountant','Custom'];
const permissions=['procurement.over_receive','order.discount','order.void','payment.reverse','till.override_variance','folio.reverse'];

export function WebStaffAdminView({records,session,disabled,command,rpc,currentDeviceId}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn;rpc:Rpc;currentDeviceId:string}){
 const [devices,setDevices]=useState<Device[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [authUserId,setAuthUserId]=useState('');const [staffId,setStaffId]=useState('');const [name,setName]=useState('');const [role,setRole]=useState('Server');
 const [initiatorId,setInitiatorId]=useState('');const [approvalPermission,setApprovalPermission]=useState(permissions[0]);const [approvalTarget,setApprovalTarget]=useState('');
 const staff=records.filter(r=>r.collection==='employees');
 const loadDevices=async()=>{if(!allowed(session,'devices.manage'))return;try{const list=await rpc('rpc/servos_v2_list_devices',{}) as Device[];setDevices(list)}catch(e){setError(String(e))}};
 useEffect(()=>{void loadDevices()},[session.actorId,session.policyVersion]);
 const run=async(op:string,id:string,payload:Record<string,unknown>)=>{setError('');setNotice('');const ok=await command(op,'employees',id,payload);if(ok===false){setError('The server did not confirm this command. Check Activity for the rejection.');return false}setNotice('Server confirmed the command.');await loadDevices();return true};
 const create=async()=>{if(!authUserId.trim()||!staffId.trim()||!name.trim())return;const ok=await run('staff.create',staffId.trim(),{authUserId:authUserId.trim(),staffId:staffId.trim(),name:name.trim(),role});if(ok){setAuthUserId('');setStaffId('');setName('')}};
 const approve=async()=>{if(!initiatorId.trim()||!approvalTarget.trim())return;const token=crypto.randomUUID();const ok=await run('managerApproval.issue',token,{initiatorId:initiatorId.trim(),permission:approvalPermission,target:approvalTarget.trim(),approvalToken:token});if(ok){setNotice(`Approval token (expires in 5 minutes): ${token}. Share it directly with the named operator; it is single-use and action/target bound.`);await navigator.clipboard?.writeText(token).catch(()=>undefined)}};
 const revoke=async(device:Device)=>{if(device.id===currentDeviceId){setError('This browser cannot revoke its own active device. Use a different trusted device.');return}const ok=await command('device.revoke','deviceEvents',device.id,{deviceId:device.id});if(ok===false){setError('Device revocation was not confirmed. Check Activity.');return}setNotice('Device revoked; its later commands are rejected by the server.');await loadDevices()};
 return <section className="space-y-6" aria-label="Staff and device administration">
  <header><h2 className="text-xl font-bold">Staff, approvals and devices</h2><p className="mt-1 text-sm text-slate-400">Server permissions are authoritative. Invitations and passwords are managed through Supabase Auth; this workspace only binds an existing Auth user to a staff profile.</p></header>
  {error&&<p role="alert" className="rounded-lg border border-rose-800 bg-rose-950 p-3 text-sm">{error}</p>}{notice&&<p role="status" className="break-all rounded-lg border border-emerald-800 p-3 text-sm">{notice}</p>}
  {allowed(session,'staff.create')&&<form className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void create()}}><h3 className="font-semibold sm:col-span-2">Bind invited Auth user</h3><label className="text-sm">Existing Auth user ID<input required className={input} value={authUserId} onChange={e=>setAuthUserId(e.target.value)}/></label><label className="text-sm">Staff ID<input required className={input} value={staffId} onChange={e=>setStaffId(e.target.value)}/></label><label className="text-sm">Name<input required className={input} value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm">Role<select className={input} value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><button disabled={disabled} className={`${button} sm:col-span-2`}>Create staff profile</button></form>}
  <div className="space-y-2"><h3 className="font-semibold">Staff profiles</h3>{staff.map(person=><article key={person.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 p-3"><div><b>{String(person.data.name||person.id)}</b><p className="text-xs text-slate-400">{String(person.data.role)} · {person.archived?'Inactive':'Active'} · {String(person.data.authUserId||'Auth user not linked')}</p><p className="text-xs text-slate-500">Outlets: {Array.isArray(person.data.outletIds)?person.data.outletIds.join(', '):'all'} · Areas: {Array.isArray(person.data.serviceAreas)?person.data.serviceAreas.join(', '):'all'}</p></div><div className="flex flex-wrap gap-2">{allowed(session,'staff.update')&&!person.archived&&<select aria-label={`Change ${String(person.data.name)} role`} className={input+' min-w-36'} value={String(person.data.role)} disabled={disabled} onChange={e=>void run('staff.update',person.id,{authUserId:person.data.authUserId,staffId:person.id,name:person.data.name,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select>}{allowed(session,'staff.deactivate')&&!person.archived&&<button disabled={disabled||String(person.data.authUserId)===session.actorId} className={button} onClick={()=>void run('staff.deactivate',person.id,{authUserId:person.data.authUserId,staffId:person.id})}>Deactivate</button>}</div></article>)}{!staff.length&&<p className="text-sm text-slate-500">No staff profiles are visible to this role.</p>}</div>
  {allowed(session,'staff.update')&&<form className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void approve()}}><h3 className="font-semibold sm:col-span-2">Issue manager approval</h3><label className="text-sm">Initiating operator Auth user ID<input required className={input} value={initiatorId} onChange={e=>setInitiatorId(e.target.value)}/></label><label className="text-sm">Action<select className={input} value={approvalPermission} onChange={e=>setApprovalPermission(e.target.value)}>{permissions.map(p=><option key={p}>{p}</option>)}</select></label><label className="text-sm sm:col-span-2">Exact target ID (for over-receipt, purchase order ID)<input required className={input} value={approvalTarget} onChange={e=>setApprovalTarget(e.target.value)}/></label><button disabled={disabled} className={`${button} sm:col-span-2`}>Issue five-minute one-time approval</button></form>}
  {allowed(session,'devices.manage')&&<div className="space-y-2"><div className="flex items-center justify-between"><h3 className="font-semibold">Trusted devices</h3><button className={button} onClick={()=>void loadDevices()}>Refresh</button></div>{devices.map(device=><article key={device.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 p-3"><div className="min-w-0"><b>{device.name}</b><p className="break-all font-mono text-xs text-slate-400">{device.id} · {device.class} · protocol {device.protocolVersion}</p><p className="text-xs text-slate-500">Owner {device.ownerId} · sequence {device.lastSequence} · last seen {device.lastSeenAt?new Date(device.lastSeenAt).toLocaleString():'not yet'}</p></div><div className="flex items-center gap-2"><span>{device.active?'Active':'Revoked'}</span>{device.active&&<button disabled={disabled||device.id===currentDeviceId} className={button} onClick={()=>void revoke(device)}>Revoke</button>}</div></article>)}</div>}
  {staff.some(p=>p.data.role==='Admin'&&p.data.active!==false)&&!staff.some(p=>p.data.role==='Admin'&&!p.archived)&&<p className="text-sm text-amber-300">An Admin profile is marked inactive; verify that another active Admin remains before continuing.</p>}
 </section>;
}
