import React,{useMemo,useState} from 'react';
import {ArrowRightLeft,Clock3,LogIn,Search,ShieldAlert} from 'lucide-react';
import {useRuntime} from '../runtime/RuntimeProvider';
import {ActionDialog} from './ActionDialog';
import {buttonClass,fieldClass,money,primaryButtonClass,recordOf,recordsOf,shortDate} from './records';

// SERVOS_PATCH_06_FRONT_DESK
const HOTEL_TZ='Africa/Nairobi';
const hotelDate=(value:Date|string|number)=>new Intl.DateTimeFormat('en-CA',{timeZone:HOTEL_TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const datePlus=(date:string,days:number)=>{const d=new Date(`${date}T12:00:00+03:00`);d.setUTCDate(d.getUTCDate()+days);return hotelDate(d)};
const overlapsDay=(start:string,end:string,date:string)=>new Date(start)<new Date(`${datePlus(date,1)}T00:00:00+03:00`)&&new Date(end)>new Date(`${date}T00:00:00+03:00`);
const active=(status:string)=>['RESERVED','CHECKED_IN'].includes(status);
const stateClass=(v:string)=>v==='CHECKED_IN'?'text-emerald-300':v==='RESERVED'?'text-sky-300':v==='DIRTY'||v==='OUT_OF_ORDER'?'text-rose-300':'text-slate-400';

export function NativeFrontDeskView(){
  const runtime=useRuntime();const s=runtime.snapshot!;const canOperate=s.actor.permissions.includes('rooms.operate');
  const rooms=recordsOf(s,'rooms'),types=recordsOf(s,'roomTypes'),reservations=recordsOf(s,'roomReservations'),customers=recordsOf(s,'customers'),blocks=recordsOf(s,'roomBlocks'),folios=recordsOf(s,'folios');
  const [start,setStart]=useState(hotelDate(new Date()));const [days,setDays]=useState(7);const [query,setQuery]=useState('');const [move,setMove]=useState<any>(null);const [message,setMessage]=useState('');
  const dates=useMemo(()=>Array.from({length:days},(_,i)=>datePlus(start,i)),[start,days]);
  const filtered=useMemo(()=>reservations.filter(r=>{const q=query.trim().toLowerCase();if(!q)return true;const guest=customers.find(c=>c.id===r.customerId)?.name||'';const room=rooms.find(x=>x.id===r.roomId)?.number||'';return `${guest} ${room} ${r.id}`.toLowerCase().includes(q)}),[reservations,customers,rooms,query]);
  const today=hotelDate(new Date());
  const arrivals=filtered.filter(r=>r.status==='RESERVED'&&hotelDate(r.startsAt)===today);
  const arrivalQueue=filtered.filter(r=>r.status==='RESERVED'&&(hotelDate(r.startsAt)===today||(new Date(r.startsAt)<new Date()&&new Date(r.endsAt)>new Date())));
  const departures=filtered.filter(r=>active(r.status)&&hotelDate(r.endsAt)===today);
  const occupied=rooms.filter(room=>reservations.some(r=>r.roomId===room.id&&r.status==='CHECKED_IN')).length;
  const due=arrivalQueue.filter(r=>new Date(r.startsAt)<=new Date());
  const roomName=(id:string)=>rooms.find(x=>x.id===id)?.number||id;const guestName=(id:string)=>customers.find(x=>x.id===id)?.name||id;
  const command=async(op:string,payload:any,version?:number)=>{setMessage('');try{await runtime.command(op,payload,version);setMove(null);setMessage('Front Desk action committed locally and queued for synchronization.')}catch(e){setMessage(String(e))}};
  const checkIn=async(r:any)=>{const rr=recordOf(s,'roomReservations',r.id),room=recordOf(s,'rooms',r.roomId),folio=recordOf(s,'folios',r.id);if(!rr||!room)return;await command('stay.checkIn',{id:r.id,roomVersion:room.version,...(folio?{folioVersion:folio.version}:{})},rr.version)};
  const moveStay=async(destinationRoomId:string,reason:string)=>{if(!move)return;const stay=recordOf(s,'stays',move.id),res=recordOf(s,'roomReservations',move.id),oldRoom=recordOf(s,'rooms',move.roomId),dest=recordOf(s,'rooms',destinationRoomId);if(!stay||!res||!oldRoom||!dest)return;const folio=recordOf(s,'folios',move.id);if(!folio)return;await command('stay.move',{id:move.id,destinationRoomId,reservationVersion:res.version,folioVersion:folio.version,currentRoomVersion:oldRoom.version,destinationRoomVersion:dest.version,reason},stay.version)};
  const checkOut=async(r:any)=>{const stay=recordOf(s,'stays',r.id),res=recordOf(s,'roomReservations',r.id),folio=recordOf(s,'folios',r.id),room=recordOf(s,'rooms',r.roomId);if(!stay||!res||!folio||!room)return;await command('stay.checkOut',{id:r.id,reservationVersion:res.version,folioVersion:folio.version,roomVersion:room.version},stay.version)};

  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Front Desk</h1><p className="mt-1 text-sm text-slate-400">Arrivals, departures, room occupancy and the seven-day tape chart. Hotel time zone: Africa/Nairobi.</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500"/><input className={fieldClass+' pl-9'} placeholder="Guest, room, reservation…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div></div>
    {message&&<p role="status" className="mt-4 rounded-xl bg-slate-900 p-3 text-sm text-slate-300">{message}</p>}
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Occupied now" value={`${occupied}/${rooms.length}`}/><Metric label="Today's arrivals" value={String(arrivals.length)}/><Metric label="Due to arrive" value={String(due.length)}/><Metric label="Today's departures" value={String(departures.length)}/></section>

    <section className="mt-6 grid gap-4 xl:grid-cols-2">
      <Queue title="Arrivals & overdue" icon={<LogIn className="h-4 w-4"/>} empty="No arrivals due today.">{arrivalQueue.map(r=>{const room=rooms.find(x=>x.id===r.roomId);const isDue=new Date(r.startsAt)<=new Date();const ready=room?.housekeepingState==='CLEAN'&&room?.maintenanceState!=='OUT_OF_ORDER';return <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-950 p-3"><div><b>{guestName(r.customerId)}</b><div className="text-xs text-slate-500">Room {roomName(r.roomId)} · {shortDate(r.startsAt)} · {r.guests} guest(s)</div></div>{canOperate&&<button disabled={!isDue||!ready} className={primaryButtonClass} onClick={()=>void checkIn(r)}>{!isDue?'Not due yet':!ready?'Room not ready':'Check in'}</button>}</div>})}</Queue>
      <Queue title="Departures today" icon={<Clock3 className="h-4 w-4"/>} empty="No departures scheduled today.">{departures.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-950 p-3"><div><b>{guestName(r.customerId)}</b><div className="text-xs text-slate-500">Room {roomName(r.roomId)} · due {shortDate(r.endsAt)}</div></div><div className="flex flex-wrap items-center justify-end gap-2">{folios.find(f=>f.id===r.id)&&<span className="text-[11px] text-slate-500">Balance {money(Number(folios.find(f=>f.id===r.id)?.balanceMinor||0)/100)} · Deposit {money(Number(folios.find(f=>f.id===r.id)?.depositMinor||0)/100)}</span>}{r.status==='CHECKED_IN'&&canOperate&&<button className={buttonClass} onClick={()=>setMove(r)}><ArrowRightLeft className="mr-1 inline h-4 w-4"/>Move</button>}{r.status==='CHECKED_IN'&&canOperate&&<button className={primaryButtonClass} onClick={()=>void checkOut(r)}>Check out</button>}</div></div>)}</Queue>
    </section>

    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Tape chart</h2><p className="text-xs text-slate-500">Reservations and active blocks use real committed intervals. Turnaround remains part of availability even after departure.</p></div><div className="flex gap-2"><label><span className="block text-[11px] text-slate-500">Start</span><input type="date" className={fieldClass} value={start} onChange={e=>setStart(e.target.value)}/></label><label><span className="block text-[11px] text-slate-500">Days</span><select className={fieldClass} value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7</option><option value={14}>14</option></select></label></div></div>
      <div className="mt-4 overflow-auto"><table className="min-w-max border-separate border-spacing-1 text-xs"><thead><tr><th className="sticky left-0 z-10 min-w-36 bg-slate-900 p-2 text-left">Room</th>{dates.map(d=><th key={d} className="min-w-28 p-2 text-center text-slate-500">{d.slice(5)}</th>)}</tr></thead><tbody>{rooms.map(room=><tr key={room.id}><th className="sticky left-0 z-10 bg-slate-900 p-2 text-left"><div className="font-bold">{room.number}</div><div className="text-[10px] text-slate-500">{types.find(t=>t.id===room.roomTypeId)?.name||room.roomTypeId}</div></th>{dates.map(d=>{const res=filtered.find(r=>r.roomId===room.id&&active(r.status)&&overlapsDay(r.startsAt,r.blockedUntil||r.endsAt,d));const block=blocks.find(b=>b.roomId===room.id&&b.status==='ACTIVE'&&overlapsDay(b.startsAt,b.endsAt,d));return <td key={d} className="h-14 rounded-lg border border-slate-800 p-1 align-top">{res?<div className={`h-full rounded-md p-2 ${res.status==='CHECKED_IN'?'bg-emerald-950/60 text-emerald-200':'bg-sky-950/60 text-sky-200'}`}><b>{guestName(res.customerId)}</b><div className="truncate text-[10px]">#{res.id.slice(0,8)}</div></div>:block?<div className="h-full rounded-md bg-amber-950/50 p-2 text-amber-200">BLOCK<div className="truncate text-[10px]">{block.reason}</div></div>:<div className="grid h-full place-items-center text-slate-700">·</div>}</td>})}</tr>)}</tbody></table></div>
    </section>

    <section className="mt-5 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 text-emerald-300"/><div><b className="text-emerald-200">Checkout conservation active</b><p className="mt-1 text-xs text-slate-400">Checkout now requires all booked accommodation posted, zero guest receivable and zero unapplied deposit. Use Folios to settle, apply/refund deposits, post services, or perform paid extensions.</p></div></div></section>

    {move&&<MoveDialog reservation={move} rooms={rooms} onClose={()=>setMove(null)} onSave={(id,reason)=>void moveStay(id,reason)}/>}
  </div>
}
const Metric=({label,value}:{label:string;value:string})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>;
const Queue=({title,icon,empty,children}:{title:string;icon:React.ReactNode;empty:string;children:React.ReactNode})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="mb-3 flex items-center gap-2 font-bold">{icon}{title}</div><div className="space-y-2">{React.Children.count(children)?children:<div className="p-5 text-center text-sm text-slate-600">{empty}</div>}</div></div>;
function MoveDialog({reservation,rooms,onClose,onSave}:{reservation:any;rooms:any[];onClose:()=>void;onSave:(id:string,reason:string)=>void}){
 const current=rooms.find(r=>r.id===reservation.roomId);const options=rooms.filter(r=>r.id!==reservation.roomId&&r.maintenanceState!=='OUT_OF_ORDER'&&r.housekeepingState==='CLEAN'&&Number(r.capacity||0)>=Number(reservation.guests||1));const [roomId,setRoomId]=useState(options[0]?.id||'');const [reason,setReason]=useState('');
 return <ActionDialog title={`Move stay from room ${current?.number||reservation.roomId}`} onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();onSave(roomId,reason)}}><label>Destination<select required className={fieldClass} value={roomId} onChange={e=>setRoomId(e.target.value)}>{options.map(r=><option key={r.id} value={r.id}>{r.number} · capacity {r.capacity}</option>)}</select></label><label>Reason<textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Upgrade, room issue, guest request…"/></label><p className="text-xs text-slate-500">The old room becomes DIRTY and receives an automatic turnaround block. The original reservation rate snapshot is preserved.</p><button disabled={!roomId} className={primaryButtonClass}>Move room</button></form></ActionDialog>
}
