import React,{useMemo,useState} from 'react';
import {Archive,Barcode,Boxes,ClipboardCheck,MapPin,Plus,Search,ShieldCheck,Tag,UserCheck,Wrench} from 'lucide-react';
import {useRuntime} from '../runtime/RuntimeProvider';
import {barcodeEquals,useBarcodeScanner} from '../hooks/useBarcodeScanner';
import {ActionDialog} from './ActionDialog';
import {buttonClass,fieldClass,money,primaryButtonClass,recordOf,recordsOf,shortDate} from './records';

// SERVOS_PATCH_09_ASSET_REGISTER
type Section='REGISTER'|'MAINTENANCE'|'COMMISSION'|'CATEGORIES';
const terminal=(status:string)=>['LOST','RETIRED','DISPOSED'].includes(status);
const tone=(value:string)=>value==='ACTIVE'||value==='COMPLETED'||value==='GOOD'?'text-emerald-300':value==='CRITICAL'||value==='BROKEN'||value==='LOST'||value==='DISPOSED'?'text-rose-300':value==='IN_PROGRESS'||value==='POOR'?'text-amber-300':'text-slate-300';
const kesMinor=(minor:unknown)=>money(Number(minor||0)/100);

export function NativeAssetsView(){
  const runtime=useRuntime();const s=runtime.snapshot!;const perms=s.actor.permissions;
  const assets=recordsOf(s,'assets'),categories=recordsOf(s,'assetCategories'),acquisitions=recordsOf(s,'assetAcquisitions');
  const events=recordsOf(s,'assetEvents'),maintenance=recordsOf(s,'maintenanceOrders'),maintenanceEvents=recordsOf(s,'maintenanceEvents');
  const employees=recordsOf(s,'employees'),rooms=recordsOf(s,'rooms'),locations=recordsOf(s,'stockLocations'),stocks=recordsOf(s,'stockItems'),suppliers=recordsOf(s,'suppliers');
  const [section,setSection]=useState<Section>('REGISTER');const [query,setQuery]=useState('');const [selectedId,setSelectedId]=useState(assets[0]?.id||'');
  const [modal,setModal]=useState<{kind:string;data?:any}|null>(null);const [notice,setNotice]=useState('');
  const canManage=perms.includes('assets.manage');const canOperate=perms.includes('assets.operate');const canMaintain=perms.includes('maintenance.manage');
  const selected=assets.find(a=>a.id===selectedId);
  const filtered=useMemo(()=>assets.filter(a=>{const q=query.trim().toLowerCase();if(!q)return true;const category=categories.find(c=>c.id===a.assetCategoryId)?.name||'';const loc=rooms.find(r=>r.id===a.roomId)?.number||locations.find(l=>l.id===a.locationId)?.name||'';return `${a.tag} ${a.name} ${a.serialNumber||''} ${category} ${loc}`.toLowerCase().includes(q);}),[assets,categories,locations,query,rooms]);
  const openMaintenance=maintenance.filter(m=>!['COMPLETED','CANCELLED'].includes(m.status));
  const pending=acquisitions.filter(a=>a.status==='PENDING_COMMISSION');
  const command=async(op:string,payload:any,version?:number)=>{setNotice('');try{await runtime.command(op,payload,version);setModal(null);setNotice('Asset operation committed locally and queued for synchronization.')}catch(e){setNotice(String(e))}};
  const runAsset=async(op:string,asset:any,payload:any={})=>{const rec=recordOf(s,'assets',asset.id);if(rec)await command(op,{id:asset.id,...payload},rec.version)};
  const scan=(raw:string)=>{const code=raw.trim();if(!code)return;const matches=assets.filter(a=>barcodeEquals(a.tag,code));if(matches.length===1){setSelectedId(matches[0].id);setQuery(matches[0].tag);setSection('REGISTER');setNotice(`Opened ${matches[0].tag} · ${matches[0].name}`);}else setNotice(matches.length?'Asset tag is duplicated in this snapshot.':'No asset uses that tag. No record was changed.');};
  useBarcodeScanner({enabled:section==='REGISTER'&&!modal,onScan:scan});

  const assetLocation=(a:any)=>a.roomId?`Room ${rooms.find(r=>r.id===a.roomId)?.number||a.roomId}`:locations.find(l=>l.id===a.locationId)?.name||a.locationId||'Unlocated';
  const custodian=(a:any)=>employees.find(e=>e.id===a.custodianId)?.name||'Unassigned';
  const assetEvents=selected?events.filter(e=>e.assetId===selected.id).slice().sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))).slice(0,30):[];
  const assetMaintenance=selected?maintenance.filter(m=>m.assetId===selected.id).slice().sort((a,b)=>String(b.reportedAt).localeCompare(String(a.reportedAt))):[];
  const sectionButton=(id:Section,label:string)=><button key={id} className={section===id?primaryButtonClass:buttonClass} onClick={()=>setSection(id)}>{label}</button>;

  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Asset Register</h1><p className="mt-1 max-w-3xl text-sm text-slate-400">Permanent tags, custody, locations, inspections, maintenance and procurement commissioning. Scanner input opens the matching tag without mutating anything.</p></div>{canManage&&<button className={primaryButtonClass} onClick={()=>setModal({kind:'ASSET'})}><Plus className="mr-2 inline h-4 w-4"/>Manual asset</button>}</div>
    {notice&&<p role="status" className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-900 p-3 text-sm text-slate-300">{notice}</p>}
    <nav className="mt-5 flex flex-wrap gap-2">{sectionButton('REGISTER',`Register (${assets.length})`)}{sectionButton('MAINTENANCE',`Maintenance (${openMaintenance.length})`)}{sectionButton('COMMISSION',`Commissioning (${pending.length})`)}{sectionButton('CATEGORIES',`Categories (${categories.length})`)}</nav>

    {section==='REGISTER'&&<>
      <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Active" value={assets.filter(a=>a.status==='ACTIVE').length}/><Metric label="Assigned" value={assets.filter(a=>Boolean(a.custodianId)).length}/><Metric label="Open maintenance" value={openMaintenance.length}/><Metric label="Inspection due" value={assets.filter(a=>a.nextInspectionAt&&new Date(`${a.nextInspectionAt}T23:59:59`)<new Date()).length}/><Metric label="Pending commission" value={pending.length}/></section>
      <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(360px,.9fr)_minmax(500px,1.4fr)]">
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input className={fieldClass+' pl-9'} placeholder="Tag, asset, serial, category, location…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="mt-2 flex items-center gap-2 text-xs text-slate-500"><Barcode className="h-4 w-4"/>USB keyboard-wedge scanners can scan an asset tag anywhere on this register.</div><div className="mt-4 max-h-[65vh] space-y-2 overflow-auto">{filtered.map(a=><button key={a.id} onClick={()=>setSelectedId(a.id)} className={`w-full rounded-xl border p-3 text-left ${selectedId===a.id?'border-amber-500 bg-amber-950/20':'border-slate-800 bg-slate-950'}`}><div className="flex items-center justify-between gap-2"><b>{a.tag}</b><span className={'text-xs '+tone(a.status)}>{a.status}</span></div><div className="mt-1 text-sm">{a.name}</div><div className="mt-1 text-xs text-slate-500">{assetLocation(a)} · {custodian(a)} · {categories.find(c=>c.id===a.assetCategoryId)?.name||a.assetCategoryId}</div></button>)}</div></div>
        <div>{selected?<AssetDetail asset={selected} category={categories.find(c=>c.id===selected.assetCategoryId)} location={assetLocation(selected)} custodian={custodian(selected)} events={assetEvents} maintenance={assetMaintenance} rooms={rooms} locations={locations} employees={employees} canManage={canManage} canOperate={canOperate} canMaintain={canMaintain} onEdit={()=>setModal({kind:'ASSET',data:selected})} onAssign={()=>setModal({kind:'ASSIGN',data:selected})} onReturn={()=>setModal({kind:'RETURN',data:selected})} onTransfer={()=>setModal({kind:'TRANSFER',data:selected})} onInspect={()=>setModal({kind:'INSPECT',data:selected})} onMaintenance={()=>setModal({kind:'REPORT',data:{asset:selected}})} onLifecycle={(kind)=>setModal({kind,data:selected})}/>:<div className="rounded-2xl border border-dashed border-slate-800 p-10 text-center text-slate-600">Select or scan an asset.</div>}</div>
      </section>
    </>}

    {section==='MAINTENANCE'&&<section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Maintenance workbench</h2><p className="text-xs text-slate-500">Parts, external service cost and work-order state remain one native transaction at completion.</p></div>{canMaintain&&<button className={primaryButtonClass} onClick={()=>setModal({kind:'REPORT'})}><Wrench className="mr-2 inline h-4 w-4"/>Report work</button>}</div><div className="mt-4 space-y-3">{maintenance.slice().sort((a,b)=>Number(!['COMPLETED','CANCELLED'].includes(b.status))-Number(!['COMPLETED','CANCELLED'].includes(a.status))||String(b.reportedAt).localeCompare(String(a.reportedAt))).map(work=><MaintenanceCard key={work.id} work={work} asset={assets.find(a=>a.id===work.assetId)} room={rooms.find(r=>r.id===work.roomId)} employee={employees.find(e=>e.id===work.assigneeId)} events={maintenanceEvents.filter(e=>e.maintenanceOrderId===work.id)} canManage={canMaintain} onAssign={()=>setModal({kind:'MAINT_ASSIGN',data:work})} onStart={()=>void maintenanceAction(work,'maintenance.start')} onComplete={()=>setModal({kind:'MAINT_COMPLETE',data:work})} onCancel={()=>setModal({kind:'MAINT_CANCEL',data:work})} onBlock={()=>setModal({kind:'MAINT_BLOCK',data:work})}/>)}</div></section>}

    {section==='COMMISSION'&&<section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">Pending capital assets</h2><p className="mt-1 text-xs text-slate-500">Accepted ASSET procurement units sit in clearing until a permanent tag and physical location are assigned.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{pending.map(a=><article key={a.id} className="rounded-xl bg-slate-950 p-4"><div className="flex justify-between gap-3"><div><b>{a.assetName}</b><div className="text-xs text-slate-500">{a.assetCategoryName} · {a.poNumber} / {a.grnNumber} · unit {a.unitOrdinal}</div></div><b>{kesMinor(a.unitCostMinor)}</b></div><div className="mt-2 text-xs text-slate-500">{a.supplierName} · received {shortDate(a.receivedAt)}</div>{canManage&&<button className={primaryButtonClass+' mt-3'} onClick={()=>setModal({kind:'COMMISSION',data:a})}><Tag className="mr-2 inline h-4 w-4"/>Commission asset</button>}</article>)}</div>{!pending.length&&<div className="p-10 text-center text-slate-600">No capital assets are waiting for commissioning.</div>}</section>}

    {section==='CATEGORIES'&&<section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex items-center justify-between"><h2 className="font-bold">Asset categories</h2>{canManage&&<button className={buttonClass} onClick={()=>setModal({kind:'CATEGORY'})}>Add category</button>}</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{categories.map(c=><article key={c.id} className="rounded-xl bg-slate-950 p-3"><div className="flex justify-between gap-2"><div><b>{c.name}</b><div className="font-mono text-xs text-slate-500">{c.code}</div></div>{canManage&&<button className={buttonClass} onClick={()=>setModal({kind:'CATEGORY',data:c})}>Edit</button>}</div><div className="mt-2 text-xs text-slate-500">{c.depreciationMethod} · {c.usefulLifeMonths||0} month(s)</div></article>)}</div></section>}

    {modal?.kind==='ASSET'&&<AssetForm existing={modal.data} categories={categories} rooms={rooms} locations={locations} suppliers={suppliers} onClose={()=>setModal(null)} onSave={async data=>{const id=modal.data?.id||crypto.randomUUID();await command('asset.save',{id,data},recordOf(s,'assets',id)?.version)}}/>}
    {modal?.kind==='CATEGORY'&&<CategoryForm existing={modal.data} onClose={()=>setModal(null)} onSave={async data=>{const id=modal.data?.id||crypto.randomUUID();await command('assetCategory.save',{id,data},recordOf(s,'assetCategories',id)?.version)}}/>}
    {modal?.kind==='ASSIGN'&&<AssignDialog asset={modal.data} employees={employees.filter(e=>e.status==='ACTIVE')} onClose={()=>setModal(null)} onSave={(custodianId,reason)=>runAsset('asset.assign',modal.data,{custodianId,reason})}/>}
    {modal?.kind==='RETURN'&&<ReasonDialog title="Return assigned asset" onClose={()=>setModal(null)} onSave={reason=>runAsset('asset.return',modal.data,{reason})}/>}
    {modal?.kind==='TRANSFER'&&<TransferDialog asset={modal.data} rooms={rooms} locations={locations} onClose={()=>setModal(null)} onSave={(destination,reason)=>runAsset('asset.transfer',modal.data,{...destination,reason})}/>}
    {modal?.kind==='INSPECT'&&<InspectDialog asset={modal.data} onClose={()=>setModal(null)} onSave={(condition,nextInspectionAt,reason)=>runAsset('asset.inspect',modal.data,{condition,nextInspectionAt,reason})}/>}
    {['LOSE','RETIRE','DISPOSE','ARCHIVE'].includes(modal?.kind||'')&&<ReasonDialog title={`${modal?.kind} asset`} onClose={()=>setModal(null)} onSave={reason=>runAsset(modal!.kind==='LOSE'?'asset.lose':modal!.kind==='RETIRE'?'asset.retire':modal!.kind==='DISPOSE'?'asset.dispose':'asset.archive',modal!.data,{reason})}/>}
    {modal?.kind==='REPORT'&&<MaintenanceReportDialog asset={modal.data?.asset} assets={assets.filter(a=>a.status==='ACTIVE')} rooms={rooms} onClose={()=>setModal(null)} onSave={async data=>command('maintenance.report',{id:crypto.randomUUID(),...data})}/>}
    {modal?.kind==='MAINT_ASSIGN'&&<MaintenanceAssignDialog employees={employees.filter(e=>e.status==='ACTIVE')} onClose={()=>setModal(null)} onSave={async assigneeId=>maintenanceAction(modal.data,'maintenance.assign',{assigneeId})}/>}
    {modal?.kind==='MAINT_COMPLETE'&&<MaintenanceCompleteDialog work={modal.data} stocks={stocks} locations={locations} suppliers={suppliers} snapshot={s} onClose={()=>setModal(null)} onSave={async data=>maintenanceAction(modal.data,'maintenance.complete',data)}/>}
    {modal?.kind==='MAINT_CANCEL'&&<ReasonDialog title="Cancel maintenance" onClose={()=>setModal(null)} onSave={reason=>maintenanceAction(modal.data,'maintenance.cancel',{reason})}/>}
    {modal?.kind==='MAINT_BLOCK'&&<MaintenanceBlockDialog work={modal.data} onClose={()=>setModal(null)} onSave={async data=>command('room.block',{id:crypto.randomUUID(),roomId:modal.data.roomId,maintenanceOrderId:modal.data.id,...data})}/>}
    {modal?.kind==='COMMISSION'&&<CommissionDialog acquisition={modal.data} rooms={rooms} locations={locations} onClose={()=>setModal(null)} onSave={async data=>command('asset.commission',{acquisitionId:modal.data.id,...data},recordOf(s,'assetAcquisitions',modal.data.id)?.version)}/>}
  </div>;

  async function maintenanceAction(work:any,op:string,payload:any={}){
    const rec=recordOf(s,'maintenanceOrders',work.id);if(rec)await command(op,{id:work.id,...payload},rec.version);
  }
}

const Metric=({label,value}:{label:string;value:number})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>;

function AssetDetail({asset,category,location,custodian,events,maintenance,rooms,locations,employees,canManage,canOperate,canMaintain,onEdit,onAssign,onReturn,onTransfer,onInspect,onMaintenance,onLifecycle}:{asset:any;category:any;location:string;custodian:string;events:any[];maintenance:any[];rooms:any[];locations:any[];employees:any[];canManage:boolean;canOperate:boolean;canMaintain:boolean;onEdit:()=>void;onAssign:()=>void;onReturn:()=>void;onTransfer:()=>void;onInspect:()=>void;onMaintenance:()=>void;onLifecycle:(kind:string)=>void}){
 return <div className="space-y-4"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-mono text-sm text-amber-300">{asset.tag}</div><h2 className="text-xl font-bold">{asset.name}</h2><div className="mt-1 text-xs text-slate-500">{category?.name||asset.assetCategoryId} · {location}</div></div><div className="text-right text-xs"><div className={tone(asset.status)}>{asset.status}</div><div className={tone(asset.condition)}>{asset.condition}</div></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Small label="Custodian" value={custodian}/><Small label="Serial" value={asset.serialNumber||'—'}/><Small label="Cost" value={kesMinor(asset.purchaseCostMinor)}/><Small label="Warranty" value={asset.warrantyUntil||'—'}/><Small label="Last inspection" value={asset.lastInspectedAt?shortDate(asset.lastInspectedAt):'—'}/><Small label="Next inspection" value={asset.nextInspectionAt||'—'}/><Small label="Acquired" value={asset.acquiredAt||'—'}/><Small label="Source" value={asset.acquisitionSourceId?'Procurement':'Manual / import'}/></div>{!terminal(asset.status)&&<div className="mt-4 flex flex-wrap gap-2">{canManage&&<button className={buttonClass} onClick={onEdit}>Edit metadata</button>}{canOperate&&!asset.custodianId&&<button className={buttonClass} onClick={onAssign}><UserCheck className="mr-1 inline h-4 w-4"/>Assign</button>}{canOperate&&asset.custodianId&&<button className={buttonClass} onClick={onReturn}>Return</button>}{canOperate&&<button className={buttonClass} onClick={onTransfer}><MapPin className="mr-1 inline h-4 w-4"/>Transfer</button>}{canOperate&&<button className={buttonClass} onClick={onInspect}><ClipboardCheck className="mr-1 inline h-4 w-4"/>Inspect</button>}{canMaintain&&<button className={buttonClass} onClick={onMaintenance}><Wrench className="mr-1 inline h-4 w-4"/>Maintenance</button>}{canOperate&&<button className={buttonClass} onClick={()=>onLifecycle('LOSE')}>Lost</button>}{canOperate&&<button className={buttonClass} onClick={()=>onLifecycle('RETIRE')}>Retire</button>}{canOperate&&<button className={buttonClass} onClick={()=>onLifecycle('DISPOSE')}>Dispose</button>}</div>}{terminal(asset.status)&&canManage&&['RETIRED','DISPOSED'].includes(asset.status)&&<button className={buttonClass+' mt-4'} onClick={()=>onLifecycle('ARCHIVE')}><Archive className="mr-1 inline h-4 w-4"/>Archive</button>}</section>
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-bold">Asset history</h3><div className="mt-3 max-h-80 space-y-2 overflow-auto">{events.map(e=><div key={e.id} className="rounded-xl bg-slate-950 p-3 text-xs"><div className="flex justify-between"><b>{e.operation}</b><span className="text-slate-500">{shortDate(e.occurredAt)}</span></div><div className="mt-1 text-slate-500">{eventDelta(e,rooms,locations,employees)||e.reason||e.actorName}</div>{e.reason&&eventDelta(e,rooms,locations,employees)&&<div className="mt-1 text-slate-600">{e.reason}</div>}</div>)}{!events.length&&<div className="text-sm text-slate-600">No lifecycle events yet.</div>}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-bold">Maintenance history</h3><div className="mt-3 max-h-80 space-y-2 overflow-auto">{maintenance.map(m=><div key={m.id} className="rounded-xl bg-slate-950 p-3 text-xs"><div className="flex justify-between"><b>{m.description}</b><span className={tone(m.status)}>{m.status}</span></div><div className="mt-1 text-slate-500">{m.priority} · {m.reportedAt?shortDate(m.reportedAt):'—'}</div></div>)}{!maintenance.length&&<div className="text-sm text-slate-600">No maintenance records.</div>}</div></div></section></div>
}
const eventDelta=(event:any,rooms:any[],locations:any[],employees:any[])=>{
 const before=event.before||{},after=event.after||{};
 const place=(v:any)=>v?.roomId?`Room ${rooms.find(r=>r.id===v.roomId)?.number||v.roomId}`:v?.locationId?(locations.find(l=>l.id===v.locationId)?.name||v.locationId):'Unlocated';
 const person=(id:any)=>employees.find(e=>e.id===id)?.name||id||'Unassigned';
 if(event.operation==='asset.transfer')return `${place(before)} → ${place(after)}`;
 if(event.operation==='asset.assign'||event.operation==='asset.return')return `${person(before.custodianId)} → ${person(after.custodianId)}`;
 if(event.operation==='asset.inspect')return `Condition ${before.condition||'—'} → ${after.condition||'—'}`;
 if(event.operation==='asset.commission')return `Commissioned at ${place(after)}`;
 if(['asset.lose','asset.retire','asset.dispose'].includes(event.operation))return `Status ${before.status||'—'} → ${after.status||'—'}`;
 return '';
};
const Small=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-slate-950 p-3"><div className="text-[10px] uppercase text-slate-500">{label}</div><div className="mt-1 text-sm">{value}</div></div>;

function AssetForm({existing,categories,rooms,locations,suppliers,onClose,onSave}:{existing?:any;categories:any[];rooms:any[];locations:any[];suppliers:any[];onClose:()=>void;onSave:(v:any)=>Promise<void>}){
 const [v,setV]=useState({name:existing?.name||'',tag:existing?.tag||'',assetCategoryId:existing?.assetCategoryId||categories[0]?.id||'',serialNumber:existing?.serialNumber||'',locationType:existing?.roomId?'ROOM':'STOCK',roomId:existing?.roomId||rooms[0]?.id||'',locationId:existing?.locationId||locations[0]?.id||'',supplierId:existing?.supplierId||'',acquiredAt:existing?.acquiredAt||'',purchaseCost:Number(existing?.purchaseCostMinor||0)/100,warrantyUntil:existing?.warrantyUntil||'',notes:existing?.notes||''});
 return <ActionDialog title={existing?'Edit asset metadata':'Create manual asset'} onClose={onClose}><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void onSave({name:v.name,tag:v.tag.toUpperCase(),assetCategoryId:v.assetCategoryId,serialNumber:v.serialNumber||null,roomId:v.locationType==='ROOM'?v.roomId:null,locationId:v.locationType==='STOCK'?v.locationId:null,supplierId:v.supplierId||null,acquiredAt:v.acquiredAt||null,purchaseCostMinor:Math.round(v.purchaseCost*100),warrantyUntil:v.warrantyUntil||null,notes:v.notes})}}><label>Name<input required className={fieldClass} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Permanent tag<input required data-barcode-capture="true" className={fieldClass+' font-mono'} value={v.tag} onChange={e=>setV({...v,tag:e.target.value})}/></label><label>Category<select className={fieldClass} value={v.assetCategoryId} onChange={e=>setV({...v,assetCategoryId:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Serial number<input className={fieldClass} value={v.serialNumber} onChange={e=>setV({...v,serialNumber:e.target.value})}/></label>{!existing&&<><label>Location type<select className={fieldClass} value={v.locationType} onChange={e=>setV({...v,locationType:e.target.value})}><option value="STOCK">Stock / service location</option><option value="ROOM">Room</option></select></label>{v.locationType==='ROOM'?<label>Room<select className={fieldClass} value={v.roomId} onChange={e=>setV({...v,roomId:e.target.value})}>{rooms.map(r=><option key={r.id} value={r.id}>{r.number}</option>)}</select></label>:<label>Location<select className={fieldClass} value={v.locationId} onChange={e=>setV({...v,locationId:e.target.value})}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}</>}<label>Supplier<select className={fieldClass} value={v.supplierId} onChange={e=>setV({...v,supplierId:e.target.value})}><option value="">None / unknown</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Acquisition date<input type="date" className={fieldClass} value={v.acquiredAt} onChange={e=>setV({...v,acquiredAt:e.target.value})}/></label><label>Cost (KES)<input type="number" min="0" step="0.01" className={fieldClass} value={v.purchaseCost} onChange={e=>setV({...v,purchaseCost:Number(e.target.value)})}/></label><label>Warranty until<input type="date" className={fieldClass} value={v.warrantyUntil} onChange={e=>setV({...v,warrantyUntil:e.target.value})}/></label><label className="sm:col-span-2">Notes<textarea className={fieldClass} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label><button disabled={!categories.length||(!existing&&!rooms.length&&!locations.length)} className={primaryButtonClass}>Save asset</button></form></ActionDialog>
}
function CategoryForm({existing,onClose,onSave}:{existing?:any;onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [v,setV]=useState({name:existing?.name||'',code:existing?.code||'',depreciationMethod:existing?.depreciationMethod||'STRAIGHT_LINE',usefulLifeMonths:existing?.usefulLifeMonths||60});return <ActionDialog title={existing?'Edit asset category':'New asset category'} onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();void onSave(v)}}><label>Name<input required className={fieldClass} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Code<input required className={fieldClass} value={v.code} onChange={e=>setV({...v,code:e.target.value.toUpperCase()})}/></label><label>Depreciation<select className={fieldClass} value={v.depreciationMethod} onChange={e=>setV({...v,depreciationMethod:e.target.value})}><option>STRAIGHT_LINE</option><option>NONE</option></select></label><label>Useful life months<input type="number" min={v.depreciationMethod==='NONE'?0:1} max="1200" className={fieldClass} value={v.usefulLifeMonths} onChange={e=>setV({...v,usefulLifeMonths:Number(e.target.value)})}/></label><button className={primaryButtonClass}>Save category</button></form></ActionDialog>}
function AssignDialog({asset,employees,onClose,onSave}:{asset:any;employees:any[];onClose:()=>void;onSave:(id:string,reason:string)=>Promise<void>}){const [id,setId]=useState(employees[0]?.id||'');const [reason,setReason]=useState('Operational custody');return <ActionDialog title={`Assign ${asset.tag}`} onClose={onClose}><div className="space-y-3"><label>Custodian<select className={fieldClass} value={id} onChange={e=>setId(e.target.value)}>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Reason<input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!id||!reason.trim()} className={primaryButtonClass} onClick={()=>void onSave(id,reason)}>Assign asset</button></div></ActionDialog>}
function TransferDialog({asset,rooms,locations,onClose,onSave}:{asset:any;rooms:any[];locations:any[];onClose:()=>void;onSave:(v:any,reason:string)=>Promise<void>}){const [type,setType]=useState(asset.roomId?'STOCK':'ROOM');const [roomId,setRoom]=useState(rooms[0]?.id||'');const [locationId,setLocation]=useState(locations[0]?.id||'');const [reason,setReason]=useState('Operational transfer');return <ActionDialog title={`Transfer ${asset.tag}`} onClose={onClose}><div className="space-y-3"><label>Destination type<select className={fieldClass} value={type} onChange={e=>setType(e.target.value)}><option value="ROOM">Room</option><option value="STOCK">Stock / service location</option></select></label>{type==='ROOM'?<label>Room<select className={fieldClass} value={roomId} onChange={e=>setRoom(e.target.value)}>{rooms.map(r=><option key={r.id} value={r.id}>{r.number}</option>)}</select></label>:<label>Location<select className={fieldClass} value={locationId} onChange={e=>setLocation(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}<label>Reason<input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={type==='ROOM'?!roomId:!locationId} className={primaryButtonClass} onClick={()=>void onSave(type==='ROOM'?{roomId,locationId:null}:{roomId:null,locationId},reason)}>Transfer</button></div></ActionDialog>}
function InspectDialog({asset,onClose,onSave}:{asset:any;onClose:()=>void;onSave:(c:string,d:string,r:string)=>Promise<void>}){const [condition,setCondition]=useState(asset.condition||'GOOD');const [date,setDate]=useState(asset.nextInspectionAt||'');const [reason,setReason]=useState('Scheduled inspection');return <ActionDialog title={`Inspect ${asset.tag}`} onClose={onClose}><div className="space-y-3"><label>Condition<select className={fieldClass} value={condition} onChange={e=>setCondition(e.target.value)}><option>GOOD</option><option>FAIR</option><option>POOR</option><option>BROKEN</option></select></label><label>Next inspection<input type="date" className={fieldClass} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Inspection note<input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className={primaryButtonClass} onClick={()=>void onSave(condition,date,reason)}>Record inspection</button></div></ActionDialog>}
function ReasonDialog({title,onClose,onSave}:{title:string;onClose:()=>void;onSave:(r:string)=>Promise<void>}){const [reason,setReason]=useState('');return <ActionDialog title={title} onClose={onClose}><div className="space-y-3"><label>Reason<textarea autoFocus className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!reason.trim()} className={primaryButtonClass} onClick={()=>void onSave(reason.trim())}>Confirm</button></div></ActionDialog>}

function MaintenanceReportDialog({asset,assets,rooms,onClose,onSave}:{asset?:any;assets:any[];rooms:any[];onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [assetId,setAsset]=useState(asset?.id||'');const [roomId,setRoom]=useState(asset?.roomId||'');const [priority,setPriority]=useState('MEDIUM');const [description,setDescription]=useState('');return <ActionDialog title="Report maintenance" onClose={onClose}><div className="space-y-3"><label>Asset<select className={fieldClass} value={assetId} onChange={e=>setAsset(e.target.value)}><option value="">Room / general work only</option>{assets.map(a=><option key={a.id} value={a.id}>{a.tag} · {a.name}</option>)}</select></label><label>Room<select className={fieldClass} value={roomId} onChange={e=>setRoom(e.target.value)}><option value="">No room</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.number}</option>)}</select></label><label>Priority<select className={fieldClass} value={priority} onChange={e=>setPriority(e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Description<textarea autoFocus className={fieldClass} value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={(!assetId&&!roomId)||!description.trim()} className={primaryButtonClass} onClick={()=>void onSave({assetId:assetId||null,roomId:roomId||null,priority,description})}>Create work order</button></div></ActionDialog>}
function MaintenanceAssignDialog({employees,onClose,onSave}:{employees:any[];onClose:()=>void;onSave:(id:string)=>Promise<void>}){const [id,setId]=useState(employees[0]?.id||'');return <ActionDialog title="Assign maintenance" onClose={onClose}><div className="space-y-3"><select className={fieldClass} value={id} onChange={e=>setId(e.target.value)}>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button disabled={!id} className={primaryButtonClass} onClick={()=>void onSave(id)}>Assign</button></div></ActionDialog>}
function MaintenanceCompleteDialog({work,stocks,locations,suppliers,snapshot,onClose,onSave}:{work:any;stocks:any[];locations:any[];suppliers:any[];snapshot:any;onClose:()=>void;onSave:(v:any)=>Promise<void>}){
 const [resolution,setResolution]=useState('');const [parts,setParts]=useState<any[]>([]);const [stockItemId,setStock]=useState(stocks[0]?.id||'');const [locationId,setLocation]=useState(locations[0]?.id||'');const [quantity,setQuantity]=useState(1);const [serviceCost,setServiceCost]=useState(0);const [supplierId,setSupplier]=useState(suppliers[0]?.id||'');const [invoice,setInvoice]=useState('');
 const addPart=()=>{if(!stockItemId||!locationId||quantity<=0)return;setParts(v=>[...v.filter(x=>x.stockItemId!==stockItemId),{stockItemId,locationId,quantity}])};
 return <ActionDialog title={`Complete maintenance · ${work.id.slice(0,8)}`} onClose={onClose}><div className="space-y-4"><label>Resolution<textarea className={fieldClass} value={resolution} onChange={e=>setResolution(e.target.value)}/></label><div className="rounded-xl border border-slate-800 p-3"><b className="text-sm">Parts used</b><div className="mt-2 grid gap-2 sm:grid-cols-3"><select className={fieldClass} value={stockItemId} onChange={e=>setStock(e.target.value)}>{stocks.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={fieldClass} value={locationId} onChange={e=>setLocation(e.target.value)}>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={fieldClass} type="number" min="0.001" step="0.001" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></div><button className={buttonClass+' mt-2'} onClick={addPart}>Add / replace part</button><div className="mt-2 space-y-1">{parts.map(x=><div key={x.stockItemId} className="flex justify-between rounded-lg bg-slate-950 p-2 text-xs"><span>{stocks.find(s=>s.id===x.stockItemId)?.name} · {x.quantity} @ {locations.find(l=>l.id===x.locationId)?.name}</span><button className="text-rose-300" onClick={()=>setParts(v=>v.filter(p=>p.stockItemId!==x.stockItemId))}>Remove</button></div>)}</div></div><div className="grid gap-2 sm:grid-cols-2"><label>External service cost (KES)<input className={fieldClass} type="number" min="0" step="0.01" value={serviceCost} onChange={e=>setServiceCost(Number(e.target.value))}/></label>{serviceCost>0&&<label>Supplier<select className={fieldClass} value={supplierId} onChange={e=>setSupplier(e.target.value)}>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}{serviceCost>0&&<label className="sm:col-span-2">Supplier invoice reference<input className={fieldClass} value={invoice} onChange={e=>setInvoice(e.target.value)}/></label>}</div><button disabled={!resolution.trim()||(serviceCost>0&&(!supplierId||!invoice.trim()))} className={primaryButtonClass} onClick={()=>void onSave({resolution,parts:parts.map(x=>({...x,stockItemVersion:recordOf(snapshot,'stockItems',x.stockItemId)?.version})),serviceCostMinor:Math.round(serviceCost*100),...(serviceCost>0?{supplierId,invoiceReference:invoice.trim()}:{})})}>Complete work</button></div></ActionDialog>
}
function MaintenanceBlockDialog({work,onClose,onSave}:{work:any;onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [startsAt,setStart]=useState('');const [endsAt,setEnd]=useState('');const [reason,setReason]=useState('Maintenance downtime');const iso=(v:string)=>new Date(v).toISOString();return <ActionDialog title="Block room for maintenance" onClose={onClose}><div className="space-y-3"><label>Start<input type="datetime-local" className={fieldClass} value={startsAt} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="datetime-local" className={fieldClass} value={endsAt} onChange={e=>setEnd(e.target.value)}/></label><label>Reason<input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!work.roomId||!startsAt||!endsAt||!reason.trim()} className={primaryButtonClass} onClick={()=>void onSave({startsAt:iso(startsAt),endsAt:iso(endsAt),reason})}>Block room</button></div></ActionDialog>}
function MaintenanceCard({work,asset,room,employee,events,canManage,onAssign,onStart,onComplete,onCancel,onBlock}:{work:any;asset:any;room:any;employee:any;events:any[];canManage:boolean;onAssign:()=>void;onStart:()=>void;onComplete:()=>void;onCancel:()=>void;onBlock:()=>void}){return <article className="rounded-xl bg-slate-950 p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><b>{work.description}</b><span className={'text-xs '+tone(work.priority)}>{work.priority}</span></div><div className="mt-1 text-xs text-slate-500">{asset?`${asset.tag} · ${asset.name}`:'No asset'}{room?` · Room ${room.number}`:''} · reported {shortDate(work.reportedAt)}</div><div className="text-xs text-slate-500">{employee?`Assigned to ${employee.name}`:'Unassigned'}</div></div><div className={'font-bold '+tone(work.status)}>{work.status}</div></div>{work.resolution&&<p className="mt-3 text-sm text-slate-300">{work.resolution}</p>}{canManage&&!['COMPLETED','CANCELLED'].includes(work.status)&&<div className="mt-3 flex flex-wrap gap-2">{['REPORTED','ASSIGNED'].includes(work.status)&&<button className={buttonClass} onClick={onAssign}>Assign</button>}{work.status==='ASSIGNED'&&<button className={buttonClass} onClick={onStart}>Start</button>}{work.status==='IN_PROGRESS'&&<button className={primaryButtonClass} onClick={onComplete}>Complete</button>}{work.roomId&&<button className={buttonClass} onClick={onBlock}>Block room</button>}<button className={buttonClass} onClick={onCancel}>Cancel</button></div>}{events.length>0&&<div className="mt-3 text-[11px] text-slate-600">{events.length} immutable transition event(s)</div>}</article>}
function CommissionDialog({acquisition,rooms,locations,onClose,onSave}:{acquisition:any;rooms:any[];locations:any[];onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [tag,setTag]=useState('');const [serialNumber,setSerial]=useState('');const [type,setType]=useState(rooms.length?'ROOM':'STOCK');const [roomId,setRoom]=useState(rooms[0]?.id||'');const [locationId,setLocation]=useState(locations[0]?.id||'');const [warrantyUntil,setWarranty]=useState('');const [notes,setNotes]=useState('');useBarcodeScanner({enabled:true,onScan:raw=>setTag(raw.trim().toUpperCase())});return <ActionDialog title={`Commission ${acquisition.assetName}`} onClose={onClose}><div className="space-y-3"><div className="rounded-xl bg-slate-950 p-3 text-sm"><b>{kesMinor(acquisition.unitCostMinor)}</b> · {acquisition.poNumber} / {acquisition.grnNumber}<div className="text-xs text-slate-500">Commissioning reclassifies Asset Clearing → Fixed Assets. It does not touch stock.</div></div><label>Permanent asset tag<input autoFocus data-barcode-capture="true" className={fieldClass+' font-mono'} value={tag} onChange={e=>setTag(e.target.value.toUpperCase())}/></label><label>Serial number<input className={fieldClass} value={serialNumber} onChange={e=>setSerial(e.target.value)}/></label><label>Physical location type<select className={fieldClass} value={type} onChange={e=>setType(e.target.value)}><option value="ROOM">Room</option><option value="STOCK">Stock / service location</option></select></label>{type==='ROOM'?<label>Room<select className={fieldClass} value={roomId} onChange={e=>setRoom(e.target.value)}>{rooms.map(r=><option key={r.id} value={r.id}>{r.number}</option>)}</select></label>:<label>Location<select className={fieldClass} value={locationId} onChange={e=>setLocation(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}<label>Warranty until<input type="date" className={fieldClass} value={warrantyUntil} onChange={e=>setWarranty(e.target.value)}/></label><label>Notes<textarea className={fieldClass} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={!tag.trim()||(type==='ROOM'?!roomId:!locationId)} className={primaryButtonClass} onClick={()=>void onSave({tag:tag.trim().toUpperCase(),serialNumber:serialNumber||null,roomId:type==='ROOM'?roomId:null,locationId:type==='STOCK'?locationId:null,warrantyUntil:warrantyUntil||null,notes})}><ShieldCheck className="mr-2 inline h-4 w-4"/>Commission asset</button></div></ActionDialog>}
