import React, {useMemo,useState} from 'react';
import {useRuntime} from '../runtime/RuntimeProvider';
import {ActionDialog} from './ActionDialog';
import {ManagerApprovalDialog} from './ManagerApprovalDialog';
import {buttonClass,fieldClass,money,primaryButtonClass,recordsOf,shortDate} from './records';
import type {Permission} from '../types/runtime';

const minor=(value:any)=>Number(value||0)/100;

export function NativeCustomerCreditView(){
  const runtime=useRuntime();const s=runtime.snapshot!;const perms=s.actor.permissions;
  const customers=recordsOf<any>(s,'customers');const accounts=recordsOf<any>(s,'customerCreditAccounts');
  const entries=recordsOf<any>(s,'customerCreditEntries').slice().sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt)));
  const reconciliations=recordsOf<any>(s,'customerCreditReconciliations').slice().reverse();
  const discrepancies=recordsOf<any>(s,'customerCreditDiscrepancies').slice().reverse();
  const [query,setQuery]=useState('');const [selected,setSelected]=useState('');const [modal,setModal]=useState<string|null>(null);const [notice,setNotice]=useState('');
  const [approval,setApproval]=useState<{permission:Permission;target:string;run:(token:string)=>Promise<void>}|null>(null);
  const visible=useMemo(()=>customers.filter(c=>[c.name,c.phone,c.email].join(' ').toLowerCase().includes(query.toLowerCase())),[customers,query]);
  const customer=customers.find(c=>c.id===selected)||visible[0];const account=customer?accounts.find(a=>a.customerId===customer.id):null;
  const customerEntries=customer?entries.filter(e=>e.customerId===customer.id):[];
  const balanceMinor=customerEntries.reduce((sum,e)=>sum+Number(e.balanceDeltaMinor||0),0);
  const run=async(op:string,payload:any)=>{setNotice('');try{await runtime.command(op,payload);setNotice('Saved locally.');setModal(null)}catch(e){setNotice(String(e));throw e}};
  const protect=(permission:Permission,target:string,fn:(token?:string)=>Promise<void>)=>perms.includes(permission)?void fn():setApproval({permission,target,run:async token=>fn(token)});
  const totalOutstanding=accounts.reduce((sum,a)=>sum+entries.filter(e=>e.customerId===a.customerId).reduce((n,e)=>n+Number(e.balanceDeltaMinor||0),0),0);

  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
    <div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Customer Accounts</h1><p className="text-sm text-slate-400">Named tabs, customer credit, settlements and reconciliation. Ledger entries are append-only.</p></div><div className="rounded-xl bg-slate-900 px-4 py-3 text-right"><div className="text-xs text-slate-500">Outstanding receivables</div><div className="text-xl font-bold text-amber-300">{money(minor(totalOutstanding))}</div></div></div>
    <div className="grid gap-4 xl:grid-cols-[330px_1fr]">
      <aside className="rounded-2xl border border-slate-800 bg-slate-900 p-3">
        <input className={fieldClass} placeholder="Search customer, phone or email" value={query} onChange={e=>setQuery(e.target.value)}/>
        <div className="mt-3 space-y-2">{visible.map(c=>{const acct=accounts.find(a=>a.customerId===c.id);const bal=entries.filter(e=>e.customerId===c.id).reduce((n,e)=>n+Number(e.balanceDeltaMinor||0),0);return <button key={c.id} className={`w-full rounded-xl border p-3 text-left ${customer?.id===c.id?'border-amber-400 bg-amber-950/20':'border-slate-800 bg-slate-950'}`} onClick={()=>setSelected(c.id)}><b>{c.name}</b><div className="text-xs text-slate-500">{c.phone||'No phone'} · {acct?.status||'NO CREDIT ACCOUNT'}</div><div className={`mt-1 text-sm ${bal>0?'text-amber-300':bal<0?'text-emerald-300':'text-slate-400'}`}>{money(minor(bal))}</div></button>})}</div>
      </aside>
      {!customer?<div className="rounded-2xl border border-dashed border-slate-700 p-8 text-slate-500">No customer selected.</div>:<section className="space-y-4">
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5">
          <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold">{customer.name}</h2><div className="text-sm text-slate-500">{[customer.phone,customer.email].filter(Boolean).join(' · ')}</div></div><div className="flex flex-wrap gap-2">{account&&perms.includes('credit.settle')&&balanceMinor>0&&<button className={primaryButtonClass} onClick={()=>setModal('SETTLE')}>Receive Payment</button>}{perms.includes('credit.manage')&&<button className={buttonClass} onClick={()=>setModal('CONFIGURE')}>{account?'Change Terms':'Enable Credit'}</button>}{account&&perms.includes('credit.reconcile')&&<button className={buttonClass} onClick={()=>setModal('RECONCILE')}>Reconcile</button>}{account&&perms.includes('credit.write_off')&&balanceMinor>0&&<button className={buttonClass} onClick={()=>setModal('WRITEOFF')}>Write off</button>}</div></div>
          {account?<div className="mt-4 grid gap-3 sm:grid-cols-4"><Metric label="Outstanding" value={money(minor(balanceMinor))}/><Metric label="Limit" value={money(minor(account.limitMinor))}/><Metric label="Available" value={money(minor(Math.max(0,Number(account.limitMinor||0)-Math.max(0,balanceMinor))))}/><Metric label="Terms / status" value={`${account.termsDays||0} days · ${account.status}`}/></div>:<p className="mt-4 rounded-xl border border-dashed border-slate-700 p-4 text-sm text-slate-400">Credit is not enabled for this customer. Named POS tabs still work normally.</p>}
        </div>
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-bold">Statement</h3><div className="mt-3 overflow-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="p-2">Date</th><th className="p-2">Type</th><th className="p-2">Reference</th><th className="p-2 text-right">Change</th><th className="p-2">Due / notes</th></tr></thead><tbody>{customerEntries.map(e=><tr key={e.id} className="border-t border-slate-800"><td className="p-2">{shortDate(e.occurredAt)}</td><td className="p-2 font-semibold">{e.kind}</td><td className="p-2">{e.reference||e.orderNumber||e.sourceId}</td><td className={`p-2 text-right ${Number(e.balanceDeltaMinor)>0?'text-amber-300':'text-emerald-300'}`}>{Number(e.balanceDeltaMinor)>0?'+':''}{money(minor(e.balanceDeltaMinor))}</td><td className="p-2 text-xs text-slate-500">{e.dueAt?`Due ${shortDate(e.dueAt)}`:e.notes||''}</td></tr>)}{customerEntries.length===0&&<tr><td colSpan={5} className="p-5 text-center text-slate-500">No credit ledger entries yet.</td></tr>}</tbody></table></div></div>
        <div className="grid gap-4 lg:grid-cols-2">
          <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-bold">Reconciliations</h3>{reconciliations.filter(r=>r.customerId===customer.id).map(r=><div key={r.id} className="mt-2 rounded-xl bg-slate-950 p-3 text-xs"><b>{r.reference}</b> · {shortDate(r.reviewedAt)}<div className="text-slate-500">Balance {money(minor(r.expectedBalanceMinor))} · {r.entryCount} entries</div></div>)}</div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-bold">Discrepancies</h3>{discrepancies.filter(d=>d.customerId===customer.id).map(d=><div key={d.id} className="mt-2 rounded-xl bg-slate-950 p-3 text-xs"><b>{d.status}</b> · {d.reference}<div className="text-slate-500">ServOS {money(minor(d.expectedBalanceMinor))} · statement {money(minor(d.statementBalanceMinor))}</div>{d.status==='OPEN'&&perms.includes('credit.reconcile')&&<button className={buttonClass+' mt-2'} onClick={()=>{setSelected(customer.id);setModal(`RESOLVE:${d.id}`)}}>Resolve</button>}</div>)}</div>
        </div>
      </section>}
    </div>
    {notice&&<p role="status" className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-900 p-3 text-sm">{notice}</p>}
    {customer&&modal==='CONFIGURE'&&<ConfigureDialog account={account} onClose={()=>setModal(null)} onSave={v=>run('customerCredit.configure',{customerId:customer.id,...v})}/>}
    {customer&&modal==='SETTLE'&&<SettlementDialog balance={minor(balanceMinor)} onClose={()=>setModal(null)} onSave={v=>run('customerCredit.settle',{customerId:customer.id,...v})}/>}
    {customer&&modal==='RECONCILE'&&<ReconcileDialog balance={minor(balanceMinor)} onClose={()=>setModal(null)} onSave={v=>run(v.statementBalance===minor(balanceMinor)?'customerCredit.reconcile':'customerCredit.discrepancy',{customerId:customer.id,...v,reason:v.notes})}/>}
    {customer&&modal==='WRITEOFF'&&<WriteOffDialog balance={minor(balanceMinor)} onClose={()=>setModal(null)} onSave={v=>protect('credit.write_off',customer.id,async token=>run('customerCredit.writeOff',{customerId:customer.id,...v,approvalToken:token}))}/>}
    {customer&&modal?.startsWith('RESOLVE:')&&<ResolveDialog onClose={()=>setModal(null)} onSave={v=>run('customerCredit.discrepancy.resolve',{discrepancyId:modal.split(':')[1],...v})}/>}
    {approval&&<ManagerApprovalDialog permission={approval.permission} target={approval.target} onClose={()=>setApproval(null)} onApproved={approval.run}/>}
  </div>;
}
const Metric=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-slate-950 p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-bold">{value}</div></div>;

function ConfigureDialog({account,onSave,onClose}:{account:any;onSave:(v:any)=>Promise<void>;onClose:()=>void}){
  const [limit,setLimit]=useState(Number(account?.limit||0));const [termsDays,setTerms]=useState(Number(account?.termsDays||30));const [status,setStatus]=useState(account?.status||'ACTIVE');const [notes,setNotes]=useState(account?.notes||'');
  return <ActionDialog title="Customer credit terms" onClose={onClose}><div className="space-y-3"><label>Credit limit (KES)<input className={fieldClass} type="number" min="0" step="0.01" value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><label>Payment terms (days)<input className={fieldClass} type="number" min="0" max="365" value={termsDays} onChange={e=>setTerms(Number(e.target.value))}/></label><label>Status<select className={fieldClass} value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>HOLD</option><option>CLOSED</option></select></label><label>Notes<textarea className={fieldClass} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className={primaryButtonClass} onClick={()=>void onSave({limit,termsDays,status,notes})}>Save credit terms</button></div></ActionDialog>
}
function SettlementDialog({balance,onSave,onClose}:{balance:number;onSave:(v:any)=>Promise<void>;onClose:()=>void}){
  const [amount,setAmount]=useState(balance);const [method,setMethod]=useState('CASH');const [card,setCard]=useState('');const [code,setCode]=useState('');const [account,setAccount]=useState('');const [notes,setNotes]=useState('');
  return <ActionDialog title="Receive customer account payment" onClose={onClose}><div className="space-y-3"><p className="text-sm text-slate-400">Outstanding {money(balance)}. Overpayment is not allowed.</p><label>Amount<input className={fieldClass} type="number" min="0.01" max={balance} step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Method<select className={fieldClass} value={method} onChange={e=>setMethod(e.target.value)}><option>CASH</option><option>MPESA</option><option>CARD</option></select></label>{method==='CARD'&&<label>Card approval reference<input className={fieldClass} value={card} onChange={e=>setCard(e.target.value)}/></label>}{method==='MPESA'&&<><label>M-Pesa code<input className={fieldClass} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>Business M-Pesa account<input className={fieldClass} value={account} onChange={e=>setAccount(e.target.value)}/></label></>}<label>Notes<textarea className={fieldClass} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={amount<=0||amount>balance||method==='CARD'&&!card.trim()||method==='MPESA'&&(!code.trim()||!account.trim())} className={primaryButtonClass} onClick={()=>void onSave({amount,method,cardAuthCode:card,notes,mpesa:method==='MPESA'?{code,account,receivedAmount:amount,receivedAt:new Date().toISOString(),confirmed:true}:undefined})}>Confirm payment</button></div></ActionDialog>
}
function ReconcileDialog({balance,onSave,onClose}:{balance:number;onSave:(v:any)=>Promise<void>;onClose:()=>void}){
  const [statementBalance,setStatementBalance]=useState(balance);const [reference,setReference]=useState('');const [notes,setNotes]=useState('');
  const differs=Math.round(statementBalance*100)!==Math.round(balance*100);
  return <ActionDialog title="Reconcile customer account" onClose={onClose}><div className="space-y-3"><p className="text-sm text-slate-400">ServOS expected closing balance: {money(balance)}. A difference creates a discrepancy and does not change the ledger.</p><label>Customer statement balance<input className={fieldClass} type="number" min="0" step="0.01" value={statementBalance} onChange={e=>setStatementBalance(Number(e.target.value))}/></label><label>Statement / review reference<input className={fieldClass} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>{differs?'Discrepancy reason':'Review notes'}<textarea className={fieldClass} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={!reference.trim()||!notes.trim()} className={primaryButtonClass} onClick={()=>void onSave({statementBalance,reference,notes})}>{differs?'Record discrepancy':'Reconcile matching balance'}</button></div></ActionDialog>
}
function WriteOffDialog({balance,onSave,onClose}:{balance:number;onSave:(v:any)=>void;onClose:()=>void}){
  const [amount,setAmount]=useState(balance);const [reason,setReason]=useState('');
  return <ActionDialog title="Write off customer debt" onClose={onClose}><div className="space-y-3"><p className="text-sm text-rose-300">This posts a bad-debt expense and reduces Accounts Receivable. It never invents a payment.</p><input className={fieldClass} type="number" min="0.01" max={balance} step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><textarea className={fieldClass} placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={amount<=0||amount>balance||!reason.trim()} className={primaryButtonClass} onClick={()=>onSave({amount,reason})}>Write off</button></div></ActionDialog>
}
function ResolveDialog({onSave,onClose}:{onSave:(v:any)=>Promise<void>;onClose:()=>void}){
  const [outcome,setOutcome]=useState('STATEMENT_ERROR');const [resolution,setResolution]=useState('');
  return <ActionDialog title="Resolve credit discrepancy" onClose={onClose}><div className="space-y-3"><select className={fieldClass} value={outcome} onChange={e=>setOutcome(e.target.value)}><option>STATEMENT_ERROR</option><option>MISSING_PAYMENT</option><option>MISSING_CHARGE</option><option>ACCEPTED_VARIANCE</option><option>WRITE_OFF_REQUIRED</option></select><textarea className={fieldClass} placeholder="Resolution note" value={resolution} onChange={e=>setResolution(e.target.value)}/><button disabled={!resolution.trim()} className={primaryButtonClass} onClick={()=>void onSave({outcome,resolution})}>Save resolution</button></div></ActionDialog>
}
