import React,{useEffect,useMemo,useState} from 'react';
import {BedDouble,CalendarDays,DoorOpen,Plus,ShieldAlert} from 'lucide-react';
import {useRuntime} from '../runtime/RuntimeProvider';
import { SimpleRoomDialog, ReportProblemDialog } from './SimpleHospitality';
import {ActionDialog} from './ActionDialog';
import {buttonClass,fieldClass,money,primaryButtonClass,recordOf,recordsOf,shortDate} from './records';

// SERVOS_PATCH_05_ROOMS_ENGINE
const localInput=(iso?:string)=>{if(!iso)return'';const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const iso=(local:string)=>new Date(local).toISOString();
const pill=(value:string)=>value==='RESERVED'?'text-sky-300':value==='ACTIVE'||value==='AVAILABLE'||value==='CLEAN'?'text-emerald-300':value==='OUT_OF_ORDER'||value==='DIRTY'?'text-rose-300':'text-amber-300';

export function NativeRoomsView({initialAction=''}:{initialAction?:string}){
  const runtime=useRuntime();const s=runtime.snapshot!;
  const canManage=s.actor.permissions.includes('rooms.manage');const canOperate=s.actor.permissions.includes('rooms.operate');
  const roomTypes=recordsOf(s,'roomTypes'),rooms=recordsOf(s,'rooms'),rates=recordsOf(s,'ratePlans');
  const reservations=recordsOf(s,'roomReservations'),blocks=recordsOf(s,'roomBlocks'),customers=recordsOf(s,'customers');
  const [modal,setModal]=useState<string|null>(null);const [edit,setEdit]=useState<any>(null);const [message,setMessage]=useState('');
  useEffect(()=>{if(initialAction==='add-room'&&canManage){setEdit(null);setModal('SIMPLE_ROOM')}},[initialAction,canManage]);
  const activeReservations=useMemo(()=>reservations.filter(r=>['RESERVED','CHECKED_IN'].includes(r.status)),[reservations]);
  const roomTypeName=(id:string)=>roomTypes.find(x=>x.id===id)?.name||id;
  const activeForRoom=(id:string)=>activeReservations.filter(r=>r.roomId===id);
  const activeBlocks=(id:string)=>blocks.filter(b=>b.roomId===id&&b.status==='ACTIVE');
  const command=async(op:string,payload:any,version?:number)=>{setMessage('');try{await runtime.command(op,payload,version);setModal(null);setEdit(null);setMessage('Saved. Room availability was recalculated from committed records.')}catch(e){setMessage(String(e))}};

  const archive=async(kind:'roomType'|'room'|'ratePlan',id:string,collection:string)=>{
    const rec=recordOf(s,collection,id);if(!rec)return;
    await command(`${kind}.archive`,{id},rec.version);
  };
  const housekeeping=async(room:any)=>{
    const next:{[k:string]:string}={DIRTY:'CLEANING',CLEANING:'INSPECTION',INSPECTION:'CLEAN',CLEAN:'DIRTY'};
    const state=next[room.housekeepingState||'CLEAN'];if(!state)return;
    const rec=recordOf(s,'rooms',room.id);if(rec)await command('room.housekeeping',{id:room.id,state},rec.version);
  };

  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Rooms</h1><p className="mt-1 max-w-3xl text-sm text-slate-400">Add rooms and manage availability. Use Front Desk for arrivals, stays and departures.</p></div><div className="flex gap-2">{canOperate&&<button className={primaryButtonClass} onClick={()=>{setEdit(null);setModal('RESERVATION')}}><CalendarDays className="mr-2 inline h-4 w-4"/>New reservation</button>}{canManage&&<button className={buttonClass} onClick={()=>{setEdit(null);setModal('SIMPLE_ROOM')}}><Plus className="mr-2 inline h-4 w-4"/>Add Room</button>}</div></div>
    {message&&<p role="status" className="mt-4 rounded-xl bg-slate-900 p-3 text-sm text-slate-300">{message}</p>}

    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Rooms" value={rooms.length}/><Metric label="Reserved / active" value={activeReservations.length}/><Metric label="Active blocks" value={blocks.filter(x=>x.status==='ACTIVE').length}/><Metric label="Rate plans" value={rates.length}/>
    </section>

    <section className="mt-6"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-bold">Room board</h2><p className="text-xs text-slate-500">Occupancy is interval-based. Turnaround time remains reserved after departure.</p></div>{canManage&&<div className="flex gap-2"><button className={buttonClass} onClick={()=>{setEdit(null);setModal('TYPE')}}>Room type</button><button className={buttonClass} onClick={()=>{setEdit(null);setModal('RATE')}}>Rate plan</button></div>}</div>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rooms.map(room=>{const rs=activeForRoom(room.id),bs=activeBlocks(room.id);return <article key={room.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><BedDouble className="h-4 w-4 text-amber-300"/><b className="text-lg">{room.number}</b></div><div className="text-xs text-slate-500">{roomTypeName(room.roomTypeId)} · capacity {room.capacity} · turnaround {room.turnaroundMinutes||0}m</div></div><div className="text-right text-[11px]"><div className={pill(room.maintenanceState||'AVAILABLE')}>{room.maintenanceState||'AVAILABLE'}</div><div className={pill(room.housekeepingState||'CLEAN')}>{room.housekeepingState||'CLEAN'}</div></div></div>
        <div className="mt-3 space-y-1 text-xs">{rs.length?rs.map(r=><div key={r.id} className="rounded-lg bg-slate-950 p-2"><b>{customers.find(c=>c.id===r.customerId)?.name||'Guest'}</b><div className="text-slate-500">{shortDate(r.startsAt)} → {shortDate(r.endsAt)}</div></div>):<div className="text-slate-600">No active reservation.</div>}{bs.map(b=><div key={b.id} className="flex items-center justify-between gap-2 rounded-lg border border-amber-700/30 p-2 text-amber-200"><span>Blocked · {b.reason}</span>{canManage&&<button className={buttonClass} onClick={()=>{const inspection=window.prompt('Release inspection note');const rec=recordOf(s,'roomBlocks',b.id);if(inspection?.trim()&&rec)void command('room.unblock',{id:b.id,inspection:inspection.trim()},rec.version)}}>Release</button>}</div>)}</div>
        {s.actor.permissions.includes('maintenance.manage')&&<button className={buttonClass+' mt-3'} onClick={()=>{setEdit(room);setModal('REPORT')}}>Report Problem</button>}
        {canManage&&<div className="mt-3 flex flex-wrap gap-2"><button className={buttonClass} onClick={()=>{setEdit(room);setModal('ROOM')}}>Edit</button><button className={buttonClass} onClick={()=>{setEdit(room);setModal('BLOCK')}}>Block</button><button className={buttonClass} onClick={()=>void housekeeping(room)}>Housekeeping →</button><button className={buttonClass} onClick={()=>{const rec=recordOf(s,'rooms',room.id);if(!rec)return;const next=room.maintenanceState==='OUT_OF_ORDER'?'AVAILABLE':'OUT_OF_ORDER';const reason=next==='OUT_OF_ORDER'?window.prompt('Reason for taking room out of order')||'':'';if(next==='AVAILABLE'||reason.trim())void command('room.condition',{id:room.id,state:next,reason},rec.version)}}>{room.maintenanceState==='OUT_OF_ORDER'?'Return to service':'Out of order'}</button><button className={buttonClass} onClick={()=>void archive('room',room.id,'rooms')}>Archive</button></div>}</article>})}</div>
      {!rooms.length&&<div className="rounded-2xl border border-dashed border-slate-800 p-10 text-center text-sm text-slate-500">No rooms yet. Choose Add Room to create your first room and its type.</div>}
    </section>

    <section className="mt-7 rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">Reservations</h2><div className="mt-3 overflow-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-slate-500"><tr><th className="p-2">Guest</th><th className="p-2">Room</th><th className="p-2">Stay</th><th className="p-2">Quote</th><th className="p-2">Status</th><th className="p-2"></th></tr></thead><tbody>{reservations.map(r=><tr className="border-t border-slate-800" key={r.id}><td className="p-2">{customers.find(c=>c.id===r.customerId)?.name||r.customerId}</td><td className="p-2">{rooms.find(x=>x.id===r.roomId)?.number||r.roomId}</td><td className="p-2">{shortDate(r.startsAt)}<br/>{shortDate(r.endsAt)}</td><td className="p-2">{money(Number(r.quotedAmountMinor||0)/100)}</td><td className={'p-2 font-bold '+pill(r.status)}>{r.status}</td><td className="p-2 text-right">{canOperate&&r.status==='RESERVED'&&<div className="flex justify-end gap-2"><button className={buttonClass} onClick={()=>{setEdit(r);setModal('RESERVATION')}}>Edit</button><button className={buttonClass} onClick={()=>{setEdit(r);setModal('CLOSE_RESERVATION')}}>Cancel / no-show</button></div>}</td></tr>)}</tbody></table></div></section>

    <section className="mt-7 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">Room types</h2><div className="mt-3 space-y-2">{roomTypes.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-slate-950 p-3"><div><b>{x.name}</b><div className="text-xs text-slate-500">{x.code} · max {x.maxGuests} guests</div></div>{canManage&&<div className="flex gap-2"><button className={buttonClass} onClick={()=>{setEdit(x);setModal('TYPE')}}>Edit</button><button className={buttonClass} onClick={()=>void archive('roomType',x.id,'roomTypes')}>Archive</button></div>}</div>)}</div></div>
      <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">Rate plans</h2><div className="mt-3 space-y-2">{rates.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-slate-950 p-3"><div><b>{x.name}</b><div className="text-xs text-slate-500">{roomTypeName(x.roomTypeId)} · {x.mode} · KES {(Number(x.priceMinor||0)/100).toLocaleString()}</div></div>{canManage&&<div className="flex gap-2"><button className={buttonClass} onClick={()=>{setEdit(x);setModal('RATE')}}>Edit</button><button className={buttonClass} onClick={()=>void archive('ratePlan',x.id,'ratePlans')}>Archive</button></div>}</div>)}</div></div></section>

    <section className="mt-5 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 text-amber-300"/><div><h2 className="font-bold text-amber-200">Stay lifecycle gate</h2><p className="mt-1 text-xs text-slate-400">Patch 05 intentionally does not expose check-in/check-out. The staged contract requires one reservation + one stay + one folio, with checkout settlement and deposit invariants. Those commands land with the financial integration rather than inventing a non-financial shortcut.</p></div></div></section>

    {modal==='TYPE'&&<TypeDialog existing={edit} onClose={()=>setModal(null)} onSave={(data:any)=>{const id=edit?.id||crypto.randomUUID();void command('roomType.save',{id,data},recordOf(s,'roomTypes',id)?.version)}}/>}
    {modal==='SIMPLE_ROOM'&&<SimpleRoomDialog onClose={()=>setModal(null)}/>}
    {modal==='REPORT'&&<ReportProblemDialog roomId={edit?.id} label={`Room ${edit?.number}`} onClose={()=>setModal(null)}/>}
    {modal==='ROOM'&&<RoomDialog existing={edit} types={roomTypes} onClose={()=>setModal(null)} onSave={(data:any)=>{const id=edit?.id||crypto.randomUUID();void command('room.save',{id,data},recordOf(s,'rooms',id)?.version)}}/>}
    {modal==='RATE'&&<RateDialog existing={edit} types={roomTypes} onClose={()=>setModal(null)} onSave={(data:any)=>{const id=edit?.id||crypto.randomUUID();void command('ratePlan.save',{id,data},recordOf(s,'ratePlans',id)?.version)}}/>}
    {modal==='RESERVATION'&&<ReservationDialog existing={edit} rooms={rooms} rates={rates} customers={customers} onClose={()=>setModal(null)} onSave={(data:any)=>{const id=edit?.id||crypto.randomUUID();void command(edit?'roomReservation.update':'roomReservation.create',{id,...data},recordOf(s,'roomReservations',id)?.version)}}/>}
    {modal==='BLOCK'&&edit&&<BlockDialog room={edit} onClose={()=>setModal(null)} onSave={(data:any)=>void command('room.block',{id:crypto.randomUUID(),roomId:edit.id,...data})}/>}
    {modal==='CLOSE_RESERVATION'&&edit&&<CloseReservationDialog reservation={edit} onClose={()=>setModal(null)} onSave={(kind:string,reason:string)=>void command(kind,{id:edit.id,reason},recordOf(s,'roomReservations',edit.id)?.version)}/>}
  </div>;
}

const Metric=({label,value}:{label:string;value:number})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>;

function TypeDialog({existing,onClose,onSave}:{existing:any;onClose:()=>void;onSave:(v:any)=>void}){
 const [v,setV]=useState({name:existing?.name||'',code:existing?.code||'',maxGuests:existing?.maxGuests||2,notes:existing?.notes||''});
 return <ActionDialog title={existing?'Edit room type':'New room type'} onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();onSave(v)}}><label>Name<input required className={fieldClass} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Code<input required className={fieldClass} value={v.code} onChange={e=>setV({...v,code:e.target.value.toUpperCase()})}/></label><label>Maximum guests<input required min="1" max="1000" type="number" className={fieldClass} value={v.maxGuests} onChange={e=>setV({...v,maxGuests:Number(e.target.value)})}/></label><label>Notes<textarea className={fieldClass} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label><button className={primaryButtonClass}>Save room type</button></form></ActionDialog>
}
function RoomDialog({existing,types,onClose,onSave}:{existing:any;types:any[];onClose:()=>void;onSave:(v:any)=>void}){
 const [v,setV]=useState({number:existing?.number||'',roomTypeId:existing?.roomTypeId||types[0]?.id||'',capacity:existing?.capacity||1,turnaroundMinutes:existing?.turnaroundMinutes??30,floor:existing?.floor||'',wing:existing?.wing||'',notes:existing?.notes||'',initialStatus:'READY'});
 return <ActionDialog title={existing?`Edit room ${existing.number}`:'New room'} onClose={onClose}><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const data:any={...v};if(existing)delete data.initialStatus;onSave(data)}}><label>Room number<input required className={fieldClass} value={v.number} onChange={e=>setV({...v,number:e.target.value})}/></label><label>Room type<select required className={fieldClass} value={v.roomTypeId} onChange={e=>setV({...v,roomTypeId:e.target.value})}>{types.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Guest capacity<input min="1" required type="number" className={fieldClass} value={v.capacity} onChange={e=>setV({...v,capacity:Number(e.target.value)})}/></label><label>Turnaround minutes<input min="0" max="1440" required type="number" className={fieldClass} value={v.turnaroundMinutes} onChange={e=>setV({...v,turnaroundMinutes:Number(e.target.value)})}/></label><label>Floor<input className={fieldClass} value={v.floor} onChange={e=>setV({...v,floor:e.target.value})}/></label><label>Wing<input className={fieldClass} value={v.wing} onChange={e=>setV({...v,wing:e.target.value})}/></label>{!existing&&<label>Initial state<select className={fieldClass} value={v.initialStatus} onChange={e=>setV({...v,initialStatus:e.target.value})}><option>READY</option><option>DIRTY</option><option>OUT_OF_ORDER</option></select></label>}<label className="sm:col-span-2">Notes<textarea className={fieldClass} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label><button className={primaryButtonClass}>Save room</button></form></ActionDialog>
}
function RateDialog({existing,types,onClose,onSave}:{existing:any;types:any[];onClose:()=>void;onSave:(v:any)=>void}){
 const [v,setV]=useState({name:existing?.name||'',roomTypeId:existing?.roomTypeId||types[0]?.id||'',mode:existing?.mode||'NIGHTLY',price:Number(existing?.priceMinor||0)/100,taxBasisPoints:existing?.taxBasisPoints||0,durationMinutes:existing?.durationMinutes||480,mealPlan:existing?.mealPlan||'ROOM_ONLY',minNights:existing?.minNights||1,maxNights:existing?.maxNights||366});
 return <ActionDialog title={existing?'Edit rate plan':'New rate plan'} onClose={onClose}><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const {price,...data}=v;onSave({...data,priceMinor:Math.round(price*100),currency:'KES'})}}><label>Name<input required className={fieldClass} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Room type<select required className={fieldClass} value={v.roomTypeId} onChange={e=>setV({...v,roomTypeId:e.target.value})}>{types.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Mode<select className={fieldClass} value={v.mode} onChange={e=>setV({...v,mode:e.target.value})}><option>NIGHTLY</option><option>DAY_USE</option></select></label><label>Rate (KES)<input min="0" step="0.01" type="number" className={fieldClass} value={v.price} onChange={e=>setV({...v,price:Number(e.target.value)})}/></label>{v.mode==='DAY_USE'&&<label>Duration minutes<input min="1" max="1440" type="number" className={fieldClass} value={v.durationMinutes} onChange={e=>setV({...v,durationMinutes:Number(e.target.value)})}/></label>}<label>Meal plan<select className={fieldClass} value={v.mealPlan} onChange={e=>setV({...v,mealPlan:e.target.value})}><option>ROOM_ONLY</option><option>BB</option><option>HB</option><option>FB</option></select></label><label>Tax basis points<input min="0" max="10000" type="number" className={fieldClass} value={v.taxBasisPoints} onChange={e=>setV({...v,taxBasisPoints:Number(e.target.value)})}/></label><button className={primaryButtonClass}>Save rate plan</button></form></ActionDialog>
}
function ReservationDialog({existing,rooms,rates,customers,onClose,onSave}:{existing:any;rooms:any[];rates:any[];customers:any[];onClose:()=>void;onSave:(v:any)=>void}){
 const initialRoom=existing?.roomId||rooms[0]?.id||'';const [v,setV]=useState({roomId:initialRoom,ratePlanId:existing?.ratePlanId||rates.find(x=>x.roomTypeId===rooms.find(r=>r.id===initialRoom)?.roomTypeId)?.id||'',customerId:existing?.customerId||customers[0]?.id||'',guests:existing?.guests||1,startsAt:localInput(existing?.startsAt),endsAt:localInput(existing?.endsAt)});
 const room=rooms.find(x=>x.id===v.roomId);const compatible=rates.filter(x=>x.roomTypeId===room?.roomTypeId);
 return <ActionDialog title={existing?'Edit reservation':'New reservation'} onClose={onClose}><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();onSave({...v,startsAt:iso(v.startsAt),endsAt:iso(v.endsAt)})}}><label>Guest<select required className={fieldClass} value={v.customerId} onChange={e=>setV({...v,customerId:e.target.value})}>{customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Room<select required className={fieldClass} value={v.roomId} onChange={e=>{const roomId=e.target.value;const type=rooms.find(r=>r.id===roomId)?.roomTypeId;setV({...v,roomId,ratePlanId:rates.find(x=>x.roomTypeId===type)?.id||''})}}>{rooms.map(x=><option key={x.id} value={x.id}>{x.number} · {x.maintenanceState||'AVAILABLE'}</option>)}</select></label><label>Rate plan<select required className={fieldClass} value={v.ratePlanId} onChange={e=>setV({...v,ratePlanId:e.target.value})}>{compatible.map(x=><option key={x.id} value={x.id}>{x.name} · KES {(x.priceMinor/100).toLocaleString()}</option>)}</select></label><label>Guests<input required min="1" type="number" className={fieldClass} value={v.guests} onChange={e=>setV({...v,guests:Number(e.target.value)})}/></label><label>Arrival<input required type="datetime-local" className={fieldClass} value={v.startsAt} onChange={e=>setV({...v,startsAt:e.target.value})}/></label><label>Departure<input required type="datetime-local" className={fieldClass} value={v.endsAt} onChange={e=>setV({...v,endsAt:e.target.value})}/></label><button disabled={!customers.length||!compatible.length} className={primaryButtonClass}>Save reservation</button></form></ActionDialog>
}
function BlockDialog({room,onClose,onSave}:{room:any;onClose:()=>void;onSave:(v:any)=>void}){
 const [v,setV]=useState({startsAt:'',endsAt:'',reason:''});return <ActionDialog title={`Block room ${room.number}`} onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();onSave({...v,startsAt:iso(v.startsAt),endsAt:iso(v.endsAt)})}}><label>Start<input required type="datetime-local" className={fieldClass} value={v.startsAt} onChange={e=>setV({...v,startsAt:e.target.value})}/></label><label>End<input required type="datetime-local" className={fieldClass} value={v.endsAt} onChange={e=>setV({...v,endsAt:e.target.value})}/></label><label>Reason<input required className={fieldClass} value={v.reason} onChange={e=>setV({...v,reason:e.target.value})}/></label><button className={primaryButtonClass}>Create block</button></form></ActionDialog>
}
function CloseReservationDialog({reservation,onClose,onSave}:{reservation:any;onClose:()=>void;onSave:(kind:string,reason:string)=>void}){
 const [reason,setReason]=useState('');return <ActionDialog title="Close reservation" onClose={onClose}><div className="space-y-3"><label>Reason<textarea required className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="flex gap-2"><button disabled={!reason.trim()} className={primaryButtonClass} onClick={()=>onSave('roomReservation.cancel',reason)}>Cancel reservation</button><button disabled={!reason.trim()} className={buttonClass} onClick={()=>onSave('roomReservation.noShow',reason)}>Mark no-show</button></div></div></ActionDialog>
}
