import React, { useState } from 'react';
import { useRuntime } from '../runtime/RuntimeProvider';
import type { Permission } from '../types/runtime';
import { recordsOf, fieldClass, buttonClass, primaryButtonClass, money } from './records';
import { ManagerApprovalDialog } from './ManagerApprovalDialog';
import { ActionDialog } from './ActionDialog';

export function NativeInventoryView(){
  const runtime=useRuntime();const snapshot=runtime.snapshot!;const stocks=recordsOf(snapshot,'stockItems');const locations=recordsOf(snapshot,'stockLocations');const suppliers=recordsOf(snapshot,'suppliers');const movements=recordsOf(snapshot,'stockMovements').slice().reverse().slice(0,100);
  const [modal,setModal]=useState<string|null>(null); const [approval,setApproval]=useState<{permission:Permission;run:(t:string)=>Promise<void>}|null>(null); const perms=snapshot.actor.permissions;
  const [form,setForm]=useState({stockItemId:stocks[0]?.id||'',locationId:locations[0]?.id||'',toLocationId:locations[1]?.id||'',quantity:1,countedQty:0,unitCost:0,reason:'',supplierId:suppliers[0]?.id||'',deliveryNote:'',invoiceReference:''});
  const act=async(operation:string,payload:any,permission:Permission)=>{const exec=async(token?:string)=>{await runtime.command(operation,{...payload,approvalToken:token});setModal(null)};if(perms.includes(permission))await exec();else setApproval({permission,run:async t=>exec(t)});};
  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Inventory</h1><p className="text-sm text-slate-400">Location-driven stock ledger. Every mutation creates an auditable movement.</p></div><div className="flex flex-wrap gap-2">{perms.includes('inventory.receive')&&<button className={primaryButtonClass} onClick={()=>setModal('RECEIVE')}>Receive</button>}<button className={buttonClass} onClick={()=>setModal('COUNT')}>Count</button><button className={buttonClass} onClick={()=>setModal('TRANSFER')}>Transfer</button><button className={buttonClass} onClick={()=>setModal('WASTE')}>Waste</button></div></div>
  <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-sm"><thead className="bg-slate-900 text-left text-slate-400"><tr><th className="p-3">Stock item</th><th className="p-3">Unit</th>{locations.map(l=><th className="p-3" key={l.id}>{l.name}</th>)}<th className="p-3">Avg cost</th></tr></thead><tbody>{stocks.map(s=><tr key={s.id} className="border-t border-slate-800"><td className="p-3 font-semibold">{s.name}<div className="text-xs text-slate-500">{s.code}</div></td><td className="p-3">{s.baseUnit}</td>{locations.map(l=><td className="p-3 font-mono" key={l.id}>{Number(s.currentStock?.[l.id]||0).toLocaleString()}</td>)}<td className="p-3">{money(s.averageUnitCost)}</td></tr>)}</tbody></table></div>
  <h2 className="mb-2 mt-6 font-bold">Recent movements</h2><div className="space-y-2">{movements.map(m=><div key={m.id} className="grid grid-cols-[1fr_auto] gap-3 rounded-xl border border-slate-800 bg-slate-900 p-3 text-sm"><div><b>{m.stockItemName}</b> · {m.locationName}<div className="text-xs text-slate-500">{m.movementType} · {m.reasonCode} · {m.actorName}</div></div><span className={Number(m.quantityDelta)>=0?'text-emerald-300':'text-rose-300'}>{Number(m.quantityDelta)>0?'+':''}{m.quantityDelta} {m.baseUnit}</span></div>)}</div>
  {modal&&<ActionDialog title={{RECEIVE:'Receive stock',COUNT:'Physical count',TRANSFER:'Transfer stock',WASTE:'Declare waste'}[modal]||modal} onClose={()=>setModal(null)}><InventoryForm modal={modal} form={form} setForm={setForm} stocks={stocks} locations={locations} suppliers={suppliers} onSubmit={async()=>{if(modal==='RECEIVE')await act('inventory.receive',{stockItemId:form.stockItemId,locationId:form.locationId,quantity:form.quantity,unitCost:form.unitCost,supplierId:form.supplierId||undefined,deliveryNote:form.deliveryNote,invoiceReference:form.invoiceReference,reason:form.reason||'Stock receipt'},'inventory.receive');if(modal==='COUNT')await act('inventory.adjust',{stockItemId:form.stockItemId,locationId:form.locationId,countedQty:form.countedQty,reason:form.reason||'Physical stock count'},'inventory.count');if(modal==='WASTE')await act('inventory.waste',{stockItemId:form.stockItemId,locationId:form.locationId,quantity:form.quantity,reason:form.reason||'Declared waste'},'inventory.waste');if(modal==='TRANSFER')await act('inventory.transfer',{stockItemId:form.stockItemId,locationId:form.locationId,toLocationId:form.toLocationId,quantity:form.quantity,reason:form.reason||'Internal transfer'},'inventory.transfer');}}/></ActionDialog>}
  {approval&&<ManagerApprovalDialog permission={approval.permission} onClose={()=>setApproval(null)} onApproved={approval.run}/>}</div>;
}
const InventoryForm=({modal,form,setForm,stocks,locations,suppliers,onSubmit}:{modal:string;form:any;setForm:(x:any)=>void;stocks:any[];locations:any[];suppliers:any[];onSubmit:()=>Promise<void>})=><div className="space-y-3"><label>Stock item<select className={fieldClass} value={form.stockItemId} onChange={e=>setForm({...form,stockItemId:e.target.value})}>{stocks.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Location<select className={fieldClass} value={form.locationId} onChange={e=>setForm({...form,locationId:e.target.value})}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{modal==='TRANSFER'&&<label>Destination<select className={fieldClass} value={form.toLocationId} onChange={e=>setForm({...form,toLocationId:e.target.value})}>{locations.filter(l=>l.id!==form.locationId).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}{modal==='COUNT'?<label>Counted quantity<input className={fieldClass} type="number" min="0" step="0.001" value={form.countedQty} onChange={e=>setForm({...form,countedQty:Number(e.target.value)})}/></label>:<label>Quantity<input className={fieldClass} type="number" min="0.001" step="0.001" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label>}{modal==='RECEIVE'&&<><label>Unit cost<input className={fieldClass} type="number" min="0" step="0.01" value={form.unitCost} onChange={e=>setForm({...form,unitCost:Number(e.target.value)})}/></label><label>Supplier<select className={fieldClass} value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">None</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><input className={fieldClass} placeholder="Delivery note" value={form.deliveryNote} onChange={e=>setForm({...form,deliveryNote:e.target.value})}/><input className={fieldClass} placeholder="Invoice reference" value={form.invoiceReference} onChange={e=>setForm({...form,invoiceReference:e.target.value})}/></>}<label>Reason / note<textarea className={fieldClass} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button className={primaryButtonClass} onClick={()=>void onSubmit()}>Commit movement</button></div>;
