import React,{useMemo,useState} from 'react';
import {BedDouble,CreditCard,FileText,Plus,RefreshCw,RotateCcw,WalletCards} from 'lucide-react';
import {useRuntime} from '../runtime/RuntimeProvider';
import {ActionDialog} from './ActionDialog';
import {NativeReceiptDialog} from './NativeReceiptDialog';
import {buttonClass,fieldClass,money,primaryButtonClass,recordOf,recordsOf,shortDate} from './records';

// SERVOS_PATCH_07_FOLIOS
const kesMinor=(minor:unknown)=>money(Number(minor||0)/100);
const statusTone=(status:string)=>status==='OPEN'?'text-emerald-300':status==='CLOSED'?'text-slate-400':'text-amber-300';

export function NativeFoliosView(){
  const runtime=useRuntime();const s=runtime.snapshot!;const perms=s.actor.permissions;
  const reservations=recordsOf(s,'roomReservations'),folios=recordsOf(s,'folios'),entries=recordsOf(s,'folioEntries');
  const rooms=recordsOf(s,'rooms'),customers=recordsOf(s,'customers'),rates=recordsOf(s,'ratePlans'),services=recordsOf(s,'hotelServices'),receipts=recordsOf(s,'receiptDocuments');
  const [selectedId,setSelectedId]=useState<string>(()=>folios.find(f=>f.status==='OPEN')?.id||reservations.find(r=>['RESERVED','CHECKED_IN'].includes(r.status))?.id||'');
  const [modal,setModal]=useState<{kind:string;data?:any}|null>(null);const [notice,setNotice]=useState('');
  const reservation=reservations.find(r=>r.id===selectedId);const folio=folios.find(f=>f.id===selectedId);
  const room=rooms.find(r=>r.id===reservation?.roomId);const customer=customers.find(c=>c.id===reservation?.customerId);
  const folioEntries=useMemo(()=>entries.filter(e=>e.folioId===selectedId).slice().sort((a,b)=>String(a.postedAt||'').localeCompare(String(b.postedAt||''))),[entries,selectedId]);
  const hotelReceipt=receipts.filter(r=>r.folioId===selectedId&&r.documentType==='HOTEL_FOLIO').slice().sort((a,b)=>String(b.issuedAt).localeCompare(String(a.issuedAt)))[0];
  const candidates=reservations.filter(r=>['RESERVED','CHECKED_IN','CHECKED_OUT'].includes(r.status)||folios.some(f=>f.id===r.id));
  const command=async(op:string,payload:any,version?:number)=>{setNotice('');try{await runtime.command(op,payload,version);setModal(null);setNotice('Folio action committed locally and queued for synchronization.')}catch(e){setNotice(String(e))}};
  const openFolio=async()=>{if(!reservation)return;const rec=recordOf(s,'roomReservations',reservation.id);if(rec)await command('folio.open',{id:reservation.id},rec.version)};
  const applyDeposit=async()=>{if(!folio)return;const amount=Math.min(Number(folio.balanceMinor||0),Number(folio.depositMinor||0));if(amount<=0)return;const rec=recordOf(s,'folios',folio.id);if(rec)await command('folio.applyDeposit',{id:folio.id,amountMinor:amount},rec.version)};
  const postAccommodation=async(settleBookedStay=false)=>{if(!folio)return;const rec=recordOf(s,'folios',folio.id);if(rec)await command('folio.postAccommodation',{id:folio.id,settleBookedStay},rec.version)};
  const checkout=async()=>{if(!folio||!reservation||!room)return;const stay=recordOf(s,'stays',folio.id),res=recordOf(s,'roomReservations',folio.id),fr=recordOf(s,'folios',folio.id),rr=recordOf(s,'rooms',room.id);if(!stay||!res||!fr||!rr)return;await command('stay.checkOut',{id:folio.id,reservationVersion:res.version,folioVersion:fr.version,roomVersion:rr.version},stay.version)};

  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Folios</h1><p className="mt-1 max-w-3xl text-sm text-slate-400">Guest receivables, deposits, accommodation, room charges and checkout settlement. All values are stored as integer KES minor units.</p></div><select className={fieldClass+' max-w-sm'} value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select reservation / folio</option>{candidates.map(r=><option key={r.id} value={r.id}>{customers.find(c=>c.id===r.customerId)?.name||'Guest'} · Room {rooms.find(x=>x.id===r.roomId)?.number||r.roomId} · {r.status}</option>)}</select></div>
    {notice&&<p role="status" className="mt-4 rounded-xl bg-slate-900 p-3 text-sm text-slate-300">{notice}</p>}

    {!reservation?<div className="mt-6 rounded-2xl border border-dashed border-slate-800 p-10 text-center text-slate-500">Select a reservation to review its folio.</div>:<>
      <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <Metric label="Guest" value={customer?.name||'Guest'}/><Metric label="Room" value={room?.number||'—'}/><Metric label="Reservation" value={reservation.status}/><Metric label="Receivable" value={folio?kesMinor(folio.balanceMinor):'Not opened'}/><Metric label="Unapplied deposit" value={folio?kesMinor(folio.depositMinor):'—'}/>
      </section>

      {!folio?<section className="mt-5 rounded-2xl border border-amber-700/30 bg-amber-950/10 p-5"><h2 className="font-bold">No folio yet</h2><p className="mt-1 text-sm text-slate-400">Open the reservation folio to accept a deposit before arrival or prepare it for check-in.</p>{perms.includes('folio.manage')&&['RESERVED','CHECKED_IN'].includes(reservation.status)&&<button className={primaryButtonClass+' mt-3'} onClick={()=>void openFolio()}>Open folio</button>}</section>:<>
        <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Folio controls <span className={'ml-2 text-xs '+statusTone(folio.status)}>{folio.status}</span></h2><p className="text-xs text-slate-500">Deposits are liabilities until applied. Direct payments cannot exceed the receivable.</p></div>{hotelReceipt&&<button className={buttonClass} onClick={()=>setModal({kind:'RECEIPT',data:hotelReceipt})}><FileText className="mr-2 inline h-4 w-4"/>Hotel receipt</button>}</div>
          {folio.status==='OPEN'&&<div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
            <button className={buttonClass} onClick={()=>void postAccommodation(false)}><RefreshCw className="mr-2 inline h-4 w-4"/>Post due accommodation</button>
            <button className={buttonClass} onClick={()=>void postAccommodation(true)}>Post booked stay</button>
            <button className={buttonClass} onClick={()=>setModal({kind:'SERVICE'})}><Plus className="mr-2 inline h-4 w-4"/>Hotel service</button>
            <button className={buttonClass} onClick={()=>setModal({kind:'DEPOSIT'})}><WalletCards className="mr-2 inline h-4 w-4"/>Record deposit</button>
            <button className={buttonClass} disabled={Number(folio.balanceMinor||0)<=0} onClick={()=>setModal({kind:'PAY'})}><CreditCard className="mr-2 inline h-4 w-4"/>Settle balance</button>
            <button className={buttonClass} disabled={Number(folio.balanceMinor||0)<=0||Number(folio.depositMinor||0)<=0} onClick={()=>void applyDeposit()}>Apply deposit</button>
            <button className={buttonClass} disabled={Number(folio.depositMinor||0)<=0} onClick={()=>setModal({kind:'REFUND_DEPOSIT'})}><RotateCcw className="mr-2 inline h-4 w-4"/>Refund deposit</button>
            {reservation.status==='CHECKED_IN'&&<button className={buttonClass} onClick={()=>setModal({kind:'EXTEND'})}>Extend stay</button>}
            {reservation.status==='CHECKED_IN'&&<button className={primaryButtonClass} onClick={()=>void checkout()}><BedDouble className="mr-2 inline h-4 w-4"/>Check out</button>}
          </div>}
        </section>

        <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">Ledger</h2><div className="mt-3 overflow-auto"><table className="w-full min-w-[880px] text-left text-xs"><thead className="text-slate-500"><tr><th className="p-2">Posted</th><th className="p-2">Type</th><th className="p-2">Description</th><th className="p-2 text-right">Receivable Δ</th><th className="p-2 text-right">Deposit Δ</th><th className="p-2"></th></tr></thead><tbody>{folioEntries.map(e=><tr key={e.id} className="border-t border-slate-800"><td className="p-2">{shortDate(e.postedAt)}</td><td className="p-2 font-mono">{e.kind}</td><td className="p-2">{e.description||e.sourceType||e.paymentId||e.refundId||'Folio entry'}</td><td className={`p-2 text-right ${Number(e.balanceDeltaMinor||0)>0?'text-amber-300':Number(e.balanceDeltaMinor||0)<0?'text-emerald-300':''}`}>{kesMinor(e.balanceDeltaMinor)}</td><td className="p-2 text-right">{kesMinor(e.depositDeltaMinor)}</td><td className="p-2 text-right">{perms.includes('folio.reverse')&&e.kind==='CHARGE'&&Number(e.balanceDeltaMinor||0)>0&&<button className={buttonClass} onClick={()=>setModal({kind:'REVERSE',data:e})}>Reverse</button>}</td></tr>)}</tbody></table>{!folioEntries.length&&<div className="p-8 text-center text-slate-600">No folio entries yet.</div>}</div></section>
      </>}

      <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-bold">Hotel services</h2><p className="text-xs text-slate-500">Active service masters snapshot their price and tax when posted to a folio.</p></div>{perms.includes('folio.manage')&&<button className={buttonClass} onClick={()=>setModal({kind:'SERVICE_MASTER'})}>Add service</button>}</div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{services.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-slate-950 p-3"><div><b>{x.name}</b><div className="text-xs text-slate-500">{x.code} · {kesMinor(x.priceMinor)}</div></div>{perms.includes('folio.manage')&&<button className={buttonClass} onClick={()=>setModal({kind:'SERVICE_MASTER',data:x})}>Edit</button>}</div>)}</div></section>
    </>}

    {modal?.kind==='SERVICE'&&folio&&<ServiceChargeDialog services={services} onClose={()=>setModal(null)} onSave={async(serviceId,quantity)=>{const fr=recordOf(s,'folios',folio.id),sr=recordOf(s,'hotelServices',serviceId);if(fr&&sr)await command('folio.postService',{id:folio.id,serviceId,serviceVersion:sr.version,quantity},fr.version)}}/>}
    {(modal?.kind==='DEPOSIT'||modal?.kind==='PAY')&&folio&&<FolioPaymentDialog kind={modal.kind} snapshot={s} maximumMinor={modal.kind==='PAY'?Number(folio.balanceMinor||0):undefined} onClose={()=>setModal(null)} onSave={async payload=>{const fr=recordOf(s,'folios',folio.id);if(fr)await command(modal.kind==='DEPOSIT'?'folio.deposit':'folio.pay',{id:folio.id,...payload},fr.version)}}/>}
    {modal?.kind==='REFUND_DEPOSIT'&&folio&&<DepositRefundDialog maximumMinor={Number(folio.depositMinor||0)} onClose={()=>setModal(null)} onSave={async payload=>{const fr=recordOf(s,'folios',folio.id);if(fr)await command('folio.refundDeposit',{id:folio.id,...payload},fr.version)}}/>}
    {modal?.kind==='REVERSE'&&folio&&<ReasonDialog title="Reverse unpaid folio charge" onClose={()=>setModal(null)} onSave={async reason=>{const fr=recordOf(s,'folios',folio.id);if(fr)await command('folio.reverse',{id:folio.id,entryId:modal.data.id,reason},fr.version)}}/>}
    {modal?.kind==='EXTEND'&&folio&&reservation&&room&&<ExtensionDialog rates={rates.filter(r=>r.roomTypeId===room.roomTypeId)} snapshot={s} onClose={()=>setModal(null)} onSave={async(v)=>{const stay=recordOf(s,'stays',folio.id),fr=recordOf(s,'folios',folio.id),rr=recordOf(s,'roomReservations',folio.id),roomRec=recordOf(s,'rooms',room.id),rateRec=recordOf(s,'ratePlans',v.ratePlanId);if(stay&&fr&&rr&&roomRec&&rateRec)await command('stay.extend',{id:folio.id,ratePlanId:v.ratePlanId,units:v.units,reservationVersion:rr.version,folioVersion:fr.version,roomVersion:roomRec.version,ratePlanVersion:rateRec.version,payment:v.payment},stay.version)}}/>}
    {modal?.kind==='SERVICE_MASTER'&&<ServiceMasterDialog existing={modal.data} onClose={()=>setModal(null)} onSave={async data=>{const id=modal.data?.id||crypto.randomUUID();await command('hotelService.save',{id,data},recordOf(s,'hotelServices',id)?.version)}}/>}
    {modal?.kind==='RECEIPT'&&<NativeReceiptDialog order={{id:`hotel-${selectedId}`}} receiptId={modal.data.id} reprint onClose={()=>setModal(null)} onJobsChanged={()=>undefined}/>}
  </div>
}

const Metric=({label,value}:{label:string;value:string})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 break-words font-bold">{value}</div></div>;

function ServiceChargeDialog({services,onClose,onSave}:{services:any[];onClose:()=>void;onSave:(id:string,quantity:number)=>Promise<void>}){
 const [serviceId,setServiceId]=useState(services[0]?.id||'');const [quantity,setQuantity]=useState(1);const service=services.find(x=>x.id===serviceId);
 return <ActionDialog title="Post hotel service" onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();void onSave(serviceId,quantity)}}><label>Service<select className={fieldClass} value={serviceId} onChange={e=>setServiceId(e.target.value)}>{services.map(x=><option key={x.id} value={x.id}>{x.name} · {kesMinor(x.priceMinor)}</option>)}</select></label><label>Quantity<input className={fieldClass} type="number" min="1" max="1000" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><p className="text-xs text-slate-500">Charge preview: {kesMinor(Number(service?.priceMinor||0)*quantity)}</p><button disabled={!serviceId||quantity<1} className={primaryButtonClass}>Post service</button></form></ActionDialog>
}

function FolioPaymentDialog({kind,snapshot,maximumMinor,onClose,onSave}:{kind:string;snapshot:any;maximumMinor?:number;onClose:()=>void;onSave:(v:any)=>Promise<void>}){
 const config=recordsOf(snapshot,'paymentConfig')[0]||{methods:['CASH']};const methods=config.methods||['CASH'];const [method,setMethod]=useState(methods[0]||'CASH');const [amount,setAmount]=useState(maximumMinor?maximumMinor/100:0);const [cash,setCash]=useState(maximumMinor?maximumMinor/100:0);const [reference,setReference]=useState('');const account=config.mpesaAccounts?.[0]?.number||'';
 const amountMinor=Math.round(Number(amount||0)*100);const payload:any={amountMinor,method};if(method==='CASH')payload.cashTenderedMinor=Math.round(Number(cash||0)*100);else{payload.reference=reference;payload.manuallyConfirmed=true;if(method==='MPESA')payload.account=account}
 return <ActionDialog title={kind==='DEPOSIT'?'Record guest deposit':'Settle folio'} onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();void onSave(payload)}}><label>Method<select className={fieldClass} value={method} onChange={e=>setMethod(e.target.value)}>{methods.map((m:string)=><option key={m}>{m}</option>)}</select></label><label>Amount (KES)<input className={fieldClass} type="number" min="0.01" max={maximumMinor?maximumMinor/100:undefined} step="0.01" value={amount} onChange={e=>{setAmount(Number(e.target.value));setCash(Number(e.target.value))}}/></label>{method==='CASH'?<label>Cash tendered (KES)<input className={fieldClass} type="number" min={amount} step="0.01" value={cash} onChange={e=>setCash(Number(e.target.value))}/></label>:<><label>{method==='MPESA'?'Transaction code':'External approval reference'}<input className={fieldClass} value={reference} onChange={e=>setReference(e.target.value.toUpperCase())}/></label>{method==='MPESA'&&<label>M-Pesa account<input disabled className={fieldClass} value={account}/></label>}<p className="text-xs text-amber-200">This action records funds only after you manually verify the external receipt.</p></>}<button disabled={amountMinor<=0||(maximumMinor!==undefined&&amountMinor>maximumMinor)||(method!=='CASH'&&!reference.trim())} className={primaryButtonClass}>{kind==='DEPOSIT'?'Record deposit':'Record settlement'}</button></form></ActionDialog>
}

function DepositRefundDialog({maximumMinor,onClose,onSave}:{maximumMinor:number;onClose:()=>void;onSave:(v:any)=>Promise<void>}){
 const [method,setMethod]=useState('CASH');const [amount,setAmount]=useState(maximumMinor/100);const [reference,setReference]=useState('');const [reason,setReason]=useState('');
 const amountMinor=Math.round(amount*100);const payload:any={amountMinor,method,reason};if(method!=='CASH'){payload.reference=reference;payload.manuallyConfirmed=true}
 return <ActionDialog title="Refund unapplied deposit" onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();void onSave(payload)}}><label>Method<select className={fieldClass} value={method} onChange={e=>setMethod(e.target.value)}><option>CASH</option><option>MPESA</option><option>CARD</option></select></label><label>Amount (KES)<input className={fieldClass} min="0.01" max={maximumMinor/100} step="0.01" type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>{method!=='CASH'&&<label>Payout reference<input className={fieldClass} value={reference} onChange={e=>setReference(e.target.value.toUpperCase())}/></label>}<label>Reason<textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={amountMinor<=0||amountMinor>maximumMinor||!reason.trim()||(method!=='CASH'&&!reference.trim())} className={primaryButtonClass}>Record refund</button></form></ActionDialog>
}

function ExtensionDialog({rates,snapshot,onClose,onSave}:{rates:any[];snapshot:any;onClose:()=>void;onSave:(v:any)=>Promise<void>}){
 const config=recordsOf(snapshot,'paymentConfig')[0]||{methods:['CASH']};const methods=config.methods||['CASH'];const [ratePlanId,setRate]=useState(rates[0]?.id||'');const [units,setUnits]=useState(1);const [method,setMethod]=useState(methods[0]||'CASH');const [reference,setReference]=useState('');const rate=rates.find(r=>r.id===ratePlanId);const amountMinor=Number(rate?.priceMinor||0)*units;const account=config.mpesaAccounts?.[0]?.number||'';
 const payment:any={amountMinor,method};if(method==='CASH')payment.cashTenderedMinor=amountMinor;else{payment.reference=reference;payment.manuallyConfirmed=true;if(method==='MPESA')payment.account=account}
 return <ActionDialog title="Paid stay extension" onClose={onClose}><form className="space-y-3" onSubmit={e=>{e.preventDefault();void onSave({ratePlanId,units,payment})}}><label>Rate plan<select className={fieldClass} value={ratePlanId} onChange={e=>setRate(e.target.value)}>{rates.map(r=><option key={r.id} value={r.id}>{r.name} · {kesMinor(r.priceMinor)}</option>)}</select></label><label>Rate units<input className={fieldClass} type="number" min="1" max="366" value={units} onChange={e=>setUnits(Number(e.target.value))}/></label><label>Payment method<select className={fieldClass} value={method} onChange={e=>setMethod(e.target.value)}>{methods.map((m:string)=><option key={m}>{m}</option>)}</select></label>{method!=='CASH'&&<label>{method==='MPESA'?'Transaction code':'External approval reference'}<input className={fieldClass} value={reference} onChange={e=>setReference(e.target.value.toUpperCase())}/></label>}<p className="rounded-xl bg-slate-950 p-3 text-sm">Extension total: <b>{kesMinor(amountMinor)}</b>. The charge and exact payment commit in one transaction.</p><button disabled={!ratePlanId||units<1||amountMinor<=0||(method!=='CASH'&&!reference.trim())} className={primaryButtonClass}>Extend and pay</button></form></ActionDialog>
}

function ServiceMasterDialog({existing,onClose,onSave}:{existing?:any;onClose:()=>void;onSave:(v:any)=>Promise<void>}){
 const [v,setV]=useState({name:existing?.name||'',code:existing?.code||'',category:existing?.category||'SERVICE',price:Number(existing?.priceMinor||0)/100,taxBasisPoints:existing?.taxBasisPoints||0});
 return <ActionDialog title={existing?'Edit hotel service':'New hotel service'} onClose={onClose}><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void onSave({name:v.name,code:v.code.toUpperCase(),category:v.category,priceMinor:Math.round(v.price*100),taxBasisPoints:Number(v.taxBasisPoints),currency:'KES'})}}><label>Name<input required className={fieldClass} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Code<input required className={fieldClass} value={v.code} onChange={e=>setV({...v,code:e.target.value})}/></label><label>Category<input className={fieldClass} value={v.category} onChange={e=>setV({...v,category:e.target.value})}/></label><label>Price (KES)<input required min="0" step="0.01" type="number" className={fieldClass} value={v.price} onChange={e=>setV({...v,price:Number(e.target.value)})}/></label><label>Tax basis points<input min="0" max="10000" type="number" className={fieldClass} value={v.taxBasisPoints} onChange={e=>setV({...v,taxBasisPoints:Number(e.target.value)})}/></label><button className={primaryButtonClass}>Save service</button></form></ActionDialog>
}
function ReasonDialog({title,onClose,onSave}:{title:string;onClose:()=>void;onSave:(reason:string)=>Promise<void>}){const [reason,setReason]=useState('');return <ActionDialog title={title} onClose={onClose}><div className="space-y-3"><label>Reason<textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!reason.trim()} className={primaryButtonClass} onClick={()=>void onSave(reason.trim())}>Confirm reversal</button></div></ActionDialog>}
