import React, { useMemo, useState } from 'react';
import { useRuntime } from '../runtime/RuntimeProvider';
import { recordsOf, buttonClass } from './records';

export function NativeKDSView(){
  const runtime=useRuntime(); const orders=recordsOf(runtime.snapshot,'orders').filter(o=>!['COMPLETED','VOIDED'].includes(o.state));
  const [station,setStation]=useState<'BAR'|'KITCHEN'|'SERVICE'>('BAR');
  const tickets=useMemo(()=>orders.flatMap(order=>(order.items||[]).filter((i:any)=>i.stockFired===true&&i.productSnapshot?.routeTo===station&&i.courseStatus!=='SERVED').map((item:any)=>({order,item}))),[orders,station]);
  const next=(s:string)=>s==='FIRED'?'PREPARING':s==='PREPARING'?'READY':s==='READY'?'SERVED':'READY';
  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Bar / Kitchen Pass</h1><p className="text-sm text-slate-400">Item-specific preparation states from the native order record.</p></div><div className="flex gap-2">{(['BAR','KITCHEN','SERVICE'] as const).map(s=><button key={s} onClick={()=>setStation(s)} className={station===s?'rounded-xl bg-amber-400 px-4 py-2 font-bold text-slate-950':buttonClass}>{s}</button>)}</div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tickets.map(({order,item})=><article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between"><div><div className="text-xs font-mono text-amber-400">{order.orderNumber}</div><h2 className="mt-1 text-lg font-bold">{item.quantity} × {item.productName}</h2><p className="text-sm text-slate-400">{order.tabName||order.tableName||'Walk-in'}</p></div><span className="rounded-lg bg-slate-800 px-2 py-1 text-xs">{item.courseStatus}</span></div>{item.note&&<p className="mt-3 rounded-lg bg-slate-950 p-2 text-sm">Note: {item.note}</p>}<button className="mt-4 w-full rounded-xl bg-amber-400 px-4 py-3 font-bold text-slate-950" onClick={()=>void runtime.command('order.kds',{orderId:order.id,itemId:item.id,station,status:next(item.courseStatus)})}>{item.courseStatus==='READY'?'Mark served':item.courseStatus==='PREPARING'?'Mark ready':'Start preparing'}</button></article>)}{tickets.length===0&&<div className="col-span-full rounded-xl border border-dashed border-slate-700 p-10 text-center text-slate-500">No active {station.toLowerCase()} items.</div>}</div></div>;
}
