import React, { useState } from 'react';
import { useRuntime } from '../runtime/RuntimeProvider';
import type { Permission } from '../types/runtime';
import { recordsOf, recordOf, money, shortDate, fieldClass, buttonClass, primaryButtonClass } from './records';
import { ActionDialog } from './ActionDialog';
import { ManagerApprovalDialog } from './ManagerApprovalDialog';

export function NativeReconciliationView(){
  const runtime=useRuntime();
  const s=runtime.snapshot!;
  const receipts=recordsOf(s,'mpesaReceipts');
  const discrepancies=recordsOf(s,'mpesaDiscrepancies').slice().reverse();
  const [current,setCurrent]=useState<any>(null);
  const [statementAmount,setStatementAmount]=useState('');
  const [reference,setReference]=useState('');
  const [notes,setNotes]=useState('');
  const [error,setError]=useState('');
  const [resolving,setResolving]=useState<any>(null);
  const [outcome,setOutcome]=useState('STATEMENT_ERROR');
  const [resolution,setResolution]=useState('');
  const [busy,setBusy]=useState(false);
  const currentDiscrepancy=current?discrepancies.find(d=>d.receiptId===current.id&&d.status==='RESOLVED'):null;
  const openReceipt=(receipt:any)=>{const prior=discrepancies.find(d=>d.receiptId===receipt.id&&d.status==='RESOLVED');setCurrent(receipt);setStatementAmount(String(prior?.outcome==='ACCEPTED_VARIANCE'?prior.statementAmount:receipt.receivedAmount));setReference(prior?.statementReference||'');setNotes(prior?.resolution||'');setError('')};
  const recordReview=async(discrepancy:boolean)=>{
    if(!current)return;
    setBusy(true);setError('');
    try{
      if(discrepancy)await runtime.command('mpesa.discrepancy',{receiptId:current.id,statementAmount:Number(statementAmount),statementReference:reference,reason:notes});
      else await runtime.command('mpesa.reconcile',{receiptId:current.id,statementAmount:Number(statementAmount),statementReference:reference,notes});
      setCurrent(null);
    }catch(e){setError(String(e))}finally{setBusy(false)}
  };
  const resolveDiscrepancy=async()=>{
    if(!resolving)return;
    setBusy(true);setError('');
    try{await runtime.command('mpesa.discrepancy.resolve',{discrepancyId:resolving.id,outcome,resolution});setResolving(null);setResolution('')}
    catch(e){setError(String(e))}finally{setBusy(false)}
  };
  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
    <h1 className="text-2xl font-bold">M-Pesa reconciliation</h1>
    <p className="mb-5 text-sm text-slate-400">Compare each manually confirmed receipt with its statement entry. Variances stay open until a manager records a resolution.</p>
    <h2 className="mb-2 font-bold">Receipts</h2>
    <div className="space-y-2">{receipts.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-3"><div><b>{r.code}</b> - {r.account}<div className="text-xs text-slate-500">Received {money(r.receivedAmount)} - allocated {money(r.allocatedAmount)} - {shortDate(r.receivedAt)}</div></div><div className="flex items-center gap-2"><span className={r.reconciliationStatus.startsWith('RECONCILED')?'text-emerald-300':r.reconciliationStatus==='DISCREPANCY'?'text-rose-300':'text-amber-300'}>{r.reconciliationStatus}</span>{!r.reconciliationStatus.startsWith('RECONCILED')&&!discrepancies.some(d=>d.receiptId===r.id&&d.status==='OPEN')&&<button className={buttonClass} onClick={()=>openReceipt(r)}>Review statement</button>}</div></div>)}</div>
    <h2 className="mb-2 mt-7 font-bold">Statement discrepancies</h2>
    <div className="space-y-2">{discrepancies.map(d=><article key={d.id} className="rounded-xl border border-rose-900/60 bg-rose-950/20 p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{d.receiptCode}</b> - {d.account}<div className="text-sm">Receipt {money(d.receivedAmount)} - statement {money(d.statementAmount)} - variance {money(d.variance)}</div><div className="text-xs text-slate-400">{d.statementReference} - {d.reason} - {d.status}{d.resolution?` - ${d.outcome}: ${d.resolution}`:''}</div></div>{d.status==='OPEN'&&<button className={buttonClass} onClick={()=>{setResolving(d);setOutcome('STATEMENT_ERROR');setResolution('');setError('')}}>Resolve</button>}</div></article>)}{discrepancies.length===0&&<p className="text-sm text-slate-500">No statement discrepancies recorded.</p>}</div>
    {current&&<ActionDialog title={`Review ${current.code}`} onClose={()=>setCurrent(null)}><div className="space-y-3"><p className="text-sm text-slate-400">Receipt amount: {money(current.receivedAmount)}. A mismatch creates a separate audit record and needs a manager resolution.</p><label>Statement amount<input className={fieldClass} type="number" min="0" step="0.01" value={statementAmount} onChange={e=>setStatementAmount(e.target.value)}/></label><label>Statement reference<input className={fieldClass} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Review notes / discrepancy reason<textarea className={fieldClass} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p role="alert" className="text-rose-300">{error}</p>}<div className="flex flex-wrap gap-2"><button className={primaryButtonClass} disabled={busy||!reference.trim()||!notes.trim()||Number(statementAmount)!==Number(current.receivedAmount)&&currentDiscrepancy?.outcome!=='ACCEPTED_VARIANCE'} onClick={()=>void recordReview(false)}>{currentDiscrepancy?.outcome==='ACCEPTED_VARIANCE'?'Reconcile accepted variance':'Reconcile matching amount'}</button><button className={buttonClass} disabled={busy||!reference.trim()||!notes.trim()||Number(statementAmount)===Number(current.receivedAmount)||!!currentDiscrepancy} onClick={()=>void recordReview(true)}>Record discrepancy</button></div></div></ActionDialog>}
    {resolving&&<ActionDialog title={`Resolve ${resolving.receiptCode} discrepancy`} onClose={()=>setResolving(null)}><div className="space-y-3"><p className="text-sm text-slate-400">Receipt {money(resolving.receivedAmount)} - statement {money(resolving.statementAmount)} - variance {money(resolving.variance)}. Resolution does not alter either recorded amount.</p><label>Outcome<select className={fieldClass} value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="STATEMENT_ERROR">Statement entry was wrong; reconcile the receipt amount</option><option value="ACCEPTED_VARIANCE">Accept the documented statement variance</option></select></label><label>Resolution note<textarea className={fieldClass} value={resolution} onChange={e=>setResolution(e.target.value)}/></label>{error&&<p role="alert" className="text-rose-300">{error}</p>}<button className={primaryButtonClass} disabled={busy||!resolution.trim()} onClick={()=>void resolveDiscrepancy()}>Save resolution</button></div></ActionDialog>}
  </div>
}

export function NativeCloseDayView(){const runtime=useRuntime();const s=runtime.snapshot!;const tills=recordsOf(s,'tillSessions');const open=tills.find(t=>t.status==='OPEN');const closed=tills.filter(t=>t.status==='CLOSED').slice().reverse();const [modal,setModal]=useState<string|null>(null);const [amount,setAmount]=useState(0);const [openingFloat,setOpeningFloat]=useState(Number(recordsOf(s,'tillPolicy')[0]?.defaultOpeningFloat||0));const [reason,setReason]=useState('');const [cashType,setCashType]=useState('OUT');const [approval,setApproval]=useState<{permission:Permission;target:string;run:(t:string)=>Promise<void>}|null>(null);const perms=s.actor.permissions;const protect=(permission:Permission,target:string,fn:(token?:string)=>Promise<void>)=>perms.includes(permission)?void fn():setApproval({permission,target,run:async t=>fn(t)});return <div className="h-full overflow-auto bg-slate-950 p-5 text-white"><div className="mb-5"><h1 className="text-2xl font-bold">Shift & day close</h1><p className="text-sm text-slate-400">Resolve tabs, reconcile, count cash, close, back up and synchronize.</p></div>{open?<div className="rounded-2xl border border-amber-700/40 bg-amber-950/20 p-5"><div className="grid gap-3 sm:grid-cols-4"><Metric label="Opening float" value={money(open.openingFloat)}/><Metric label="Cash sales" value={money(open.cashSalesTotal)}/><Metric label="Paid in / out" value={`${money(open.cashPaidIn)} / ${money(open.cashPaidOut)}`}/><Metric label="Expected drawer" value={money(open.expectedCashInDrawer)}/></div><div className="mt-4 flex flex-wrap gap-2"><button className={buttonClass} onClick={()=>{setAmount(0);setReason('');setModal('MOVEMENT')}}>Paid in / out</button><button className={primaryButtonClass} onClick={()=>{setAmount(Number(open.expectedCashInDrawer));setReason('');setModal('CLOSE')}}>Count & close till</button></div></div>:<div className="rounded-xl border border-dashed border-slate-700 p-6 text-slate-400">No open till. Open one from Business Admin before service.</div>}
<div className="mt-6 flex flex-wrap gap-2"><button className={buttonClass} onClick={()=>void runtime.backup()}>Create backup</button><button className={buttonClass} onClick={()=>void runtime.sync()}>Synchronize</button></div><h2 className="mb-2 mt-7 font-bold">Closed shifts</h2>{closed.map(t=><div key={t.id} className="mb-2 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-3"><div><b>{shortDate(t.closedAt)}</b><div className="text-xs text-slate-500">Cash variance {money(t.cashVariance)} · counted {money(t.countedCashAtClose)}</div></div><button className={buttonClass} onClick={()=>void runtime.command('closeDay.generate',{tillId:t.id})}>Generate close-day report</button></div>)}
{modal==='MOVEMENT'&&open&&<ActionDialog title="Cash paid in / out" onClose={()=>setModal(null)}><div className="space-y-3"><select className={fieldClass} value={cashType} onChange={e=>setCashType(e.target.value)}><option value="IN">Paid in / float top-up</option><option value="OUT">Paid out / cash drop</option></select><input className={fieldClass} type="number" min="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><textarea className={fieldClass} placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><button className={primaryButtonClass} onClick={()=>protect('till.cash_movement',open.id,async token=>{await runtime.command('till.cashMovement',{tillId:open.id,type:cashType,amount,reason,approvalToken:token});setModal(null)})}>Record movement</button></div></ActionDialog>}
{modal==='CLOSE'&&open&&<ActionDialog title="Blind drawer count" onClose={()=>setModal(null)}><div className="space-y-3"><p className="text-sm text-slate-400">Enter the actual physical cash. ServOS compares it to the expected drawer in the native transaction.</p><input className={fieldClass} type="number" min="0" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><textarea className={fieldClass} placeholder="Variance reason if count differs" value={reason} onChange={e=>setReason(e.target.value)}/><button className={primaryButtonClass} onClick={()=>{const doClose=async(token?:string)=>{await runtime.command('till.close',{tillId:open.id,countedCash:amount,reason,approvalToken:token});setModal(null)};if(Number(amount)===Number(open.expectedCashInDrawer))void doClose();else protect('till.override_variance',open.id,doClose)}}>Reconcile & close</button></div></ActionDialog>}
{approval&&<ManagerApprovalDialog permission={approval.permission} target={approval.target} onClose={()=>setApproval(null)} onApproved={approval.run}/>}</div>}

export function NativeReportsView(){const runtime=useRuntime();const reports=recordsOf(runtime.snapshot,'closeDayReports').slice().reverse();return <div className="h-full overflow-auto bg-slate-950 p-5 text-white"><h1 className="text-2xl font-bold">Reports</h1><p className="mb-5 text-sm text-slate-400">Persisted close-day reports from the same native transaction records.</p>{reports.map(r=><article key={r.id} className="mb-4 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="text-xs font-mono text-amber-400">{shortDate(r.generatedAt)}</div><h2 className="font-bold">Shift {r.tillSessionId?.slice(0,8)}</h2></div><div className="text-right"><div className="text-xl font-bold">{money(r.sales?.gross)}</div><div className="text-xs text-slate-500">Gross sales</div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Net" value={money(r.sales?.net)}/><Metric label="VAT / levy" value={`${money(r.sales?.vat)} / ${money(r.sales?.levy)}`}/><Metric label="Cash / M-Pesa / Card" value={`${money(r.tenders?.cash)} / ${money(r.tenders?.mpesa)} / ${money(r.tenders?.card)}`}/><Metric label="Gross profit" value={money(r.margin?.grossProfit)}/><Metric label="Discounts / comps" value={`${money(r.adjustments?.discounts)} / ${money(r.adjustments?.comps)}`}/><Metric label="Refunds" value={money(r.adjustments?.refunds)}/><Metric label="COGS / waste" value={`${money(r.inventory?.cogs)} / ${money(r.inventory?.waste)}`}/><Metric label="Cash variance" value={money(r.cash?.variance)}/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div><b className="text-sm">Top products</b><div className="mt-2 text-sm text-slate-400">{(r.topProducts||[]).map((x:any)=>`${x.name} (${x.quantity})`).join(' · ')||'No products'}</div></div><div><b className="text-sm">Staff sales</b><div className="mt-2 text-sm text-slate-400">{(r.staffSales||[]).map((x:any)=>`${x.name}: ${money(x.sales)}`).join(' · ')||'No staff sales'}</div></div></div></article>)}{reports.length===0&&<div className="rounded-xl border border-dashed border-slate-700 p-8 text-center text-slate-500">Generate a report after closing a till.</div>}</div>}

export function NativeAdminView(){const runtime=useRuntime();const s=runtime.snapshot!;const perms=s.actor.permissions;const staff=runtime.status?.staff||[];const till=recordsOf(s,'tillSessions').find(t=>t.status==='OPEN');const policy=recordsOf(s,'tillPolicy')[0]||{};const [modal,setModal]=useState<string|null>(null);const [form,setForm]=useState({name:'',jobTitle:'Bartender',role:'Server',pin:'',staffId:'',newRole:'Server',float:Number(policy.defaultOpeningFloat||0)});const [approval,setApproval]=useState<{permission:Permission;target?:string;run:(t:string)=>Promise<void>}|null>(null);const protect=(permission:Permission,target:string|undefined,fn:(token?:string)=>Promise<void>)=>perms.includes(permission)?void fn():setApproval({permission,target,run:async t=>fn(t)});return <div className="h-full overflow-auto bg-slate-950 p-5 text-white"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Business Admin</h1><p className="text-sm text-slate-400">{s.actor.name} · {s.actor.role} · terminal {s.terminalId?.slice(0,8)}</p></div><div className="flex gap-2"><button className={buttonClass} onClick={()=>void runtime.sync()}>Sync ({s.pendingCount})</button><button className={buttonClass} onClick={()=>void runtime.backup()}>Backup</button><button className={buttonClass} onClick={()=>void runtime.lock()}>Change staff / lock</button></div></div>
<section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">Till</h2>{till?<p className="mt-2 text-sm text-slate-400">Open by {till.employeeName}. Expected drawer {money(till.expectedCashInDrawer)}. Close it from Shift & Day Close.</p>:<div className="mt-3 flex gap-3"><input className={fieldClass+' max-w-xs'} type="number" min="0" value={form.float} onChange={e=>setForm({...form,float:Number(e.target.value)})}/><button className={primaryButtonClass} onClick={()=>void runtime.command('till.open',{floatAmount:form.float})}>Open till</button></div>}</section>
<section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between"><div><h2 className="font-bold">Staff access</h2><p className="text-xs text-slate-500">Authority comes from each person's local PIN session.</p></div>{perms.includes('staff.create')&&<button className={buttonClass} onClick={()=>setModal('CREATE')}>Add staff</button>}</div><div className="mt-3 space-y-2">{staff.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-950 p-3"><div><b>{x.name}</b><div className="text-xs text-slate-500">{x.role}</div></div><div className="flex gap-1">{perms.includes('staff.reset_pin')&&<button className={buttonClass} onClick={()=>{setForm({...form,staffId:x.id,pin:''});setModal('PIN')}}>Reset PIN</button>}{perms.includes('staff.change_role')&&<button className={buttonClass} onClick={()=>{setForm({...form,staffId:x.id,newRole:x.role});setModal('ROLE')}}>Role</button>}{perms.includes('staff.deactivate')&&x.id!==s.actor.id&&<button className={buttonClass} onClick={()=>protect('staff.deactivate',x.id,async token=>{await runtime.command('staff.deactivate',{staffId:x.id,approvalToken:token})})}>Deactivate</button>}</div></div>)}</div></section>
<section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">System health</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><Metric label="Installation" value={s.installationStage}/><Metric label="Pending sync" value={String(s.pendingCount)}/><Metric label="Last backup" value={shortDate(s.lastBackup)}/></div></section>
{modal==='CREATE'&&<ActionDialog title="Create staff account" onClose={()=>setModal(null)}><div className="space-y-3"><input className={fieldClass} placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={fieldClass} placeholder="Job title" value={form.jobTitle} onChange={e=>setForm({...form,jobTitle:e.target.value})}/><select className={fieldClass} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Server</option><option>Manager</option>{s.actor.role==='Admin'&&<option>Admin</option>}</select><input className={fieldClass} type="password" inputMode="numeric" placeholder="PIN" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,'').slice(0,12)})}/><button className={primaryButtonClass} onClick={()=>void runtime.command('staff.create',{name:form.name,jobTitle:form.jobTitle,role:form.role,pin:form.pin}).then(()=>setModal(null))}>Create</button></div></ActionDialog>}
{modal==='PIN'&&<ActionDialog title="Reset staff PIN" onClose={()=>setModal(null)}><div className="space-y-3"><input className={fieldClass} type="password" inputMode="numeric" placeholder="New PIN" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,'').slice(0,12)})}/><button className={primaryButtonClass} onClick={()=>protect('staff.reset_pin',form.staffId,async token=>{await runtime.command('staff.resetPin',{staffId:form.staffId,pin:form.pin,approvalToken:token});setModal(null)})}>Reset PIN</button></div></ActionDialog>}
{modal==='ROLE'&&<ActionDialog title="Change access role" onClose={()=>setModal(null)}><div className="space-y-3"><select className={fieldClass} value={form.newRole} onChange={e=>setForm({...form,newRole:e.target.value})}><option>Server</option><option>Manager</option><option>Admin</option></select><button className={primaryButtonClass} onClick={()=>void runtime.command('staff.changeRole',{staffId:form.staffId,role:form.newRole}).then(()=>setModal(null))}>Change role</button></div></ActionDialog>}
{approval&&<ManagerApprovalDialog permission={approval.permission} target={approval.target} onClose={()=>setApproval(null)} onApproved={approval.run}/>}</div>}

export function NativeRefundsView(){const runtime=useRuntime();const s=runtime.snapshot!;const payments=recordsOf(s,'payments').slice().reverse();const [current,setCurrent]=useState<any>(null);const [amount,setAmount]=useState(0);const [reason,setReason]=useState('');const [externalReference,setExternal]=useState('');const [approval,setApproval]=useState<{permission:Permission;target:string;run:(t:string)=>Promise<void>}|null>(null);const perms=s.actor.permissions;const refund=async(token?:string)=>{await runtime.command('payment.refund',{paymentId:current.id,amount,reason,externalReference,approvalToken:token});setCurrent(null)};return <div className="h-full overflow-auto bg-slate-950 p-5 text-white"><h1 className="text-2xl font-bold">Payments & refunds</h1><p className="mb-5 text-sm text-slate-400">Refunds reverse money and accounting. Ingredient stock is not automatically restored.</p>{payments.map(p=><div key={p.id} className="mb-2 flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-3"><div><b>{p.tenderType} · {money(p.amount)}</b><div className="text-xs text-slate-500">{p.referenceNumber} · {shortDate(p.occurredAt)} · {p.cashierName}</div></div><button className={buttonClass} onClick={()=>{setCurrent(p);setAmount(Number(p.amount));setReason('');setExternal('')}}>Refund</button></div>)}{current&&<ActionDialog title="Refund payment" onClose={()=>setCurrent(null)}><div className="space-y-3"><input className={fieldClass} type="number" min="0.01" max={current.amount} value={amount} onChange={e=>setAmount(Number(e.target.value))}/><textarea className={fieldClass} placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/>{current.tenderType!=='CASH'&&<input className={fieldClass} placeholder="External reversal / refund reference" value={externalReference} onChange={e=>setExternal(e.target.value)}/>}<button className={primaryButtonClass} onClick={()=>perms.includes('order.refund')?void refund():setApproval({permission:'order.refund',target:current.id,run:async t=>refund(t)})}>Post refund</button></div></ActionDialog>}{approval&&<ManagerApprovalDialog permission={approval.permission} target={approval.target} onClose={()=>setApproval(null)} onApproved={approval.run}/>}</div>}
const Metric=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-slate-950 p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-bold">{value}</div></div>;
