import React,{useEffect,useMemo,useState} from 'react';
import {FileDown,FileSpreadsheet,ShieldCheck,Upload} from 'lucide-react';
import {useRuntime} from '../runtime/RuntimeProvider';
import type {ImportApplyPlan,ImportBatchDetail,ImportBatchSummary,ImportTemplateKey,StageImportInput} from '../types/imports';
import {IMPORT_TEMPLATES,IMPORT_TEMPLATE_GROUPS} from './importTemplates';
import { FriendlyImport } from './FriendlyImport';
import {ActionDialog} from './ActionDialog';
import {buttonClass,primaryButtonClass} from './records';

// SERVOS_PATCH_04_CONTROLLED_IMPORT
const stateClass=(s:string)=>['READY','APPLIED','CREATE'].includes(s)?'text-emerald-300':['UPDATE'].includes(s)?'text-sky-300':['NO_CHANGE','CANCELLED','SUPERSEDED'].includes(s)?'text-slate-400':'text-amber-300';
const when=(v:string)=>new Date(v).toLocaleString();
const download=(name:string,csv:string)=>{const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(u),1000)};

export function NativeImportCenterView(){
  const runtime=useRuntime();const perms=runtime.snapshot!.actor.permissions;
  const canStage=perms.includes('data.import.stage');const canExecute=perms.includes('data.import.execute');
  const [templateKey,setTemplateKey]=useState<ImportTemplateKey>('products');
  const [batches,setBatches]=useState<ImportBatchSummary[]>([]);const [detail,setDetail]=useState<ImportBatchDetail|null>(null);
  const [plan,setPlan]=useState<ImportApplyPlan|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const selected=useMemo(()=>IMPORT_TEMPLATES.find(x=>x.key===templateKey)!,[templateKey]);
  const load=async()=>setBatches(await runtime.importBatches());
  useEffect(()=>{void load().catch(e=>setMessage(String(e)))},[]);
  const stageMapped=async(input:StageImportInput)=>{setBusy(true);setMessage('');try{const r=await runtime.stageImport(input);setDetail(r);setPlan(null);await load();}catch(e){setMessage(String(e));throw e;}finally{setBusy(false)}};
  const stage=async(file:File)=>{setBusy(true);setMessage('');try{const r=await runtime.stageImport({templateKey,fileName:file.name,csvText:await file.text()});setDetail(r);setPlan(null);await load();setMessage(r.invalidCount?`${r.invalidCount} invalid row(s). Correct the CSV and stage a new batch.`:`${r.rowCount} row(s) staged. Generate a dry run before application.`)}catch(e){setMessage(String(e))}finally{setBusy(false)}};
  const review=async(id:string)=>{setBusy(true);try{setDetail(await runtime.importBatch(id));setPlan(null)}catch(e){setMessage(String(e))}finally{setBusy(false)}};
  const dryRun=async()=>{if(!detail)return;setBusy(true);try{const r=await runtime.planImport(detail.id);setPlan(r);setMessage(r.status==='READY'?'Dry run ready for review.':'Dry run contains blocked or conflicting steps.')}catch(e){setMessage(String(e))}finally{setBusy(false)}};
  const apply=async()=>{if(!plan)return;setBusy(true);try{const r=await runtime.applyImport(plan.id);setPlan(r);setDetail(null);await load();setMessage('Controlled import applied through ServOS domain commands.')}catch(e){setMessage(String(e));try{setPlan(await runtime.importPlan(plan.id))}catch{}}finally{setBusy(false)}};
  const cancel=async()=>{if(!detail)return;setBusy(true);try{await runtime.cancelImport(detail.id);setDetail(null);setPlan(null);await load()}catch(e){setMessage(String(e))}finally{setBusy(false)}};

  return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Bring In Existing Data</h1><p className="mt-1 max-w-3xl text-sm text-slate-400">Stage → validate → dry run → review → controlled application through normal ServOS commands.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-700/40 bg-emerald-950/20 px-3 py-2 text-xs text-emerald-200"><ShieldCheck className="h-4 w-4"/>No direct business-record writes</div></div>
    {canStage&&<FriendlyImport live={runtime.snapshot?.installationStage==='LIVE'} busy={busy} onStage={stageMapped}/>}
    <details className="mt-5"><summary className="cursor-pointer text-sm text-amber-200">Advanced templates and canonical CSV</summary>
    <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1"><span className="mb-1 block text-xs font-bold text-slate-400">Template</span><select className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2" value={templateKey} onChange={e=>setTemplateKey(e.target.value as ImportTemplateKey)}>{IMPORT_TEMPLATES.map(t=><option key={t.key} value={t.key}>{t.group} · {t.label}</option>)}</select></label><button className={buttonClass} onClick={()=>download(selected.fileName,selected.csv)}><FileDown className="mr-2 inline h-4 w-4"/>Download {selected.fileName}</button>{canStage&&<label className={primaryButtonClass+' cursor-pointer'}><Upload className="mr-2 inline h-4 w-4"/>{busy?'Working…':'Stage CSV'}<input className="hidden" type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void stage(file);e.currentTarget.value=''}}/></label>}</div><p className="mt-3 text-xs text-slate-500">Canonical headers: {selected.headers.join(', ')}</p>{message&&<p role="status" className="mt-3 rounded-xl bg-slate-950 p-3 text-xs text-slate-300">{message}</p>}</section>
    <section className="mt-5"><h2 className="mb-1 font-bold">Template library</h2><p className="mb-3 text-xs text-slate-500">Dependency order: business → stock locations → outlets → inventory stock masters → products. Room types, rooms, rate plans, hotel services, asset categories and assets now apply through their native domain commands.</p>{IMPORT_TEMPLATE_GROUPS.map(g=><div className="mb-4" key={g}><div className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">{g}</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{IMPORT_TEMPLATES.filter(t=>t.group===g).map(t=><button key={t.key} onClick={()=>download(t.fileName,t.csv)} className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-900 p-3 text-left"><span><b className="text-sm">{t.label}</b><span className="mt-1 block font-mono text-[11px] text-slate-500">{t.fileName}</span></span><FileSpreadsheet className="h-4 w-4 text-slate-500"/></button>)}</div></div>)}</section>
    </details>
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between"><div><h2 className="font-bold">Staged batches</h2><p className="text-xs text-slate-500">Admins execute. Managers may stage and dry-run.</p></div><button className={buttonClass} onClick={()=>void load()}>Refresh</button></div><div className="mt-3 overflow-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="text-slate-500"><tr><th className="p-2">File</th><th className="p-2">Template</th><th className="p-2">Status</th><th className="p-2">Rows</th><th className="p-2">Created</th><th className="p-2"></th></tr></thead><tbody>{batches.map(b=><tr key={b.id} className="border-t border-slate-800"><td className="p-2">{b.fileName}</td><td className="p-2 font-mono">{b.templateKey}</td><td className={'p-2 font-bold '+stateClass(b.status)}>{b.status}</td><td className="p-2">{b.validCount}/{b.rowCount}</td><td className="p-2 text-slate-500">{when(b.createdAt)}</td><td className="p-2 text-right"><button className={buttonClass} onClick={()=>void review(b.id)}>Review</button></td></tr>)}</tbody></table></div></section>
    {detail&&<ActionDialog title={`Import batch · ${detail.fileName}`} onClose={()=>{setDetail(null);setPlan(null)}}><div className="space-y-4 text-sm">
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Status" value={detail.status}/><Metric label="Rows" value={String(detail.rowCount)}/><Metric label="Valid" value={String(detail.validCount)}/><Metric label="Invalid" value={String(detail.invalidCount)}/></div>
      <div className="max-h-52 overflow-auto rounded-xl border border-slate-800"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-950 text-slate-500"><tr><th className="p-2">Row</th><th className="p-2">External ID</th><th className="p-2">Validation</th></tr></thead><tbody>{detail.rows.map(r=><tr key={r.rowNumber} className="border-t border-slate-800"><td className="p-2">{r.rowNumber}</td><td className="p-2 font-mono">{r.externalId||'—'}</td><td className="p-2">{r.errors.length?<span className="text-rose-300">{r.errors.join(' · ')}</span>:<span className="text-emerald-300">Valid</span>}</td></tr>)}</tbody></table></div>
      {detail.status==='READY'&&<button className={primaryButtonClass} disabled={busy} onClick={()=>void dryRun()}>Generate dry-run plan</button>}
      {plan&&<div className="rounded-xl border border-slate-700 p-3"><div className="flex flex-wrap justify-between gap-2"><div><b>Plan <span className={stateClass(plan.status)}>{plan.status}</span></b><div className="text-xs text-slate-500">{plan.summary.create} create · {plan.summary.update} update · {plan.summary.noChange} no change · {plan.summary.blocked} blocked · {plan.summary.conflict} conflict</div></div>{canExecute&&plan.status==='READY'&&<button className={primaryButtonClass} disabled={busy} onClick={()=>void apply()}>Apply reviewed plan</button>}</div><div className="mt-3 max-h-72 overflow-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="p-2">Step</th><th className="p-2">Decision</th><th className="p-2">Target</th><th className="p-2">Reason</th></tr></thead><tbody>{plan.steps.map(s=><tr key={s.stepIndex} className="border-t border-slate-800 align-top"><td className="p-2">{s.stepIndex}</td><td className={'p-2 font-bold '+stateClass(s.action)}>{s.action}</td><td className="p-2 font-mono">{s.targetCollection||'—'}</td><td className="p-2 text-slate-400">{s.reason}{s.error&&<div className="text-rose-300">{s.error}</div>}</td></tr>)}</tbody></table></div></div>}
      <div className="flex justify-between gap-2"><span className="text-xs text-slate-500">SHA-256 {detail.sourceHash.slice(0,16)}…</span>{canStage&&!['CANCELLED','APPLIED'].includes(detail.status)&&<button className={buttonClass} onClick={()=>void cancel()}>Cancel batch</button>}</div>
    </div></ActionDialog>}
  </div>;
}
const Metric=({label,value}:{label:string;value:string})=><div className="rounded-xl bg-slate-950 p-3"><div className="text-[11px] text-slate-500">{label}</div><div className="font-semibold">{value}</div></div>;
