import React, { useEffect, useMemo, useState } from 'react';
import { CreditCard, Flame, Plus, Minus, Search, ShieldAlert, Split, Trash2 } from 'lucide-react';
import { useRuntime } from '../runtime/RuntimeProvider';
import type { Permission } from '../types/runtime';
import { recordsOf, money, fieldClass, buttonClass, primaryButtonClass } from './records';
import { ManagerApprovalDialog } from './ManagerApprovalDialog';
import { ActionDialog } from './ActionDialog';
import { NativeReceiptDialog } from './NativeReceiptDialog';
import { barcodeEquals, useBarcodeScanner } from '../hooks/useBarcodeScanner';

export function NativePOSView(){
  const runtime=useRuntime(); const snapshot=runtime.snapshot!; const perms=snapshot.actor.permissions;
  const outlets=recordsOf(snapshot,'outlets'); const products=recordsOf(snapshot,'products'); const tables=recordsOf(snapshot,'tables'); const orders=recordsOf(snapshot,'orders');
  const openOrders=orders.filter(o=>!['COMPLETED','VOIDED'].includes(o.state));
  const [outletId,setOutletId]=useState(outlets[0]?.id||''); const [activeId,setActiveId]=useState(openOrders[0]?.id||''); const active=openOrders.find(o=>o.id===activeId)||openOrders[0];
  const [query,setQuery]=useState(''); const [modal,setModal]=useState<{kind:string;data?:any}|null>(null); const [notice,setNotice]=useState(''); const [scannerTest,setScannerTest]=useState(false); const [lastTestScan,setLastTestScan]=useState('');
  const [printerJobs,setPrinterJobs]=useState<any[]>([]);
  const [approval,setApproval]=useState<{permission:Permission;target?:string;run:(token:string)=>Promise<void>}|null>(null);
  const refreshPrinterJobs=async()=>{try{setPrinterJobs(await runtime.printerJobs())}catch{/* Session expiry is handled by the runtime shell. */}};
  useEffect(()=>{void refreshPrinterJobs()},[runtime.session?.token]);
  const visible=useMemo(()=>products.filter(p=>(!outletId||p.outletIds?.includes(outletId)) && [p.name,p.code,p.barcode,p.category].join(' ').toLowerCase().includes(query.toLowerCase())),[products,outletId,query]);
  const run=async(op:string,payload:any={},version?:number)=>{setNotice('');try{await runtime.command(op,payload,version);setNotice('Saved locally.');}catch(e){setNotice(String(e));throw e;}};
  const protectedRun=(permission:Permission,target:string|undefined,fn:(token?:string)=>Promise<void>)=>{if(perms.includes(permission))void fn();else setApproval({permission,target,run:async token=>fn(token)});};
  const createTab=async()=>{if(!outletId)return;const name=`Walk-in ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;const r=await runtime.command('order.create',{outletId,name});setActiveId(r.recordIds.find(Boolean)||'');};
  const createTableOrder=async(table:any)=>{const r=await runtime.command('order.create',{outletId:table.outletId,tableId:table.id,name:`Table ${table.label}`});setActiveId(r.recordIds.find(Boolean)||'');};
  const addProduct=(product:any)=>{if((product.portions?.length||0)>0||(product.modifiers?.length||0)>0)setModal({kind:'CONFIG',data:{product,quantity:1,portionId:product.portions?.[0]?.id||'',modifierIds:[]}});else if(active)void run('order.addItem',{orderId:active.id,productId:product.id,quantity:1});};
  useBarcodeScanner({enabled:modal===null,onScan:barcode=>{
    if(scannerTest){setLastTestScan(barcode);setScannerTest(false);setQuery('');setNotice(`Scanner test received ${barcode}. No sale or stock change was made.`);return;}
    const matches=products.filter((p:any)=>(!outletId||p.outletIds?.includes(outletId))&&(barcodeEquals(p.barcode,barcode)||barcodeEquals(p.code,barcode)));
    setQuery('');
    if(matches.length>1){setNotice(`Barcode ${barcode} matches more than one sellable. Resolve the duplicate catalog assignment before scanning sales.`);return;}
    if(!matches.length){setNotice(`Barcode ${barcode} is not assigned to a sellable in this service area.`);return;}
    if(!active){setNotice(`Scanned ${matches[0].name}. Open or select a tab before adding it.`);return;}
    setNotice(`Scanned ${matches[0].name}.`);
    addProduct(matches[0]);
  }});
  const updateItem=(item:any,quantity:number)=>quantity<=0?void run('order.removeItem',{orderId:active.id,itemId:item.id}):void run('order.updateItem',{orderId:active.id,itemId:item.id,quantity});
  const balance=active?Math.max(0,Number(active.grandTotal||0)-Number(active.amountPaid||0)):0;
  const finishPayment=async(p:any)=>{
    if(!active)return;
    const order={...active,amountPaid:Number(active.amountPaid||0)+Number(p.amount||0),completedAt:new Date().toISOString()};
    try{
      await runtime.command('payment.record',{orderId:active.id,...p});
      setModal({kind:'RECEIPT',data:{order,payment:{tenderType:p.method,amount:p.amount,receiptRef:p.mpesa?.code||p.cardAuthCode,cashTendered:p.cashTendered,changeDue:p.method==='CASH'?Math.max(0,Number(p.cashTendered||0)-Number(p.amount||0)):0}}});
    }catch(e){setNotice(String(e))}
  };
  const finishSplit=async(payments:any[])=>{
    if(!active)return;
    const amount=payments.reduce((sum,p)=>sum+Number(p.amount||0),0);
    const order={...active,amountPaid:Number(active.amountPaid||0)+amount,completedAt:new Date().toISOString()};
    try{
      await runtime.command('payment.split',{orderId:active.id,payments});
      setModal({kind:'RECEIPT',data:{order,payment:{tenderType:payments.map(p=>p.method).join(' + '),amount,receiptRef:payments.map(p=>p.mpesa?.code||p.cardAuthCode).filter(Boolean).join(', ')||undefined,cashTendered:payments.filter(p=>p.method==='CASH').reduce((sum,p)=>sum+Number(p.cashTendered||0),0)||undefined}}});
    }catch(e){setNotice(String(e))}
  };

  return <div className="grid h-full min-h-0 grid-cols-1 xl:grid-cols-[1fr_430px] bg-slate-950 text-white">
    <section className="min-h-0 overflow-auto p-4">
      <div className="mb-2 flex flex-wrap items-center gap-2"><select className={fieldClass+' max-w-xs'} value={outletId} onChange={e=>setOutletId(e.target.value)}>{outlets.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><button className={primaryButtonClass} onClick={()=>void createTab()}>Quick tab</button><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input data-barcode-capture="true" className={fieldClass+' pl-9'} placeholder="Search or scan barcode" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className={buttonClass} onClick={()=>{setLastTestScan('');setScannerTest(true);setNotice('Scan any barcode now. This test will not change a sale or stock count.')}}>{scannerTest?'Waiting for scan…':'Test scanner'}</button></div>
      <p className="mb-4 text-xs text-slate-500">USB keyboard-wedge scanner ready when connected. {lastTestScan&&<>Last test: <span className="font-mono text-emerald-300">{lastTestScan}</span></>}</p>
      <div className="mb-5 flex gap-2 overflow-x-auto pb-2">{tables.filter(t=>t.outletId===outletId).map(t=><button key={t.id} disabled={t.state!=='AVAILABLE'&&t.state!=='CLEANING'} onClick={()=>t.state==='CLEANING'?void run('table.ready',{tableId:t.id},recordVersion(snapshot,'tables',t.id)):void createTableOrder(t)} className={`min-w-24 rounded-xl border p-3 text-left ${t.state==='AVAILABLE'?'border-emerald-700 bg-emerald-950/40':t.state==='CLEANING'?'border-amber-700 bg-amber-950/40':'border-slate-800 bg-slate-900 opacity-50'}`}><b className="block">{t.label}</b><span className="text-xs text-slate-400">{t.state}</span></button>)}</div>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{visible.map(p=><button key={p.id} disabled={!active} onClick={()=>addProduct(p)} className="rounded-xl border border-slate-800 bg-slate-900 p-4 text-left hover:border-amber-500 disabled:opacity-40"><div className="text-xs uppercase text-slate-500">{p.category||p.routeTo}</div><div className="mt-1 font-bold">{p.name}</div><div className="mt-2 text-amber-300">{money(p.price)}</div>{p.favorite&&<div className="mt-2 text-xs text-amber-400">★ Favorite</div>}</button>)}</div>
    </section>
    <aside className="min-h-0 overflow-auto border-l border-slate-800 bg-slate-900/70 p-4">
      {printerJobs.length>0&&<section aria-label="Pending printer jobs" className="mb-4 rounded-xl border border-amber-700/50 bg-amber-950/20 p-3"><h2 className="font-bold text-amber-200">Receipt jobs needing attention</h2><div className="mt-2 space-y-2">{printerJobs.map((job:any)=><div key={job.jobId} className="rounded-lg bg-slate-950 p-2 text-xs"><b>{job.orderId==='PRINTER_TEST'?'Printer test':`Order ${job.orderId}`}: {job.state}</b><p className="mt-1 text-slate-400">{job.message}</p>{job.state==='QUEUED'&&<button className={buttonClass+' mt-2'} onClick={()=>void runtime.retryPrinterJob(job.jobId).then(refreshPrinterJobs).catch(e=>setNotice(String(e)))}>Retry print</button>}{job.state==='DELIVERY_UNCERTAIN'&&<button className={buttonClass+' mt-2'} onClick={()=>void runtime.retryPrinterJob(job.jobId,true).then(refreshPrinterJobs).catch(e=>setNotice(String(e)))}>Reprint (may duplicate)</button>}</div>)}</div></section>}
      <div className="mb-4"><div className="text-xs font-mono text-amber-400">ACTIVE TAB</div><select className={fieldClass} value={active?.id||''} onChange={e=>setActiveId(e.target.value)}><option value="">Select order</option>{openOrders.map(o=><option key={o.id} value={o.id}>{o.tabName||o.orderNumber} · {money(o.grandTotal)}</option>)}</select></div>
      {!active?<div className="rounded-xl border border-dashed border-slate-700 p-8 text-center text-slate-400">Open a quick tab or select an available table.</div>:<>
        <div className="space-y-2">{(active.items||[]).map((item:any)=><div key={item.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex justify-between gap-3"><div><b>{item.productName}</b><div className="text-xs text-slate-500">{item.portionSnapshot?.name||''}{item.modifiers?.length?` · ${item.modifiers.map((m:any)=>m.name).join(', ')}`:''}</div><div className="text-xs text-slate-500">{item.courseStatus}</div></div><div className="text-right"><b>{money(item.lineTotal)}</b>{item.comped&&<div className="text-xs text-purple-300">COMP</div>}</div></div><div className="mt-2 flex gap-1"><button className={buttonClass} disabled={item.stockFired} onClick={()=>updateItem(item,Number(item.quantity)-1)}><Minus className="h-3 w-3"/></button><span className="px-3 py-2 text-sm">{item.quantity}</span><button className={buttonClass} disabled={item.stockFired} onClick={()=>updateItem(item,Number(item.quantity)+1)}><Plus className="h-3 w-3"/></button><button className={buttonClass} disabled={item.stockFired} onClick={()=>void run('order.addItem',{orderId:active.id,productId:item.productId,quantity:item.quantity,portionId:item.portionSnapshot?.id,modifierIds:(item.modifiers||[]).map((m:any)=>m.id),note:item.note})}>Duplicate</button><button className={buttonClass} disabled={item.stockFired} onClick={()=>void run('order.removeItem',{orderId:active.id,itemId:item.id})}><Trash2 className="h-3 w-3"/></button><button className={buttonClass} onClick={()=>setModal({kind:'COMP',data:item})}>Comp</button></div></div>)}</div>
        <div className="mt-4 space-y-1 border-t border-slate-800 pt-3 text-sm"><div className="flex justify-between"><span>Net</span><span>{money(active.subtotal)}</span></div><div className="flex justify-between"><span>Tax</span><span>{money(active.taxTotal)}</span></div><div className="flex justify-between"><span>Levy</span><span>{money(active.cateringLevyTotal)}</span></div><div className="flex justify-between text-lg font-bold"><span>Total</span><span>{money(active.grandTotal)}</span></div><div className="flex justify-between text-amber-300"><span>Outstanding</span><span>{money(balance)}</span></div></div>
        <div className="mt-4 grid grid-cols-2 gap-2"><button className={primaryButtonClass} onClick={()=>void run('order.fire',{orderId:active.id})}><Flame className="mr-1 inline h-4 w-4"/>Fire</button><button className={buttonClass} onClick={()=>setModal({kind:'PAY'})}><CreditCard className="mr-1 inline h-4 w-4"/>Pay</button><button className={buttonClass} onClick={()=>setModal({kind:'SPLIT'})}><Split className="mr-1 inline h-4 w-4"/>Split tender</button><button className={buttonClass} onClick={()=>setModal({kind:'DISCOUNT'})}>Discount</button><button className={buttonClass} onClick={()=>setModal({kind:'MOVE'})}>Transfer / merge</button><button className={buttonClass} onClick={()=>setModal({kind:'VOID'})}><ShieldAlert className="mr-1 inline h-4 w-4"/>Void</button></div>
      </>}
      {notice&&<p className="mt-4 whitespace-pre-wrap rounded-lg bg-slate-950 p-2 text-xs text-slate-300">{notice}</p>}
    </aside>
    {modal?.kind==='CONFIG'&&active&&<ConfigDialog value={modal.data} onClose={()=>setModal(null)} onSave={async v=>{await run('order.addItem',{orderId:active.id,productId:v.product.id,quantity:v.quantity,portionId:v.portionId||undefined,modifierIds:v.modifierIds});setModal(null);}}/>}
    {modal?.kind==='PAY'&&active&&<PaymentDialog balance={balance} snapshot={snapshot} onClose={()=>setModal(null)} onPay={finishPayment}/>}
    {modal?.kind==='SPLIT'&&active&&<SplitDialog balance={balance} snapshot={snapshot} onClose={()=>setModal(null)} onPay={finishSplit}/>}
    {modal?.kind==='RECEIPT'&&<NativeReceiptDialog order={modal.data.order} payment={modal.data.payment} businessName={recordsOf(snapshot,'organization')[0]?.name||'Business'} outletName={outlets.find(o=>o.id===modal.data.order.outletId)?.name||'Outlet'} cashierName={snapshot.actor.name} onJobsChanged={()=>void refreshPrinterJobs()} onClose={()=>setModal(null)}/>}
    {modal?.kind==='DISCOUNT'&&active&&<ReasonDialog title="Discount order" extra="percent" onClose={()=>setModal(null)} onSubmit={async v=>protectedRun('order.discount',active.id,async token=>{await run('order.discount',{orderId:active.id,percent:v.percent,reason:v.reason,approvalToken:token});setModal(null);})}/>} 
    {modal?.kind==='COMP'&&active&&<ReasonDialog title={`Comp ${modal.data.productName}`} onClose={()=>setModal(null)} onSubmit={async v=>protectedRun('order.comp',modal.data.id,async token=>{await run('order.compItem',{orderId:active.id,itemId:modal.data.id,reason:v.reason,approvalToken:token});setModal(null);})}/>} 
    {modal?.kind==='VOID'&&active&&<VoidDialog onClose={()=>setModal(null)} onSubmit={async v=>protectedRun('order.void',active.id,async token=>{await run('order.void',{orderId:active.id,...v,approvalToken:token});setModal(null);})}/>} 
    {modal?.kind==='MOVE'&&active&&<MoveDialog tables={tables.filter(t=>t.outletId===active.outletId&&t.id!==active.tableId)} onClose={()=>setModal(null)} onSubmit={async v=>protectedRun(v.mode==='MERGE'?'order.merge':'order.transfer',active.id,async token=>{await run(v.mode==='MERGE'?'order.merge':'order.transfer',{orderId:active.id,targetTableId:v.targetTableId,approvalToken:token});setModal(null);})}/>} 
    {approval&&<ManagerApprovalDialog permission={approval.permission} target={approval.target} onClose={()=>setApproval(null)} onApproved={approval.run}/>} 
  </div>;
}

const recordVersion=(snapshot:any,collection:string,id:string)=>snapshot.records.find((r:any)=>r.collection===collection&&r.id===id)?.version;
const ConfigDialog=({value,onSave,onClose}:{value:any;onSave:(v:any)=>Promise<void>;onClose:()=>void})=>{const [v,setV]=useState(value);return <ActionDialog title={`Configure ${v.product.name}`} onClose={onClose}><div className="space-y-4"><label className="block">Quantity<input className={fieldClass} type="number" min="0.001" step="0.001" value={v.quantity} onChange={e=>setV({...v,quantity:Number(e.target.value)})}/></label>{v.product.portions?.length?<label className="block">Portion<select className={fieldClass} value={v.portionId} onChange={e=>setV({...v,portionId:e.target.value})}>{v.product.portions.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {money(p.price)}</option>)}</select></label>:null}{v.product.modifiers?.length?<div><div className="mb-2 text-sm">Modifiers</div>{v.product.modifiers.map((m:any)=><label key={m.id} className="mb-2 flex gap-2"><input type="checkbox" checked={v.modifierIds.includes(m.id)} onChange={e=>setV({...v,modifierIds:e.target.checked?[...v.modifierIds,m.id]:v.modifierIds.filter((x:string)=>x!==m.id)})}/>{m.name} {m.priceDelta?`(+${money(m.priceDelta)})`:''}</label>)}</div>:null}<button className={primaryButtonClass} onClick={()=>void onSave(v)}>Add to tab</button></div></ActionDialog>};
const PaymentDialog=({balance,snapshot,onPay,onClose}:{balance:number;snapshot:any;onPay:(p:any)=>Promise<void>;onClose:()=>void})=>{const config=recordsOf(snapshot,'paymentConfig')[0]||{methods:['CASH']};const [method,setMethod]=useState(config.methods?.[0]||'CASH');const [amount,setAmount]=useState(balance);const [cash,setCash]=useState(balance);const [code,setCode]=useState('');const [card,setCard]=useState('');const account=config.mpesaAccounts?.[0]?.number||'';return <ActionDialog title="Take payment" onClose={onClose}><div className="space-y-3"><select className={fieldClass} value={method} onChange={e=>setMethod(e.target.value)}>{(config.methods||[]).map((m:string)=><option key={m}>{m}</option>)}</select><label>Amount<input className={fieldClass} type="number" min="0.01" max={balance} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>{method==='CASH'&&<label>Cash tendered<input className={fieldClass} type="number" min={amount} value={cash} onChange={e=>setCash(Number(e.target.value))}/></label>}{method==='MPESA'&&<><label>Configured account<input disabled className={fieldClass} value={account}/></label><label>Transaction code<input className={fieldClass} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label></>}{method==='CARD'&&<label>External approval reference<input className={fieldClass} value={card} onChange={e=>setCard(e.target.value)}/></label>}<button className={primaryButtonClass} onClick={()=>void onPay({method,amount,cashTendered:cash,cardAuthCode:card,mpesa:method==='MPESA'?{confirmed:true,code,account,receivedAmount:amount,receivedAt:new Date().toISOString()}:undefined})}>Record payment</button></div></ActionDialog>};
const SplitDialog=({balance,snapshot,onPay,onClose}:{balance:number;snapshot:any;onPay:(p:any[])=>Promise<void>;onClose:()=>void})=>{const config=recordsOf(snapshot,'paymentConfig')[0]||{methods:['CASH']};const methods=config.methods||['CASH'];const [aMethod,setAMethod]=useState(methods[0]);const [bMethod,setBMethod]=useState(methods[1]||methods[0]);const [a,setA]=useState(Math.floor(balance/2));const [code,setCode]=useState('');const [card,setCard]=useState('');const b=Math.max(0,balance-a);const build=(method:string,amount:number)=>({method,amount,cashTendered:method==='CASH'?amount:undefined,cardAuthCode:method==='CARD'?card:undefined,mpesa:method==='MPESA'?{confirmed:true,code,account:config.mpesaAccounts?.[0]?.number||'',receivedAmount:amount,receivedAt:new Date().toISOString()}:undefined});return <ActionDialog title="Split tender" onClose={onClose}><div className="space-y-3"><div className="grid grid-cols-2 gap-2"><select className={fieldClass} value={aMethod} onChange={e=>setAMethod(e.target.value)}>{methods.map((m:string)=><option key={m}>{m}</option>)}</select><input className={fieldClass} type="number" min="0.01" max={balance} value={a} onChange={e=>setA(Number(e.target.value))}/><select className={fieldClass} value={bMethod} onChange={e=>setBMethod(e.target.value)}>{methods.map((m:string)=><option key={m}>{m}</option>)}</select><input disabled className={fieldClass} value={b}/></div>{[aMethod,bMethod].includes('MPESA')&&<input className={fieldClass} placeholder="M-Pesa transaction code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/>} {[aMethod,bMethod].includes('CARD')&&<input className={fieldClass} placeholder="Card approval reference" value={card} onChange={e=>setCard(e.target.value)}/>}<button className={primaryButtonClass} onClick={()=>void onPay([build(aMethod,a),build(bMethod,b)])}>Record split</button></div></ActionDialog>};
const ReasonDialog=({title,extra,onSubmit,onClose}:{title:string;extra?:'percent';onSubmit:(v:any)=>Promise<void>;onClose:()=>void})=>{const [reason,setReason]=useState('');const [percent,setPercent]=useState(10);return <ActionDialog title={title} onClose={onClose}><div className="space-y-3">{extra==='percent'&&<label>Percent<input className={fieldClass} type="number" min="0.01" max="100" value={percent} onChange={e=>setPercent(Number(e.target.value))}/></label>}<label>Reason<textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!reason.trim()} className={primaryButtonClass} onClick={()=>void onSubmit({reason,percent})}>Continue</button></div></ActionDialog>};
const VoidDialog=({onSubmit,onClose}:{onSubmit:(v:any)=>Promise<void>;onClose:()=>void})=>{const [reason,setReason]=useState('');const [disposition,setDisposition]=useState('WASTE');return <ActionDialog title="Void order" onClose={onClose}><div className="space-y-3"><label>Reason<textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Fired stock disposition<select className={fieldClass} value={disposition} onChange={e=>setDisposition(e.target.value)}><option>WASTE</option><option>CONSUMED</option><option>RETURN_SEALED</option><option>MANAGER_ADJUSTMENT</option></select></label><button disabled={!reason.trim()} className={primaryButtonClass} onClick={()=>void onSubmit({reason,disposition})}>Void</button></div></ActionDialog>};
const MoveDialog=({tables,onSubmit,onClose}:{tables:any[];onSubmit:(v:any)=>Promise<void>;onClose:()=>void})=>{const [mode,setMode]=useState('TRANSFER');const [targetTableId,setTarget]=useState(tables[0]?.id||'');return <ActionDialog title="Transfer / merge" onClose={onClose}><div className="space-y-3"><select className={fieldClass} value={mode} onChange={e=>setMode(e.target.value)}><option>TRANSFER</option><option>MERGE</option></select><select className={fieldClass} value={targetTableId} onChange={e=>setTarget(e.target.value)}>{tables.map(t=><option key={t.id} value={t.id}>{t.label} · {t.state}</option>)}</select><button className={primaryButtonClass} disabled={!targetTableId} onClick={()=>void onSubmit({mode,targetTableId})}>{mode==='MERGE'?'Merge':'Transfer'}</button></div></ActionDialog>};
