import React,{useMemo,useState} from 'react';
import {AlertTriangle,Wrench} from 'lucide-react';
import {useRuntime} from '../runtime/RuntimeProvider';
import {buttonClass,fieldClass,recordOf,recordsOf,shortDate} from './records';

// SERVOS_PATCH_06_HOUSEKEEPING
const FLOW:{[key:string]:string}={DIRTY:'CLEANING',CLEANING:'INSPECTION',INSPECTION:'CLEAN'};
const label:{[key:string]:string}={DIRTY:'Start cleaning',CLEANING:'Send to inspection',INSPECTION:'Pass inspection'};
export function NativeHousekeepingView(){
 const runtime=useRuntime();const s=runtime.snapshot!;const rooms=recordsOf(s,'rooms'),types=recordsOf(s,'roomTypes'),blocks=recordsOf(s,'roomBlocks'),reservations=recordsOf(s,'roomReservations');
 const [query,setQuery]=useState('');const [message,setMessage]=useState('');
 const visible=useMemo(()=>rooms.filter(r=>`${r.number} ${r.floor||''} ${r.wing||''}`.toLowerCase().includes(query.toLowerCase())),[rooms,query]);
 const command=async(op:string,payload:any,version?:number)=>{setMessage('');try{await runtime.command(op,payload,version);setMessage('Housekeeping action committed.')}catch(e){setMessage(String(e))}};
 const transition=async(room:any,state:string)=>{const rec=recordOf(s,'rooms',room.id);if(rec)await command('room.housekeeping',{id:room.id,state},rec.version)};
 const condition=async(room:any)=>{const rec=recordOf(s,'rooms',room.id);if(!rec)return;const next=room.maintenanceState==='OUT_OF_ORDER'?'AVAILABLE':'OUT_OF_ORDER';const reason=next==='OUT_OF_ORDER'?window.prompt('Reason / defect')||'':'';if(next==='AVAILABLE'||reason.trim())await command('room.condition',{id:room.id,state:next,reason},rec.version)};
 const release=async(block:any)=>{const inspection=window.prompt('Inspection / release note');const rec=recordOf(s,'roomBlocks',block.id);if(inspection?.trim()&&rec)await command('room.unblock',{id:block.id,inspection:inspection.trim()},rec.version)};
 const columns=['DIRTY','CLEANING','INSPECTION','CLEAN'];
 return <div className="h-full overflow-auto bg-slate-950 p-5 text-white">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Housekeeping</h1><p className="mt-1 text-sm text-slate-400">Room readiness is independent from occupancy. Cleaning state changes are versioned and audited.</p></div><input className={fieldClass+' max-w-xs'} placeholder="Filter room / floor / wing…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
   {message&&<p role="status" className="mt-4 rounded-xl bg-slate-900 p-3 text-sm text-slate-300">{message}</p>}
   <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Dirty" value={visible.filter(r=>r.housekeepingState==='DIRTY').length}/><Metric label="Cleaning" value={visible.filter(r=>r.housekeepingState==='CLEANING').length}/><Metric label="Inspection" value={visible.filter(r=>r.housekeepingState==='INSPECTION').length}/><Metric label="Out of order" value={visible.filter(r=>r.maintenanceState==='OUT_OF_ORDER').length}/></section>
   <section className="mt-6 grid min-w-0 gap-4 xl:grid-cols-4">{columns.map(state=><div key={state} className="min-w-0 rounded-2xl border border-slate-800 bg-slate-900 p-3"><div className="mb-3 flex items-center justify-between"><b>{state}</b><span className="rounded-full bg-slate-950 px-2 py-1 text-xs text-slate-500">{visible.filter(r=>(r.housekeepingState||'CLEAN')===state).length}</span></div><div className="space-y-2">{visible.filter(r=>(r.housekeepingState||'CLEAN')===state).map(room=>{const activeRes=reservations.find(r=>r.roomId===room.id&&['RESERVED','CHECKED_IN'].includes(r.status));const roomBlocks=blocks.filter(b=>b.roomId===room.id&&b.status==='ACTIVE');return <article key={room.id} className="rounded-xl bg-slate-950 p-3"><div className="flex justify-between gap-2"><div><div className="font-bold">Room {room.number}</div><div className="text-[11px] text-slate-500">{types.find(t=>t.id===room.roomTypeId)?.name||room.roomTypeId} · {room.floor||'—'} / {room.wing||'—'}</div></div>{room.maintenanceState==='OUT_OF_ORDER'&&<AlertTriangle className="h-4 w-4 text-rose-300"/>}</div>{activeRes&&<div className="mt-2 text-xs text-sky-300">{activeRes.status==='CHECKED_IN'?'Occupied':'Reserved'} · {shortDate(activeRes.endsAt)}</div>}{roomBlocks.map(b=><div key={b.id} className="mt-2 rounded-lg border border-amber-800/30 p-2 text-xs text-amber-200"><div>{b.reason}</div><div className="text-[10px] text-slate-500">{shortDate(b.startsAt)} → {shortDate(b.endsAt)}</div><button className="mt-1 underline" onClick={()=>void release(b)}>Release block</button></div>)}<div className="mt-3 flex flex-wrap gap-2">{FLOW[state]&&<button className={buttonClass} onClick={()=>void transition(room,FLOW[state])}>{label[state]}</button>}{state==='INSPECTION'&&<button className={buttonClass} onClick={()=>void transition(room,'DIRTY')}>Fail inspection</button>}{state==='CLEAN'&&<button className={buttonClass} onClick={()=>void transition(room,'DIRTY')}>Mark dirty</button>}<button className={buttonClass} onClick={()=>void condition(room)}>{room.maintenanceState==='OUT_OF_ORDER'?'Return to service':'Out of order'}</button></div></article>})}</div></div>)}</section>
   <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex gap-3"><Wrench className="mt-0.5 h-5 w-5 text-amber-300"/><div><b>Maintenance linkage</b><p className="mt-1 text-xs text-slate-400">Patch 06 can mark rooms out of order and manage interval blocks. Linking blocks to maintenance work orders waits for Patch 08, when maintenance has its own lifecycle and evidence.</p></div></div></section>
 </div>
}
const Metric=({label,value}:{label:string;value:number})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>;
