import React, { useMemo, useState } from 'react';
import { useRuntime } from '../runtime/RuntimeProvider';
import { buttonClass, fieldClass, primaryButtonClass, recordOf, recordsOf } from './records';

const steps = [
  ['BUSINESS_IDENTITY','Business identity',true],['TAX','Tax configuration',true],['PAYMENTS','Payment methods',true],['SERVICE_AREAS','Service areas',true],
  ['STOCK_LOCATIONS','Stock locations',true],['CATALOG','Catalog & stock master',true],['RECIPES_PORTIONS','Recipes & portions',false],['OPENING_INVENTORY','Opening inventory',true],
  ['FLOORPLAN','Tables & floorplan',false],['STAFF_ACCESS','Staff & access',true],['TILL','Till configuration',true],['BACKUP_SYNC','Backup & synchronization',false]
] as const;

export const SetupWizard = () => {
  const runtime = useRuntime();
  const snapshot = runtime.snapshot!;
  const progress = recordsOf(snapshot, 'businessSetup')[0] || { completedSteps: [] };
  const done: string[] = progress.completedSteps || [];
  const [active, setActive] = useState<string>(steps.find(s => !done.includes(s[0]))?.[0] || 'BUSINESS_IDENTITY');
  const [message, setMessage] = useState('');
  const complete = async (step: string, nextStep?: string) => { await runtime.command('setup.completeStep', { step, nextStep }); setMessage(`${step.replaceAll('_',' ')} completed.`); };
  const save = async (collection: string, id: string, data: Record<string, unknown>) => {
    const existing = recordOf(runtime.snapshot, collection, id);
    await runtime.command('record.save', { collection, id, data: { ...(existing?.data || {}), ...data } }, existing?.version);
  };
  const required = steps.filter(s => s[2]).map(s => s[0]);
  const ready = required.every(s => done.includes(s));
  const percent = Math.round(done.filter(s => required.includes(s as any)).length / required.length * 100);
  const content = (() => {
    switch (active) {
      case 'BUSINESS_IDENTITY': return <IdentityStep onSave={async values => { await save('organization','business',values); await save('property','property',{ name: values.name, legalName: values.legalName, phone: values.phone, email: values.email, address: values.address, kraPin: values.kraPin, receiptFooter: values.receiptFooter, currency:'KES', timezone:'Africa/Nairobi' }); await complete(active,'TAX'); }} existing={recordsOf(snapshot,'organization')[0] || {}} />;
      case 'TAX': return <TaxStep existing={recordsOf(snapshot,'property')[0] || {}} onSave={async values => { await save('property','property',{ taxConfigured:true, pricesIncludeTax:true, ...values }); await complete(active,'PAYMENTS'); }} />;
      case 'PAYMENTS': return <PaymentStep intake={runtime.status?.intakeProfile} existing={recordsOf(snapshot,'paymentConfig')[0]} onSave={async data => { await save('paymentConfig','main',{ name:'Payments', ...data }); await complete(active,'SERVICE_AREAS'); }} />;
      case 'SERVICE_AREAS': return <NameListStep title="Service areas" initial={runtime.status?.intakeProfile?.serviceAreas || ['Main Bar']} existing={recordsOf(snapshot,'outlets')} onCreate={async names => { const existingNames=new Set(recordsOf(runtime.snapshot,'outlets').map(x=>String(x.name).trim().toLowerCase())); for (const name of names) if(!existingNames.has(name.toLowerCase())) await save('outlets', crypto.randomUUID(), { name, propertyId:'property', type:'BAR', active:true, defaultStockLocationId:null }); await complete(active,'STOCK_LOCATIONS'); }} />;
      case 'STOCK_LOCATIONS': return <NameListStep title="Stock locations" initial={runtime.status?.intakeProfile?.stockAreas || ['Main Store','Bar Store']} existing={recordsOf(snapshot,'stockLocations')} onCreate={async names => { const before=recordsOf(runtime.snapshot,'stockLocations'); const existingNames=new Set(before.map(x=>String(x.name).trim().toLowerCase())); const created:string[]=[]; for (const name of names) if(!existingNames.has(name.toLowerCase())) { const id=crypto.randomUUID(); created.push(id); await save('stockLocations',id,{ name, propertyId:'property', type:name.toLowerCase().includes('fridge')?'FRIDGE':'STORE' }); } const first=before[0]?.id || created[0]; if(!first) throw new Error('Create at least one stock location'); for (const outlet of recordsOf(runtime.snapshot,'outlets')) await save('outlets',outlet.id,{ ...outlet, defaultStockLocationId:first }); await complete(active,'CATALOG'); }} />;
      case 'CATALOG': return <FirstCatalogStep snapshot={snapshot} onSave={async input => { const stockId=crypto.randomUUID(); await save('stockItems',stockId,{ name:input.stockName,code:input.code,baseUnit:input.baseUnit,averageUnitCost:input.cost,currentStock:{} }); const outletIds=recordsOf(runtime.snapshot,'outlets').map(x=>x.id); await save('products',crypto.randomUUID(),{ name:input.productName,code:input.code,price:input.price,category:input.category,routeTo:'BAR',outletIds,stockItemId:stockId,portionVolume:input.portionVolume,taxClassId:'A_STANDARD',favorite:true,barcode:input.barcode,portions:[],modifiers:[],recipeIngredients:[] }); await complete(active,'RECIPES_PORTIONS'); }} products={recordsOf(snapshot,'products')} />;
      case 'RECIPES_PORTIONS': return <SimpleComplete title="Recipes & portions" description="Detailed portions, recipes, modifiers and mixers are maintained in Catalog Studio. You can configure them now after setup or skip this optional step." onComplete={() => complete(active,'OPENING_INVENTORY')} />;
      case 'OPENING_INVENTORY': return <OpeningInventoryStep snapshot={snapshot} onPost={async (stockItemId,locationId,quantity) => runtime.command('inventory.openingBalance',{ stockItemId,locationId,quantity,reason:'Opening stock count' })} onComplete={() => complete(active,'FLOORPLAN')} />;
      case 'FLOORPLAN': return <FloorSetup snapshot={snapshot} suggested={runtime.status?.intakeProfile?.estimatedTables || 0} onSave={async (outletId,count) => { const tables=Array.from({length:count},(_,i)=>({ id:crypto.randomUUID(), label:String(i+1), capacity:4, section:'MAIN', shape:'SQUARE', posX:5+(i%4)*23, posY:10+Math.floor(i/4)*22, minimumSpend:0, isJoinable:true })); await runtime.command('floorplan.save',{ outletId, baseline:[], tables }); await complete(active,'STAFF_ACCESS'); }} onSkip={() => complete(active,'STAFF_ACCESS')} />;
      case 'STAFF_ACCESS': return <StaffSetup onCreate={(data) => runtime.command('staff.create',data)} staff={runtime.status?.staff || []} onComplete={() => complete(active,'TILL')} />;
      case 'TILL': return <TillPolicyStep existing={recordsOf(snapshot,'tillPolicy')[0]} onSave={async data => { await save('tillPolicy','main',{ name:'Till policy', ...data }); await complete(active,'BACKUP_SYNC'); }} />;
      case 'BACKUP_SYNC': return <BackupSetup onBackup={runtime.backup} onSync={runtime.sync} onComplete={() => complete(active)} />;
      default: return null;
    }
  })();
  return <div className="min-h-screen bg-slate-950 text-slate-100"><header className="border-b border-slate-800 bg-slate-900 px-5 py-4"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div><div className="text-xs font-bold tracking-[.2em] text-amber-400">BUSINESS SETUP</div><h1 className="text-xl font-black">Configure the real bar before trading</h1></div><button className={buttonClass} onClick={() => void runtime.lock()}>Lock terminal</button></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 p-5 lg:grid-cols-[320px_1fr]"><aside className="space-y-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between text-sm"><span>Required setup</span><strong>{percent}%</strong></div><div className="mt-2 h-2 rounded-full bg-slate-800"><div className="h-2 rounded-full bg-amber-400" style={{width:`${percent}%`}} /></div></div>{steps.map(([id,label,requiredStep]) => <button key={id} onClick={() => setActive(id)} className={`w-full rounded-xl border p-3 text-left ${active===id?'border-amber-400 bg-amber-500/10':'border-slate-800 bg-slate-900'}`}><div className="flex items-center justify-between"><span className="font-semibold">{label}</span><span className={done.includes(id)?'text-emerald-400':'text-slate-600'}>{done.includes(id)?'✓':'○'}</span></div><span className="text-xs text-slate-500">{requiredStep?'Required':'Optional'}</span></button>)}</aside>
      <main className="space-y-4">{message && <p className="rounded-xl border border-emerald-900 bg-emerald-950/50 p-3 text-sm text-emerald-300">{message}</p>}{runtime.error && <p className="rounded-xl bg-rose-950 p-3 text-sm text-rose-200">{runtime.error}</p>}{content}<section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><h2 className="font-bold">Go-live readiness</h2><p className="mt-2 text-sm text-slate-400">{ready || snapshot.installationStage==='READY_FOR_GO_LIVE' ? 'Required configuration is complete. Confirm that it represents the real business before activating live trading.' : 'Complete every required setup step. Optional steps can be finished later.'}</p><button className={`${primaryButtonClass} mt-4`} disabled={!ready && snapshot.installationStage!=='READY_FOR_GO_LIVE'} onClick={() => void runtime.command('setup.goLive').then(() => setMessage('ServOS is LIVE.'))}>Approve Go Live</button></section></main>
    </div></div>;
};

const Panel = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>;
const IdentityStep = ({existing,onSave}:{existing:any;onSave:(v:any)=>Promise<void>}) => { const [v,setV]=useState({name:existing.name||'',legalName:existing.legalName||existing.name||'',phone:existing.phone||'',email:existing.email||'',address:existing.address||'',kraPin:existing.kraPin||'',receiptFooter:existing.receiptFooter||''}); return <Panel title="1. Business identity"><div className="grid gap-3 md:grid-cols-2">{Object.entries(v).map(([k,val])=><label key={k} className="text-sm capitalize">{k.replace(/[A-Z]/g,m=>` ${m}`)}<input className={fieldClass} value={String(val)} onChange={e=>setV(x=>({...x,[k]:e.target.value}))}/></label>)}</div><button className={primaryButtonClass} onClick={()=>void onSave(v)}>Save identity & continue</button></Panel> };
const TaxStep = ({existing,onSave}:{existing:any;onSave:(v:any)=>Promise<void>}) => { const [vat,setVat]=useState(existing.vatRatePct??0);const [levy,setLevy]=useState(existing.levyRatePct??0);return <Panel title="2. Tax configuration"><p className="text-sm text-slate-400">Enter the rates that actually apply to this business. ServOS does not submit fiscal documents in this release.</p><div className="grid gap-3 md:grid-cols-2"><label>VAT %<input className={fieldClass} type="number" min="0" max="100" step="0.01" value={vat} onChange={e=>setVat(Number(e.target.value))}/></label><label>Catering levy %<input className={fieldClass} type="number" min="0" max="100" step="0.01" value={levy} onChange={e=>setLevy(Number(e.target.value))}/></label></div><button className={primaryButtonClass} onClick={()=>void onSave({vatRatePct:vat,levyRatePct:levy})}>Confirm tax policy</button></Panel> };
const PaymentStep = ({intake,existing,onSave}:{intake:any;existing:any;onSave:(v:any)=>Promise<void>}) => {const [methods,setMethods]=useState<string[]>(existing?.methods||intake?.paymentMethods||['CASH']);const [mpesa,setMpesa]=useState(existing?.mpesaAccounts?.[0]?.number||intake?.mpesaAccount||'');const toggle=(x:string)=>setMethods(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);return <Panel title="3. Payments"><div className="flex gap-2">{['CASH','MPESA','CARD'].map(x=><button key={x} className={methods.includes(x)?primaryButtonClass:buttonClass} onClick={()=>toggle(x)}>{x}</button>)}</div>{methods.includes('MPESA')&&<label className="block">Business M-Pesa Till / Paybill<input className={fieldClass} value={mpesa} onChange={e=>setMpesa(e.target.value)}/></label>}<button className={primaryButtonClass} disabled={!methods.length||methods.includes('MPESA')&&!mpesa.trim()} onClick={()=>void onSave({methods,mpesaAccounts:methods.includes('MPESA')?[{label:'Primary M-Pesa',number:mpesa.trim()}]:[]})}>Save payments</button></Panel>};
const NameListStep=({title,initial,existing,onCreate}:{title:string;initial:string[];existing:any[];onCreate:(n:string[])=>Promise<void>})=>{const [value,setValue]=useState(initial.join(', '));return <Panel title={title}><p className="text-sm text-slate-400">Existing: {existing.length?existing.map(x=>x.name).join(', '):'none'}</p><label>Names, comma separated<input className={fieldClass} value={value} onChange={e=>setValue(e.target.value)}/></label><button className={primaryButtonClass} onClick={()=>void onCreate(value.split(',').map(x=>x.trim()).filter(Boolean))}>Create from list & continue</button></Panel>};
const FirstCatalogStep=({products,onSave}:{snapshot:any;products:any[];onSave:(v:any)=>Promise<void>})=>{const [v,setV]=useState({stockName:'',productName:'',code:'',baseUnit:'ml',cost:0,price:0,category:'SPIRITS',portionVolume:30,barcode:''});return <Panel title="6. First catalog item"><p className="text-sm text-slate-400">{products.length?`${products.length} product(s) already configured. You can complete this step by adding another item or use Catalog Studio later.`:'Create one real stock/sellable pair. No sample catalog will be inserted automatically.'}</p><div className="grid gap-3 md:grid-cols-2">{Object.entries(v).map(([k,val])=><label key={k} className="text-sm capitalize">{k.replace(/[A-Z]/g,m=>` ${m}`)}<input className={fieldClass} type={typeof val==='number'?'number':'text'} value={val} onChange={e=>setV(x=>({...x,[k]:typeof val==='number'?Number(e.target.value):e.target.value}))}/></label>)}</div><button className={primaryButtonClass} disabled={!v.stockName.trim()||!v.productName.trim()||!v.code.trim()||v.price<0} onClick={()=>void onSave(v)}>Create item & continue</button></Panel>};
const SimpleComplete=({title,description,onComplete}:{title:string;description:string;onComplete:()=>Promise<void>})=><Panel title={title}><p className="text-sm text-slate-400">{description}</p><button className={buttonClass} onClick={()=>void onComplete()}>Mark optional step complete</button></Panel>;
const OpeningInventoryStep=({snapshot,onPost,onComplete}:{snapshot:any;onPost:(s:string,l:string,q:number)=>Promise<any>;onComplete:()=>Promise<void>})=>{const stocks=recordsOf(snapshot,'stockItems');const locations=recordsOf(snapshot,'stockLocations');const [s,setS]=useState(stocks[0]?.id||'');const [l,setL]=useState(locations[0]?.id||'');const [q,setQ]=useState(0);return <Panel title="8. Opening inventory"><div className="grid gap-3 md:grid-cols-3"><select className={fieldClass} value={s} onChange={e=>setS(e.target.value)}>{stocks.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={fieldClass} value={l} onChange={e=>setL(e.target.value)}>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={fieldClass} type="number" min="0" step="0.001" value={q} onChange={e=>setQ(Number(e.target.value))}/></div><div className="flex gap-3"><button className={buttonClass} onClick={()=>void onPost(s,l,q)}>Post opening balance</button><button className={primaryButtonClass} onClick={()=>void onComplete()}>Opening stock acknowledged</button></div></Panel>};
const FloorSetup=({snapshot,suggested,onSave,onSkip}:{snapshot:any;suggested:number;onSave:(o:string,n:number)=>Promise<void>;onSkip:()=>Promise<void>})=>{const outlets=recordsOf(snapshot,'outlets');const [o,setO]=useState(outlets[0]?.id||'');const [n,setN]=useState(Math.max(1,suggested||6));return <Panel title="9. Tables & floorplan"><p className="text-sm text-slate-400">Counter-only bars can skip this optional step.</p><div className="flex gap-3"><select className={fieldClass} value={o} onChange={e=>setO(e.target.value)}>{outlets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={fieldClass} type="number" min="1" max="100" value={n} onChange={e=>setN(Number(e.target.value))}/></div><div className="flex gap-3"><button className={primaryButtonClass} onClick={()=>void onSave(o,n)}>Create simple floorplan</button><button className={buttonClass} onClick={()=>void onSkip()}>Skip</button></div></Panel>};
const StaffSetup=({onCreate,staff,onComplete}:{onCreate:(d:any)=>Promise<any>;staff:any[];onComplete:()=>Promise<void>})=>{const [name,setName]=useState('');const [pin,setPin]=useState('');const [role,setRole]=useState('Server');const [jobTitle,setJobTitle]=useState('Bartender');return <Panel title="10. Staff & access"><p className="text-sm text-slate-400">Current staff: {staff.map(x=>`${x.name} (${x.role})`).join(', ')}</p><div className="grid gap-3 md:grid-cols-2"><input className={fieldClass} placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input className={fieldClass} placeholder="Job title" value={jobTitle} onChange={e=>setJobTitle(e.target.value)}/><select className={fieldClass} value={role} onChange={e=>setRole(e.target.value)}><option>Server</option><option>Manager</option><option>Admin</option></select><input className={fieldClass} type="password" inputMode="numeric" placeholder="6–12 digit PIN" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,12))}/></div><div className="flex gap-3"><button className={buttonClass} disabled={!name||pin.length<6} onClick={()=>void onCreate({name,pin,role,jobTitle}).then(()=>{setName('');setPin('');})}>Create staff</button><button className={primaryButtonClass} onClick={()=>void onComplete()}>Complete access setup</button></div></Panel>};
const TillPolicyStep=({existing,onSave}:{existing:any;onSave:(v:any)=>Promise<void>})=>{const [openingFloat,setOpeningFloat]=useState(existing?.defaultOpeningFloat??0);const [variance,setVariance]=useState(existing?.varianceThreshold??50);const [printer,setPrinter]=useState(existing?.receiptPrinterMode??'OS_PRINT');const [drawer,setDrawer]=useState(existing?.cashDrawerMode??'MANUAL');return <Panel title="11. Till policy"><div className="grid gap-3 md:grid-cols-2"><label>Default opening float<input className={fieldClass} type="number" min="0" value={openingFloat} onChange={e=>setOpeningFloat(Number(e.target.value))}/></label><label>Variance warning threshold<input className={fieldClass} type="number" min="0" value={variance} onChange={e=>setVariance(Number(e.target.value))}/></label><label>Receipt printing<select className={fieldClass} value={printer} onChange={e=>setPrinter(e.target.value)}><option value="OS_PRINT">OS print / PDF</option><option value="MANUAL">Manual</option></select></label><label>Cash drawer<select className={fieldClass} value={drawer} onChange={e=>setDrawer(e.target.value)}><option value="MANUAL">Manual drawer</option><option value="ADAPTER">Adapter when configured</option></select></label></div><button className={primaryButtonClass} onClick={()=>void onSave({defaultOpeningFloat:openingFloat,varianceThreshold:variance,receiptPrinterMode:printer,cashDrawerMode:drawer})}>Save till policy</button></Panel>};
const BackupSetup=({onBackup,onSync,onComplete}:{onBackup:()=>Promise<string>;onSync:()=>Promise<void>;onComplete:()=>Promise<void>})=>{const [log,setLog]=useState('');return <Panel title="12. Backup & synchronization"><p className="text-sm text-slate-400">Cloud failure is a warning, not a local trading blocker after enrollment.</p><div className="flex flex-wrap gap-3"><button className={buttonClass} onClick={()=>void onBackup().then(path=>setLog(`Backup created: ${path}`)).catch(e=>setLog(String(e)))}>Test local backup</button><button className={buttonClass} onClick={()=>void onSync().then(()=>setLog('Synchronization test completed.')).catch(e=>setLog(`Sync warning: ${String(e)}`))}>Test sync</button><button className={primaryButtonClass} onClick={()=>void onComplete()}>Finish optional step</button></div>{log&&<pre className="whitespace-pre-wrap rounded-xl bg-slate-950 p-3 text-xs text-slate-300">{log}</pre>}</Panel>};
