import fs from 'node:fs';import path from 'node:path';
const fail=[];const required=['docs/README.md','docs/CURRENT_RELEASE_STATE.md','docs/FEATURE_COVERAGE_MATRIX.md','docs/GAP_ANALYSIS_AND_ROADMAP.md','docs/IMPLEMENTATION_PLAN.md','docs/DATA_DICTIONARY.md','docs/MODULE_WORKFLOWS.md','docs/SYSTEM_ARCHITECTURE.md','docs/DEPLOYMENT_RUNBOOK.md','docs/RBAC_AND_PERMISSIONS.md','docs/ONBOARDING_AND_SETUP.md','docs/COMPLETION_LEDGER.md','docs/CHANGELOG.md','docs/TEST_EVIDENCE.md','docs/BAR_PRODUCTION_ACCEPTANCE.md'];
for(const f of required)if(!fs.existsSync(f))fail.push(`Missing ${f}`);
const store=fs.readFileSync('src-tauri/src/store.rs','utf8');const permissionMatch=store.match(/pub const ALL_PERMISSIONS:[\s\S]*?\];/);const permissionSource=permissionMatch?.[0]||'';
const guides=fs.readdirSync('docs/user-guide').filter(f=>f.endsWith('.md'));for(const file of guides){const text=fs.readFileSync(path.join('docs/user-guide',file),'utf8');for(const key of ['Section:','Roles:','Permission:','Screen:','## Overview','## Procedure'])if(!text.includes(key))fail.push(`${file} missing ${key}`);const perm=text.split('\n').find(x=>x.startsWith('Permission: '))?.slice(12).trim();if(perm&&perm!=='none'&&!permissionSource.includes(`"${perm}"`))fail.push(`${file} unknown permission ${perm}`)}
const docs=fs.readdirSync('docs').filter(f=>f.endsWith('.md')).map(f=>'docs/'+f);for(const f of docs){const text=fs.readFileSync(f,'utf8');for(const m of text.matchAll(/\[[^\]]+\]\(([^)]+\.md)(?:#[^)]+)?\)/g)){const target=path.normalize(path.join(path.dirname(f),m[1]));if(!fs.existsSync(target))fail.push(`${f} broken link ${m[1]}`)}}
for(const forbidden of ['JAM-','loc-bar-store','loc-warehouse']){const nativeFiles=[];const walk=d=>fs.readdirSync(d,{withFileTypes:true}).forEach(e=>e.isDirectory()?walk(path.join(d,e.name)):nativeFiles.push(path.join(d,e.name)));walk('src/native');for(const f of nativeFiles)if(fs.readFileSync(f,'utf8').includes(forbidden))fail.push(`${f} contains demo token ${forbidden}`)}
for(const expected of ['table.ready','floorplan.save','setup.goLive','payment.refund','closeDay.generate'])if(!store.includes(`"${expected}"`))fail.push(`Native command missing ${expected}`);
const index=JSON.parse(fs.readFileSync('src/generated/help-index.json','utf8'));if(index.count!==guides.length)fail.push(`Help index count ${index.count} != guide files ${guides.length}`);
if(fail.length){console.error(fail.join('\n'));process.exit(1)}console.log(`Documentation checks passed: ${guides.length} guides, ${required.length} core docs.`);
